# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-15 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20160429_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='_id',
        ),
    ]
