#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['metadsl_visualize']

package_data = \
{'': ['*']}

install_requires = \
['metadsl', 'black', 'typez']

entry_points = \
{'pytest11': ['metadsl_visualize = metadsl_visualize.plugin']}

setup(name='metadsl_visualize',
      version='0.3.0',
      description='Visualize metadsl objects with graphviz',
      author='Saul Shanabrook',
      author_email='s.shanabrook@gmail.com',
      url='https://github.com/Quansight-Labs/metadsl',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
