
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-23T08:45:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d000984e61d33053445ee44e70f01e66f236210",
 "version": "v0.1.1.a1.post20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
