name: Python application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        name: [
          "ubuntu-py37",
          "ubuntu-py38",

          "macos-py37",
          "macos-py38",
        ]
        include:
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
            tox_env: "py37"
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "py38"
          - name: "macos-py37"
            python: "3.7"
            os: macos-latest
            tox_env: "py37"
          - name: "macos-py38"
            python: "3.8"
            os: macos-latest
            tox_env: "py38"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.ini

    - name: Test with tox
      run: "tox -e ${{ matrix.tox_env }}"
