#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This file was generated by Alchemist - Automated build system based on Buildbot.
It is intended for propagation of build information back to the original project.
"""

__bauthor__ = "Alchemist - Automated build system based on Buildbot"
__brevision__ = "556887b0588868b3e7460d6f3a6ed7f39ade5a05"
__bcodename__ = "production"
__bsuite__ = "stable"
__bversion__ = "2.6.5.151"
__bversion_full__ = "2.6.5.151-556887b0588868b3e7460d6f3a6ed7f39ade5a05 (production-stable)"
__bdate__ = "2020-03-06T09:22:29.476585"