
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-28T12:50:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9595d585712bc77ecc70b6b9e476eef032586309",
 "version": "v0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
