# Generated by Django 2.2.6 on 2020-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_review_is_reviewd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_anonym',
            field=models.CharField(default='Аноним', max_length=30),
        ),
    ]
