[tool.poetry]
name = "datatosk"
version = "0.1.0"
description = ""
authors = ["Miłosz Bednarzak <milosz.bednarzak@bethink.pl>", "Kuba Karmiński <kuba.karminski@bethink.pl>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
