
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-25T17:22:02-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9e6841482b299fceadc5ad548c2dbf58a8f1227",
 "version": "0.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
