# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_file
from pulpcore.client.pulp_file.models.repository_sync_url import RepositorySyncURL  # noqa: E501
from pulpcore.client.pulp_file.rest import ApiException


class TestRepositorySyncURL(unittest.TestCase):
    """RepositorySyncURL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositorySyncURL(self):
        """Test RepositorySyncURL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulp_file.models.repository_sync_url.RepositorySyncURL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
