
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-27T15:12:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3adeec83935aebf66ec179f8df47aef17802935f",
 "version": "0.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
