[tool.poetry]
name = "jrpytorch"
version = "0.1.5"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.15"
torch = "^1.0"
sklearn = "^0.0.0"
torchvision = "^0.5.0"
matplotlib = "^3.0"
pandas = "^0.23.4"
visdom = "^0.1.8"

[tool.poetry.dev-dependencies]
