[tool.poetry]
name = "django-mongoengine"
version = "0.4.0-alpha.0"
description = "Django support for MongoDB via MongoEngine"
authors = ["Ross Lawley <ross.lawley@gmail.com>"]

[tool.poetry.dependencies]
python = ">=2.7 || >=3.6"
django = ">1.11"
mongoengine = ">=0.14"

[tool.poetry.dev-dependencies]
sphinx = "*"
nose = "*"
coverage = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
