"""
  Copyright (c) 2020 VMware, Inc. All rights reserved.
"""
from .virtual_system_caption_type import VirtualSystemCaptionType
from .qualifier_s_int64 import QualifierSInt64
from .cim_hex_binary import CimHexBinary
from .virtual_hardware_section_type import VirtualHardwareSectionType
from .automatic_startup_action import AutomaticStartupAction
from .icon import Icon
from .item import Item
from .vssd_type import VSSDType
from .cim_reference import CimReference
from .resource_allocation_section_type import ResourceAllocationSectionType
from .cim_base64_binary import CimBase64Binary
from .virtual_system_type import VirtualSystemType
from .cim_long import CimLong
from .cim_any_simple_type import CimAnySimpleType
from .disk_section_type import DiskSectionType
from .network_section_type import NetworkSectionType
from .configuration import Configuration
from .cim_date_time import CimDateTime
from .rasd_type import RASDType
from .startup_section_type import StartupSectionType
from .eula_section_type import EulaSectionType
from .product_section_type import ProductSectionType
from .cim_string import CimString
from .cim_double import CimDouble
from .mapping_behavior import MappingBehavior
from .strings_type import StringsType
from .annotation_section_type import AnnotationSectionType
from .operating_system_section_type import OperatingSystemSectionType
from .cim_unsigned_byte import CimUnsignedByte
from .cim_char16 import CimChar16
from .cim_float import CimFloat
from .cim_int import CimInt
from .section_type import SectionType
from .strings_msg import StringsMsg
from .cim_unsigned_int import CimUnsignedInt
from .cim_unsigned_long import CimUnsignedLong
from .cim_short import CimShort
from .virtual_system_changeable_type_type import VirtualSystemChangeableTypeType
from .resource_allocation_changeable_type_type import ResourceAllocationChangeableTypeType
from .qualifier_string import QualifierString
from .content_type import ContentType
from .cim_virtual_system_setting_data_type import CIMVirtualSystemSettingDataType
from .resource_type import ResourceType
from .envelope_type import EnvelopeType
from .cim_unsigned_short import CimUnsignedShort
from .automatic_shutdown_action import AutomaticShutdownAction
from .network_section_network import NetworkSectionNetwork
from .resource_allocation_caption_type import ResourceAllocationCaptionType
from .consumer_visibility import ConsumerVisibility
from .startup_section_item import StartupSectionItem
from .cim_byte import CimByte
from .virtual_disk_desc_type import VirtualDiskDescType
from .property_configuration_value_type import PropertyConfigurationValueType
from .file_type import FileType
from .deployment_option_section_configuration import DeploymentOptionSectionConfiguration
from .install_section_type import InstallSectionType
from .references_type import ReferencesType
from .automatic_recovery_action import AutomaticRecoveryAction
from .network import Network
from .qualifier_u_int32 import QualifierUInt32
from .property import Property
from .qualifier_boolean import QualifierBoolean
from .product_section_property import ProductSectionProperty
from .virtual_system_collection_type import VirtualSystemCollectionType
from .qualifier_s_array import QualifierSArray
from .product_section_icon import ProductSectionIcon
from .msg import Msg
from .deployment_option_section_type import DeploymentOptionSectionType
from .cim_boolean import CimBoolean
from .msg_type import MsgType
from .cim_resource_allocation_setting_data_type import CIMResourceAllocationSettingDataType
