# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0008_root_non_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='arity',
        ),
    ]
