
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <frc\buttons\NetworkButton.h>



#include <rpygen/frc__Button.hpp>

namespace rpygen {

using namespace frc;


template <typename CxxBase>
using PyBasefrc__NetworkButton = 
    Pyfrc__Button<
        CxxBase
    
    >
;

template <typename CxxBase>
struct Pyfrc__NetworkButton : PyBasefrc__NetworkButton<CxxBase> {
    using PyBasefrc__NetworkButton<CxxBase>::PyBasefrc__NetworkButton;



#ifndef RPYGEN_DISABLE_Get_v
    bool Get() override {
PYBIND11_OVERLOAD_NAME(bool, CxxBase, "get", Get,);    }
#endif



};

}; // namespace rpygen
