# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 04:33
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0003_auto_20170823_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationmode',
            name='name',
            field=aristotle_mdr.fields.ShortTextField(help_text='The primary name used for human identification purposes.'),
        ),
    ]
