# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 05:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0005_auto_20190502_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationmode',
            name='definition',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Representation of a concept by a descriptive statement which serves to differentiate it from related concepts. (3.2.39)', verbose_name='definition'),
        ),
    ]
