sudo: false

dist: xenial
services:
  - xvfb

language: python


python:
    - 3.6
    - 3.7
    - 3.8

env: 
    - version=latest


before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

addons:
  apt:
    packages:
    - libxkbcommon-x11-0


install:
  - python -m pip install --upgrade pip
  - if [[ $version == latest ]]; then pip install -r requirements.txt codecov ; fi
  - python setup.py install
  - python -m pip install --upgrade numpy scipy matplotlib pandas tqdm PyQt5 lmfit
  - pip list


script:
  - cd pysprint/tests
  - python -m unittest
  - coverage run -m unittest


after_success:
  - codecov