# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 02:20
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_slots', '0003_correct_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='concept',
            field=aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='aristotle_mdr._concept'),
        ),
    ]
