# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_review_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date and time a response is required', null=True, verbose_name='Date response required'),
        ),
    ]
