stages:
  - pypi

pypi:push:
  stage: pypi
  image: python:3.7
  before_script:
    - pip install --no-cache twine
  script:
    # Build the package
    - python setup.py sdist bdist_wheel
    # Check the description
    - twine check dist/*
    # Upload to PyPI
    - twine upload --username "__token__" --password "$PYPI_TOKEN" dist/*
  # Only upload tags
  only:
    - tags
