[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 132
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | subprojects
)/
'''