# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_publishing', '0004_auto_20190517_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionpermissions',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Authenticated'), (2, 'Workgroup')], default=2),
        ),
    ]
