# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 03:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0002_administrationmode_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='estimated_seconds_response_time',
            field=models.PositiveIntegerField(blank=True, help_text='The estimated amount of time required to answer a question expressed in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The text which describes the information which is to be obtained.'),
        ),
    ]
