# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallard_qr', '0006_auto_20190503_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsedomain',
            old_name='maximum_occurances',
            new_name='maximum_occurrences',
        ),
        migrations.RenameField(
            model_name='responsedomain',
            old_name='minimum_occurances',
            new_name='minimum_occurrences',
        ),
    ]
