[tool.poetry]
name = "intflags"
version = "2.0.0"
description = "The simplest way to create bit-flags"
authors = ["SeparateRecords <me@rob.ac>"]
license = "ISC"
include = ["LICENSE"]
repository = "https://github.com/SeparateRecords/intflags"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
]
keywords = ["flags", "bitflags"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
