language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
install:
  - travis_retry pip install -r requirements-test.txt
script:
  - py.test --flake8
after_success:
  - "if [ $TRAVIS_PYTHON_VERSION == '3.6' ]; then pip install coveralls; coveralls; fi"
