sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.6"
    env: TOX_ENV=lint
  - python: "3.6"
    env: TOX_ENV=cov-travis DEPLOY=1
script: tox -e $TOX_ENV

deploy:
  # Adding a new tag automatically releases to PyPI.
  provider: pypi
  user: __token__
  password:
    # to be done
  on:
    tags: true
    condition: $DEPLOY = 1
  skip_existing: true
