[tool.poetry]
name = "lgblkb-tools"
version = "1.1.0"
description = "Tools to make life easier"
authors = ["lgblkb <dbakhtiyarov@nu.edu.kz>"]

[tool.poetry.dependencies]
python = "^3.6.9"
pandas = "^1.0.1"
numpy = "^1.18.1"
matplotlib = "^3.1.3"
more-itertools = "^8.2.0"
requests = "^2.23.0"
python-box = "^4.2.0"
geojson = "^2.5.0"
shapely = "^1.7.0"
python-log-indenter = "^0.9"
wrapt = "^1.12.0"
checksumdir = "^1.1.7"
colorlog = "^4.1.0"
python-telegram-bot = "^12.4.2"
pyproj = "^2.5.0"
geopandas = {version = "^0.7.0", optional = true}
opencv-python = {version = "^4.2.0", optional = true}
scipy = {version = "^1.4.1", optional = true}
geoalchemy = {version = "^0.7.2", optional = true}
sqlalchemy = {version = "^1.3.13", optional = true}
gdal = {version = "<=2.4.3", optional = true}

[tool.poetry.extras]
gdal=["gdal<=2.4.3"]

vectorize=["gdal<=2.4.3","geopandas=^0.7.0","opencv-python=^4.2.0","scipy=^1.4.1",]

db=["geoalchemy2=^0.6.3","sqlalchemy=^1.3.13"]

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"

[tool.poetry.scripts]
export_reqs="lgblkb_tools.dev_script:export_reqs"
bump="lgblkb_tools.dev_script:export_reqs"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
