# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: px.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='px.proto',
  package='px',
  syntax='proto3',
  serialized_options=b'\n\022com.katalon.kit.pxB\014BrowserProtoP\001',
  serialized_pb=b'\n\x08px.proto\x12\x02px\"\x1c\n\nDoResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"(\n\tDoRequest\x12\x1b\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\n.px.Action\"\x96\x02\n\x06\x41\x63tion\x12(\n\x0claunchAction\x18\x01 \x01(\x0b\x32\x10.px.LaunchActionH\x00\x12$\n\ngotoAction\x18\x02 \x01(\x0b\x32\x0e.px.GotoActionH\x00\x12&\n\x0b\x63lickAction\x18\x03 \x01(\x0b\x32\x0f.px.ClickActionH\x00\x12$\n\ntypeAction\x18\x04 \x01(\x0b\x32\x0e.px.TypeActionH\x00\x12(\n\x0cselectAction\x18\x05 \x01(\x0b\x32\x10.px.SelectActionH\x00\x12\x34\n\x12getInnerTextAction\x18\x06 \x01(\x0b\x32\x16.px.GetInnerTextActionH\x00\x42\x0e\n\x0c\x61\x63tion_oneof\" \n\x0cLaunchAction\x12\x10\n\x08headless\x18\x01 \x01(\x08\"\x19\n\nGotoAction\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1f\n\x0b\x43lickAction\x12\x10\n\x08selector\x18\x01 \x01(\t\",\n\nTypeAction\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"0\n\x0cSelectAction\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"&\n\x12GetInnerTextAction\x12\x10\n\x08selector\x18\x01 \x01(\t20\n\x07\x42rowser\x12%\n\x02\x44o\x12\r.px.DoRequest\x1a\x0e.px.DoResponse\"\x00\x42$\n\x12\x63om.katalon.kit.pxB\x0c\x42rowserProtoP\x01\x62\x06proto3'
)




_DORESPONSE = _descriptor.Descriptor(
  name='DoResponse',
  full_name='px.DoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='px.DoResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=44,
)


_DOREQUEST = _descriptor.Descriptor(
  name='DoRequest',
  full_name='px.DoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='px.DoRequest.actions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=86,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='px.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='launchAction', full_name='px.Action.launchAction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gotoAction', full_name='px.Action.gotoAction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clickAction', full_name='px.Action.clickAction', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeAction', full_name='px.Action.typeAction', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selectAction', full_name='px.Action.selectAction', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='getInnerTextAction', full_name='px.Action.getInnerTextAction', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='action_oneof', full_name='px.Action.action_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=89,
  serialized_end=367,
)


_LAUNCHACTION = _descriptor.Descriptor(
  name='LaunchAction',
  full_name='px.LaunchAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headless', full_name='px.LaunchAction.headless', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=401,
)


_GOTOACTION = _descriptor.Descriptor(
  name='GotoAction',
  full_name='px.GotoAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='px.GotoAction.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=428,
)


_CLICKACTION = _descriptor.Descriptor(
  name='ClickAction',
  full_name='px.ClickAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='px.ClickAction.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=461,
)


_TYPEACTION = _descriptor.Descriptor(
  name='TypeAction',
  full_name='px.TypeAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='px.TypeAction.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='px.TypeAction.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=507,
)


_SELECTACTION = _descriptor.Descriptor(
  name='SelectAction',
  full_name='px.SelectAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='px.SelectAction.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='px.SelectAction.values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=557,
)


_GETINNERTEXTACTION = _descriptor.Descriptor(
  name='GetInnerTextAction',
  full_name='px.GetInnerTextAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='px.GetInnerTextAction.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=597,
)

_DOREQUEST.fields_by_name['actions'].message_type = _ACTION
_ACTION.fields_by_name['launchAction'].message_type = _LAUNCHACTION
_ACTION.fields_by_name['gotoAction'].message_type = _GOTOACTION
_ACTION.fields_by_name['clickAction'].message_type = _CLICKACTION
_ACTION.fields_by_name['typeAction'].message_type = _TYPEACTION
_ACTION.fields_by_name['selectAction'].message_type = _SELECTACTION
_ACTION.fields_by_name['getInnerTextAction'].message_type = _GETINNERTEXTACTION
_ACTION.oneofs_by_name['action_oneof'].fields.append(
  _ACTION.fields_by_name['launchAction'])
_ACTION.fields_by_name['launchAction'].containing_oneof = _ACTION.oneofs_by_name['action_oneof']
_ACTION.oneofs_by_name['action_oneof'].fields.append(
  _ACTION.fields_by_name['gotoAction'])
_ACTION.fields_by_name['gotoAction'].containing_oneof = _ACTION.oneofs_by_name['action_oneof']
_ACTION.oneofs_by_name['action_oneof'].fields.append(
  _ACTION.fields_by_name['clickAction'])
_ACTION.fields_by_name['clickAction'].containing_oneof = _ACTION.oneofs_by_name['action_oneof']
_ACTION.oneofs_by_name['action_oneof'].fields.append(
  _ACTION.fields_by_name['typeAction'])
_ACTION.fields_by_name['typeAction'].containing_oneof = _ACTION.oneofs_by_name['action_oneof']
_ACTION.oneofs_by_name['action_oneof'].fields.append(
  _ACTION.fields_by_name['selectAction'])
_ACTION.fields_by_name['selectAction'].containing_oneof = _ACTION.oneofs_by_name['action_oneof']
_ACTION.oneofs_by_name['action_oneof'].fields.append(
  _ACTION.fields_by_name['getInnerTextAction'])
_ACTION.fields_by_name['getInnerTextAction'].containing_oneof = _ACTION.oneofs_by_name['action_oneof']
DESCRIPTOR.message_types_by_name['DoResponse'] = _DORESPONSE
DESCRIPTOR.message_types_by_name['DoRequest'] = _DOREQUEST
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['LaunchAction'] = _LAUNCHACTION
DESCRIPTOR.message_types_by_name['GotoAction'] = _GOTOACTION
DESCRIPTOR.message_types_by_name['ClickAction'] = _CLICKACTION
DESCRIPTOR.message_types_by_name['TypeAction'] = _TYPEACTION
DESCRIPTOR.message_types_by_name['SelectAction'] = _SELECTACTION
DESCRIPTOR.message_types_by_name['GetInnerTextAction'] = _GETINNERTEXTACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoResponse = _reflection.GeneratedProtocolMessageType('DoResponse', (_message.Message,), {
  'DESCRIPTOR' : _DORESPONSE,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.DoResponse)
  })
_sym_db.RegisterMessage(DoResponse)

DoRequest = _reflection.GeneratedProtocolMessageType('DoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOREQUEST,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.DoRequest)
  })
_sym_db.RegisterMessage(DoRequest)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.Action)
  })
_sym_db.RegisterMessage(Action)

LaunchAction = _reflection.GeneratedProtocolMessageType('LaunchAction', (_message.Message,), {
  'DESCRIPTOR' : _LAUNCHACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.LaunchAction)
  })
_sym_db.RegisterMessage(LaunchAction)

GotoAction = _reflection.GeneratedProtocolMessageType('GotoAction', (_message.Message,), {
  'DESCRIPTOR' : _GOTOACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.GotoAction)
  })
_sym_db.RegisterMessage(GotoAction)

ClickAction = _reflection.GeneratedProtocolMessageType('ClickAction', (_message.Message,), {
  'DESCRIPTOR' : _CLICKACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.ClickAction)
  })
_sym_db.RegisterMessage(ClickAction)

TypeAction = _reflection.GeneratedProtocolMessageType('TypeAction', (_message.Message,), {
  'DESCRIPTOR' : _TYPEACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.TypeAction)
  })
_sym_db.RegisterMessage(TypeAction)

SelectAction = _reflection.GeneratedProtocolMessageType('SelectAction', (_message.Message,), {
  'DESCRIPTOR' : _SELECTACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.SelectAction)
  })
_sym_db.RegisterMessage(SelectAction)

GetInnerTextAction = _reflection.GeneratedProtocolMessageType('GetInnerTextAction', (_message.Message,), {
  'DESCRIPTOR' : _GETINNERTEXTACTION,
  '__module__' : 'px_pb2'
  # @@protoc_insertion_point(class_scope:px.GetInnerTextAction)
  })
_sym_db.RegisterMessage(GetInnerTextAction)


DESCRIPTOR._options = None

_BROWSER = _descriptor.ServiceDescriptor(
  name='Browser',
  full_name='px.Browser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=599,
  serialized_end=647,
  methods=[
  _descriptor.MethodDescriptor(
    name='Do',
    full_name='px.Browser.Do',
    index=0,
    containing_service=None,
    input_type=_DOREQUEST,
    output_type=_DORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROWSER)

DESCRIPTOR.services_by_name['Browser'] = _BROWSER

# @@protoc_insertion_point(module_scope)
