DCYD_CONFIG_ENV_VAR = 'DCYD_CONFIG_FILE'
DCYD_APP_BASE_URL = 'https://api.dcyd.io'
DEFAULT_ENVIRONMENT = 'test'
MPM_PUBSUB_TOPIC = 'mpm-client-log'
REQUEST_LOG_MSG = 'mpm-request'
RESPONSE_LOG_MSG = 'mpm-response'
CONFIG_ROUTE = 'configure'
CONFIG_FILE = 'dcyd.json'
