'''
Created on Jan 9, 2020

@author: colin bitterfield

A list of common definitions
'''

# ------ Configurations Import as needed  ------

FFLOCATIONS = ['/opt/local/bin', '/usr/local/bin', '/usr/bin']

VIDEO_EXTENSIONS = ['avi', 'mp4', 'mov', 'mpeg', 'mpg', 'm2p', 'mkv', '3gp', 'ogg', 'flv', 'f4v', 'f4p', 'f4a', 'f4b']

# TAble Definitions
TABLE = dict()
TABLE['preview'] = ['filename', 'part_id', 'dirname', 'basename', 'md5', 'studio', 'video_width', 'video_height',
                    'video_bit_rate', 'video_duration', 'codec_long_name', 'video_aspect', 'video_frame_rate',
                    'video_frames', 'video_size', 'comments']

COLORS = list(['AliceBlue',
               'AntiqueWhite',
               'Aqua',
               'Aquamarine',
               'Azure',
               'Beige',
               'Bisque',
               'Black',
               'BlanchedAlmond',
               'Blue',
               'BlueViolet',
               'Brown',
               'BurlyWood',
               'CadetBlue',
               'Chartreuse',
               'Chocolate',
               'Coral',
               'CornflowerBlue',
               'Cornsilk',
               'Crimson',
               'Cyan',
               'DarkBlue',
               'DarkCyan',
               'DarkGoldenRod',
               'DarkGray',
               'DarkGreen',
               'DarkKhaki',
               'DarkMagenta',
               'DarkOliveGreen',
               'Darkorange',
               'DarkOrchid',
               'DarkRed',
               'DarkSalmon',
               'DarkSeaGreen',
               'DarkSlateBlue',
               'DarkSlateGray',
               'DarkTurquoise',
               'DarkViolet',
               'DeepPink',
               'DeepSkyBlue',
               'DimGray',
               'DodgerBlue',
               'FireBrick',
               'FloralWhite',
               'ForestGreen',
               'Fuchsia',
               'Gainsboro',
               'GhostWhite',
               'Gold',
               'GoldenRod',
               'Gray',
               'Green',
               'GreenYellow',
               'HoneyDew',
               'HotPink',
               'IndianRed',
               'Indigo',
               'Ivory',
               'Khaki',
               'Lavender',
               'LavenderBlush',
               'LawnGreen',
               'LemonChiffon',
               'LightBlue',
               'LightCoral',
               'LightCyan',
               'LightGoldenRodYellow',
               'LightGreen',
               'LightGrey',
               'LightPink',
               'LightSalmon',
               'LightSeaGreen',
               'LightSkyBlue',
               'LightSlateGray',
               'LightSteelBlue',
               'LightYellow',
               'Lime',
               'LimeGreen',
               'Linen',
               'Magenta',
               'Maroon',
               'MediumAquaMarine',
               'MediumBlue',
               'MediumOrchid',
               'MediumPurple',
               'MediumSeaGreen',
               'MediumSlateBlue',
               'MediumSpringGreen',
               'MediumTurquoise',
               'MediumVioletRed',
               'MidnightBlue',
               'MintCream',
               'MistyRose',
               'Moccasin',
               'NavajoWhite',
               'Navy',
               'OldLace',
               'Olive',
               'OliveDrab',
               'Orange',
               'OrangeRed',
               'Orchid',
               'PaleGoldenRod',
               'PaleGreen',
               'PaleTurquoise',
               'PaleVioletRed',
               'PapayaWhip',
               'PeachPuff',
               'Peru',
               'Pink',
               'Plum',
               'PowderBlue',
               'Purple',
               'Red',
               'RosyBrown',
               'RoyalBlue',
               'SaddleBrown',
               'Salmon',
               'SandyBrown',
               'SeaGreen',
               'SeaShell',
               'Sienna',
               'Silver',
               'SkyBlue',
               'SlateBlue',
               'SlateGray',
               'Snow',
               'SpringGreen',
               'SteelBlue',
               'Tan',
               'Teal',
               'Thistle',
               'Tomato',
               'Turquoise',
               'Violet',
               'Wheat',
               'White',
               'WhiteSmoke',
               'Yellow',
               'YellowGreen'])
