[tool.poetry]
name = "pyrs990"
version = "0.1.0"
description = "A tool for fetching and filtering IRS 990 data."
authors = ["George Lesica <george@lesica.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
defusedxml = "^0.6.0"

[tool.poetry.dev-dependencies]
ipython = "^7.13.0"
black = "^19.10b0"
pytest = "^5.3.5"
mypy = "^0.761"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

