# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulpcore
from pulpcore.client.pulpcore.models.version import Version  # noqa: E501
from pulpcore.client.pulpcore.rest import ApiException


class TestVersion(unittest.TestCase):
    """Version unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersion(self):
        """Test Version"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulpcore.models.version.Version()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
