language: python

python: 3.6

branches:
  only:
  - master

  except:
  - project-template

matrix:
  include:
    - name: "Project structure validation"
      env: BALLET_CHECK_PROJECT_STRUCTURE=true
    - name: "Feature API validation"
      env: BALLET_CHECK_FEATURE_API=true
    - name: "Feature acceptance evaluation"
      env: BALLET_EVALUATE_FEATURE_ACCEPTANCE=true
    - name: "Feature pruning evaluation"
      env: BALLET_EVALUATE_FEATURE_PRUNING=true

install:
  - make install

script:
  - printenv | grep TRAVIS | sort
  - ballet validate
