
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-22T01:08:59-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d93ed880699e73eccb4608c0e2b8b42bfcb59d4",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
