# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0009_auto_20190320_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsettype',
            name='stewardship_organisation',
        ),
        migrations.RemoveField(
            model_name='indicatortype',
            name='stewardship_organisation',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='indicator_type',
        ),
        migrations.RemoveField(
            model_name='indicatorset',
            name='indicator_set_type',
        ),
        migrations.DeleteModel(
            name='IndicatorSetType',
        ),
        migrations.DeleteModel(
            name='IndicatorType',
        ),
    ]
