# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 02:41
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0016_auto_20190801_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='quality_statement',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, help_text='A statement of multiple quality dimensions for the purpose of assessing the quality of the data for reporting against this Indicator.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comet.QualityStatement'),
        ),
        migrations.AlterField(
            model_name='indicatordenominatordefinition',
            name='data_element',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataElement'),
        ),
        migrations.AlterField(
            model_name='indicatordenominatordefinition',
            name='data_set',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.Dataset'),
        ),
        migrations.AlterField(
            model_name='indicatordenominatordefinition',
            name='data_set_specification',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.DataSetSpecification'),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregationdefinition',
            name='data_element',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataElement'),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregationdefinition',
            name='data_set',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.Dataset'),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregationdefinition',
            name='data_set_specification',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.DataSetSpecification'),
        ),
        migrations.AlterField(
            model_name='indicatorinclusion',
            name='indicator',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comet.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicatornumeratordefinition',
            name='data_element',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.DataElement'),
        ),
        migrations.AlterField(
            model_name='indicatornumeratordefinition',
            name='data_set',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.Dataset'),
        ),
        migrations.AlterField(
            model_name='indicatornumeratordefinition',
            name='data_set_specification',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_dse.DataSetSpecification'),
        ),
    ]
