# Generated by Django 2.2.7 on 2019-11-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0017_auto_20190809_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkdimension',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
