# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 23:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0045__concept_superseded_by_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationScheme',
            fields=[
                ('_concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aristotle_mdr._concept')),
                ('classificationStructure', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('aristotle_mdr._concept',),
        ),
    ]
