# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0004_customfield_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='choices',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
