# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0005_auto_20190519_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvalue',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
