language: python
python: 
  - "3.6"

before_install:
# Work around https://github.com/travis-ci/travis-ci/issues/7940
- export BOTO_CONFIG=/dev/null  

install:
- sudo apt-get update
- pip install -r requirements.txt
- pip install .

script:
- python setup.py test
