# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fleetspeak/src/server/components/proto/fleetspeak_components/config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fleetspeak/src/server/components/proto/fleetspeak_components/config.proto',
  package='fleetspeak.components',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nIfleetspeak/src/server/components/proto/fleetspeak_components/config.proto\x12\x15\x66leetspeak.components\"\x96\x02\n\x06\x43onfig\x12\x1e\n\x16mysql_data_source_name\x18\x01 \x01(\t\x12\x38\n\x0chttps_config\x18\x02 \x01(\x0b\x32\".fleetspeak.components.HttpsConfig\x12\x38\n\x0c\x61\x64min_config\x18\x07 \x01(\x0b\x32\".fleetspeak.components.AdminConfig\x12\x16\n\x0eproxy_protocol\x18\x03 \x01(\x08\x12\x16\n\x0erequired_label\x18\x04 \x01(\t\x12#\n\x1bnotification_listen_address\x18\x05 \x01(\t\x12#\n\x1bnotification_public_address\x18\x06 \x01(\t\"c\n\x0bHttpsConfig\x12\x16\n\x0elisten_address\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x65rtificates\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x19\n\x11\x64isable_streaming\x18\x04 \x01(\x08\"%\n\x0b\x41\x64minConfig\x12\x16\n\x0elisten_address\x18\x01 \x01(\tb\x06proto3'
)




_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='fleetspeak.components.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mysql_data_source_name', full_name='fleetspeak.components.Config.mysql_data_source_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='https_config', full_name='fleetspeak.components.Config.https_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin_config', full_name='fleetspeak.components.Config.admin_config', index=2,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proxy_protocol', full_name='fleetspeak.components.Config.proxy_protocol', index=3,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='required_label', full_name='fleetspeak.components.Config.required_label', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notification_listen_address', full_name='fleetspeak.components.Config.notification_listen_address', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notification_public_address', full_name='fleetspeak.components.Config.notification_public_address', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=379,
)


_HTTPSCONFIG = _descriptor.Descriptor(
  name='HttpsConfig',
  full_name='fleetspeak.components.HttpsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='listen_address', full_name='fleetspeak.components.HttpsConfig.listen_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='certificates', full_name='fleetspeak.components.HttpsConfig.certificates', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='fleetspeak.components.HttpsConfig.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disable_streaming', full_name='fleetspeak.components.HttpsConfig.disable_streaming', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=480,
)


_ADMINCONFIG = _descriptor.Descriptor(
  name='AdminConfig',
  full_name='fleetspeak.components.AdminConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='listen_address', full_name='fleetspeak.components.AdminConfig.listen_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=519,
)

_CONFIG.fields_by_name['https_config'].message_type = _HTTPSCONFIG
_CONFIG.fields_by_name['admin_config'].message_type = _ADMINCONFIG
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['HttpsConfig'] = _HTTPSCONFIG
DESCRIPTOR.message_types_by_name['AdminConfig'] = _ADMINCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'fleetspeak.src.server.components.proto.fleetspeak_components.config_pb2'
  # @@protoc_insertion_point(class_scope:fleetspeak.components.Config)
  })
_sym_db.RegisterMessage(Config)

HttpsConfig = _reflection.GeneratedProtocolMessageType('HttpsConfig', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSCONFIG,
  '__module__' : 'fleetspeak.src.server.components.proto.fleetspeak_components.config_pb2'
  # @@protoc_insertion_point(class_scope:fleetspeak.components.HttpsConfig)
  })
_sym_db.RegisterMessage(HttpsConfig)

AdminConfig = _reflection.GeneratedProtocolMessageType('AdminConfig', (_message.Message,), {
  'DESCRIPTOR' : _ADMINCONFIG,
  '__module__' : 'fleetspeak.src.server.components.proto.fleetspeak_components.config_pb2'
  # @@protoc_insertion_point(class_scope:fleetspeak.components.AdminConfig)
  })
_sym_db.RegisterMessage(AdminConfig)


# @@protoc_insertion_point(module_scope)
