
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "43957deb551a187b6da2fd2f2a48ed7825f281ff",
 "version": "2264"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
