"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.0.0-beta.95"
COMMIT = "149c2ef07a02ced1eb234bf93117c2e87ddb6669"
MAJOR = 1
MINOR = 0
PATCH = 0
