
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-28T14:35:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "241bc51a0526064e78a6121b50ef81e080a583ee",
 "version": "1.1.1.post.dev45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
