
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-27T01:02:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa123486af0f0336fdd364a318552133c7e6b9ee",
 "version": "0.0.4a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
