
environment:
  matrix:
    - PYTHON_VERSION: "3.7"
      MINICONDA: "C:\\Miniconda36-x64"

install:
    - "%MINICONDA%\\Scripts\\activate.bat"
    - conda config --set always_yes True
    - conda config --add channels gsecars
    - conda update conda
    - conda info -a
    - conda install python=3.7 numpy scipy matplotlib sqlalchemy requests pandas scikit-image scikit-learn h5py wxpython yaml pyyaml pip
    - pip install dill nose peakutils pillow psutil psycopg2 pyepics pytest silx sphinx termcolor
    - pip install asteval lmfit pycifrw pyfai pyshortcuts uncertainties wxutils wxmplot xraydb
### - conda install dioptas tomopy


build_script:
    - python.exe setup.py install

test_script:
    - cd tests
    - python -m pytest
