[tool.poetry]
name = "cfntool"
version = "0.2.1"
description = ""
authors = ["ccdale <chris.allison@hivehome.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ccalogging = "^0.3.3"
boto3 = "^1.12.15"
getopt2 = "^0.0.3"
chaim = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
cfn = "cfntool.installtemplate:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
