import setuptools


with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="DoxyUML",
    version="0.0.2",
    author="Xavier Coponet",
    author_email="xavier.coponet@gmail.com",
    url="https://gitlab.com/xcoponet/doxyuml",
    description="Generate UML diagrams from XML documentation generated by Doxygen",
    long_description=long_description,
    long_description_content_type="text/markdown",
    license='MIT',
    packages=setuptools.find_packages(),
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        ],
    install_requires=['pytermcolor==0.1.0', "graphviz", "numpy"],

    # entry_points ={
    #     'console_scripts': ['PyCppBuild=PyCppBuild:main']
    #   },
)
