
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T15:14:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2e4b3410f808e6d78bd1a54dd43f6f4f441bd5c",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
