
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-27T12:32:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6ab56ea858cab13c3dc462917f5a10836f6b32e",
 "version": "0.2.0.post.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
