
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9b23489f3af0923584a461542841c07a29b37e57",
 "version": "2256"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
