# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_glossary', '0001_squashed_0003_fix_concept_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glossaryadditionaldefinition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='glossaryadditionaldefinition',
            name='glossaryItem',
        ),
        migrations.RemoveField(
            model_name='glossaryadditionaldefinition',
            name='registrationAuthority',
        ),
        migrations.DeleteModel(
            name='GlossaryAdditionalDefinition',
        ),
    ]
