# Azure DevOps continuous integration build configuration
#

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install --upgrade setuptools
  displayName: 'Install/Upgrade setuptools and pip'

- script: pip install tox
  displayName: 'Install tox'

- script: tox -e py
  displayName: 'Run tox'
