# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_activitypub', '0002_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.URLField(unique=True),
        ),
    ]
