# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_activitypub', '0004_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='ap_id',
        ),
        migrations.AddField(
            model_name='note',
            name='aid',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='aid',
            field=models.URLField(null=True),
        ),
    ]
