# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_activitypub', '0005_auto_20190827_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
