
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-24T15:32:21-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "90191f115e0ad57394598551fd2fd2ee8f70ed43",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
