name: justcause
channels:
  - r
  - pkgs/main
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.7
  - numpy
  - scipy
  - pandas
  - r-base
  - rpy2
  - seaborn
  - tensorflow=1.13.1 # required for dragonnet project code
  - keras
  - cython # needed by CausalML
  - arrow-cpp # check if needed
  - pyarrow>=0.15  # Mac problems with 0.13
  - scikit-learn==0.20.3  # Currently required to downgrade scikit-learn in order for CausalML to compile
  - matplotlib==2.2.4  # Required for CausalML to work instantly
  - seaborn
  # for development below here
  - jupyterlab
  - pytest
  - pytest-cov
  - pytest-virtualenv
  - coverage
  - coveralls
  - flake8
  - pip:
      - pre-commit
      - causalml
      - pygam
