
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "802c9d4a29a40de7e379bc2bc0e63a19d6bd9641",
 "version": "0.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
