# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 03:08
from __future__ import unicode_literals

from django.db import migrations

def move_to_new(apps, schema_migration):
    ra = apps.get_model('aristotle_mdr', 'RegistrationAuthority')

    for obj in ra.objects.all():
        if obj.active:
            obj.new_active = 0
        else:
            obj.new_active = 1

        obj.save()

def move_to_old(apps, schema_migration):
    ra = apps.get_model('aristotle_mdr', 'RegistrationAuthority')

    for obj in ra.objects.all():
        if obj.new_active == 0:
            obj.active = True
        else:
            obj.active = False

        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0032_add_new_active'),
    ]

    operations = [
        migrations.RunPython(move_to_new, move_to_old),
    ]
