# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0034_remove_old_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationauthority',
            name='active',
            field=models.IntegerField(choices=[(0, 'Active & Visible'), (1, 'Inactive & Visible'), (2, 'Inactive & Hidden')], default=0, help_text='Setting this to Inactive will disable all further registration actions'),
        ),
    ]
