# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 04:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0035_auto_20180817_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='_concept',
            name='origin',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The source (e.g. document, project, discipline or model) for the item (8.1.2.2.3.5)'),
        ),
    ]
