# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-22 01:51
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0036_add_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_concept',
            name='name',
            field=aristotle_mdr.fields.ShortTextField(help_text='The primary name used for human identification purposes.'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=aristotle_mdr.fields.ShortTextField(help_text='The primary name used for human identification purposes.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=aristotle_mdr.fields.ShortTextField(help_text='The primary name used for human identification purposes.'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=aristotle_mdr.fields.ShortTextField(help_text='The primary name used for human identification purposes.'),
        ),
    ]
