# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-29 00:26
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0038_sandboxshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_concept',
            name='responsible_organisation',
            field=aristotle_mdr.fields.ShortTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='_concept',
            name='submitting_organisation',
            field=aristotle_mdr.fields.ShortTextField(blank=True),
        ),
    ]
