# -*- coding: utf-8 -*-
# Generated by Harry
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0039_auto_20180828_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possumprofile',
            old_name='favourites',
            new_name='old_favourites',
        ),
    ]
