# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 05:39
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0044_remove__concept_superseded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='_concept',
            name='superseded_by_items',
            field=aristotle_mdr.fields.ConceptManyToManyField(related_name='superseded_items', through='aristotle_mdr.SupersedeRelationship', to='aristotle_mdr._concept'),
        ),
    ]
