# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 04:17
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_review_requests', '0004_auto_20181205_1925'),
        ('aristotle_mdr', '0051_auto_20190216_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrequest',
            name='concepts',
        ),
        migrations.RemoveField(
            model_name='reviewrequest',
            name='registration_authority',
        ),
        migrations.RemoveField(
            model_name='reviewrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='reviewrequest',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='supersederelationship',
            name='proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supersederelationship',
            name='review',
            field=aristotle_mdr.fields.ConceptForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supersedes', to='aristotle_mdr_review_requests.ReviewRequest'),
        ),
        migrations.DeleteModel(
            name='ReviewRequest',
        ),
    ]
