# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0061_auto_20190503_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stewardorganisation',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('private', 'Private'), ('archived', 'Deactivated & Visible'), ('hidden', 'Deactivated & Hidden')], default='active', help_text='Status of this group', max_length=128),
        ),
    ]
