# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 00:42
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aristotle_mdr', '0062_auto_20190517_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='_concept',
            name='_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
