# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0071_auto_20190809_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possumprofile',
            name='savedActiveWorkgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aristotle_mdr.Workgroup'),
        ),
    ]
