# Generated by Django 2.2.4 on 2019-09-08 06:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0073_auto_20190814_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualdomain',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description or specification of a rule, reference, or range for a set of all value meanings for a Conceptual Domain', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valuedomain',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description or specification of a rule, reference, or range for a set of all values for a Value Domain.', verbose_name='Description'),
        ),
    ]
