
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-27T09:55:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e958cc5d34e73863bfc026705391f2064a68fc1",
 "version": "v0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
