# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_help', '0004_auto_20170530_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concepthelp',
            old_name='offical_definition',
            new_name='official_definition',
        ),
    ]
