
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-28T10:24:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "372308de50614301a099234cc8f8403fc83e2f22",
 "version": "0.7.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
