# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: python 3.6
cache: pip

# First run the test. Then run all demos one-by-one.
script:
  - ./test/dongbei_test.py && ls demo/*.dongbei | xargs -L 1 ./src/dongbei.py --xudao

deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDg3NGQ1NDM4LWMwNDUtNDQ4MC05ZDE0LTRkYmNjMTA0OWZjMgACPXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkb25nYmVpLWxhbmciXX0sICJ2ZXJzaW9uIjogMX0AAAYg2Pylk-luUO4OvrXUWmEVoH7R75PRz7R7ek9pHdQSzqA"
  on:
    tags: true
