#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""postgres specific json field in taxonomy term jsonb data"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'db0a219b887b'
down_revision = '2f7c25afd313'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column('taxonomy_term', 'extra_data',
                    type_=sa.JSON().with_variant(sa.dialects.postgresql.JSONB, 'postgresql'))


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
