# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulpcore
from pulpcore.client.pulpcore.models.redis_connection import RedisConnection  # noqa: E501
from pulpcore.client.pulpcore.rest import ApiException


class TestRedisConnection(unittest.TestCase):
    """RedisConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedisConnection(self):
        """Test RedisConnection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulpcore.models.redis_connection.RedisConnection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
