[tool.poetry]
name = "mxu"
version = "0.0.3"
description = "A collection of utilities and helpers for writing Python programs."
authors = [
    "Maximilian Köhl <mkoehl@cs.uni-saarland.de>"
]
readme = "README.rst"
homepage = "https://github.com/koehlma/mx-python-utils"
repository = "https://github.com/koehlma/mx-python-utils"
classifiers = [
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = { version = "^19.10b0", allow-prereleases = true }
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.2"
pep8-naming = "^0.9.1"
mypy = "^0.761"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
