SHARED_AST = 'shared_ast'
SHARED_AST_DATA = 'data'
SHARED_AST_TABLE = "TBL"
SHARED_AST_Column = "COL"
SHARED_AST_VALUE = "VALUE"
SHARED_AST_STAR = "Star"
SHARED_AST_RB_COMPLEXITY = "rule_based_hardness"

AST_TABLE = "TABLE"
AST_COLUMN = "COLUMN"
AST_VALUE = "VALUE"
AST_STAR = "STAR"