export declare const compilerOptions: {
    "noImplicitAny": boolean;
    "noImplicitThis": boolean;
    "noImplicitReturns": boolean;
    "noUnusedLocals": boolean;
    "noUnusedParameters": boolean;
    "strictNullChecks": boolean;
    "strictBindCallApply": boolean;
    "strictFunctionTypes": boolean;
    "strictPropertyInitialization": boolean;
    "alwaysStrict": boolean;
    "noErrorTruncation": boolean;
    "noEmitOnError": boolean;
    "allowJs": boolean;
    "declaration": boolean;
    "sourceMap": boolean;
    "importHelpers": boolean;
    "experimentalDecorators": boolean;
    "module": string;
    "moduleResolution": string;
    "resolveJsonModule": boolean;
    "esModuleInterop": boolean;
    "target": string;
    "lib": string[];
    "baseUrl": string;
    "outDir": string;
};
export declare const include: string[];
