
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-21T14:28:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e31d524bd7bd4712a7d871730f0f89563b0bad5",
 "version": "0.6.71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
