
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-24T20:28:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d453645dea78286008deccd535652063daead4a",
 "version": "0.1.16.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
