---
  EC2Servers.list_servers:
    -
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        ec2_servers:
          flavor:
            name: "m1.tiny"
          image:
            name: "^cirros.*-disk$"
          servers_per_tenant: 2
      sla:
        failure_rate:
          max: 0
