[tool.poetry]
name = "interval_decorator"
version = "0.1.3"
description = ""
authors = ["fx_kirin <fx.kirin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
