
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-01T16:00:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbb0b5925d76090f03306b2721656d57e6f22c74",
 "version": "0.6.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
