from setuptools import setup


setup(
    name='nlpfeatures',
    version='0.1.4',
    packages=['nlpfeatures'],
    author='chekrizh',
    author_email='chekrizh@gmail.com',
    url='https://github.com/chekrizh/nlpfeaturespip install twine',
    zip_safe=False,
    install_requires=[
        'absl-py==0.9.0',
        'astor==0.8.1',
        'Click==7.0',
        'cloudpickle==1.3.0',
        'dask==2.11.0',
        'distributed==2.11.0',
        'featuretools==0.13.2',
        'fsspec==0.6.2',
        'gast==0.2.2',
        'google-pasta==0.1.8',
        'grpcio==1.27.2',
        'h5py==2.10.0',
        'HeapDict==1.0.1',
        'joblib==0.14.1',
        'Keras-Applications==1.0.8',
        'Keras-Preprocessing==1.1.0',
        'locket==0.2.0',
        'Markdown==3.2.1',
        'msgpack==1.0.0',
        'nlp-primitives==0.2.4',
        'nltk==3.4.5',
        'numpy==1.18.1',
        'opt-einsum==3.1.0',
        'pandas==1.0.1',
        'partd==1.1.0',
        'protobuf==3.11.3',
        'psutil==5.7.0',
        'python-dateutil==2.8.0',
        'pytz==2019.3',
        'PyYAML==5.3',
        'scikit-learn==0.22.1',
        'scipy==1.4.1',
        'six==1.14.0',
        'sortedcontainers==2.1.0',
        'tblib==1.6.0',
        'tensorboard==1.15.0',
        'tensorflow==1.15.2',
        'tensorflow-estimator==1.15.1',
        'tensorflow-hub==0.7.0',
        'termcolor==1.1.0',
        'toolz==0.10.0',
        'tornado==6.0.3',
        'tqdm==4.43.0',
        'Werkzeug==1.0.0',
        'wrapt==1.12.0',
        'zict==1.0.0'
    ],
    description='add-on library nlp primitives',
    long_description='for reading documentation check repo in github https://github.com/chekrizh/nlpfeatures',
)
