language: python
python:
  - '2.7'
  - '3.4'
install:
  - 'pip install -q -U pip'
  - 'pip install django psycopg2 mysqlclient'
  - 'pip install -e .'
before_script:
  - mysql -e 'create database app_test'
  - psql -c 'create database app_test' -U postgres
  - cd test_django_project
  - python manage.py migrate --noinput
  - python manage.py migrate --noinput --database=postgres
  - python manage.py migrate --noinput --database=mysql
script: python manage.py icytests
