[tool.poetry]
name = "adasigpy"
version = "0.1.8"
description = "Adaptive Signal Processing Package in Python"
authors = ["borley1211 <km.isetan@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.17.4"
scipy = "^1.4.0"
nptyping = "^0.3.1"

[tool.poetry.dev-dependencies]
python-language-server = "^0.31.2"
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.760"
jupyterlab = "^1.2.4"
ipykernel = "^5.1.3"
pytest = "^5.3.2"
neovim = "^0.3.1"
isort = "^4.3.21"
ptpython = "^2.0.6"
twine = "^3.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
