# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_view_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recently_viewed_metadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
