# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 00:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_backwards', '0002_representationclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representationclass',
            name='definition',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Representation of a concept by a descriptive statement which serves to differentiate it from related concepts. (3.2.39)', null=True, verbose_name='definition'),
        ),
    ]
