# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xain_proto/fl/coordinator.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xain_proto.np import ndarray_pb2 as xain__proto_dot_np_dot_ndarray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xain_proto/fl/coordinator.proto',
  package='xain_proto.fl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1fxain_proto/fl/coordinator.proto\x12\rxain_proto.fl\x1a\x1bxain_proto/np/ndarray.proto\"\x13\n\x11RendezvousRequest\"C\n\x12RendezvousResponse\x12-\n\x05reply\x18\x01 \x01(\x0e\x32\x1e.xain_proto.fl.RendezvousReply\"F\n\x10HeartbeatRequest\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.xain_proto.fl.State\x12\r\n\x05round\x18\x02 \x01(\x05\"G\n\x11HeartbeatResponse\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.xain_proto.fl.State\x12\r\n\x05round\x18\x02 \x01(\x05\"\x1b\n\x19StartTrainingRoundRequest\"@\n\x1aStartTrainingRoundResponse\x12\x0e\n\x06\x65pochs\x18\x01 \x01(\x05\x12\x12\n\nepoch_base\x18\x02 \x01(\x05\"Z\n\x17\x45ndTrainingRoundRequest\x12\x16\n\x0eparticipant_id\x18\x01 \x01(\t\x12\x16\n\x0enumber_samples\x18\x02 \x01(\x05\x12\x0f\n\x07metrics\x18\x03 \x01(\t\"\x1a\n\x18\x45ndTrainingRoundResponse*(\n\x0fRendezvousReply\x12\n\n\x06\x41\x43\x43\x45PT\x10\x00\x12\t\n\x05LATER\x10\x01*F\n\x05State\x12\x0b\n\x07STANDBY\x10\x00\x12\t\n\x05ROUND\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\x12\t\n\x05READY\x10\x03\x12\x0c\n\x08TRAINING\x10\x04\x32\x88\x03\n\x0b\x43oordinator\x12S\n\nRendezvous\x12 .xain_proto.fl.RendezvousRequest\x1a!.xain_proto.fl.RendezvousResponse\"\x00\x12P\n\tHeartbeat\x12\x1f.xain_proto.fl.HeartbeatRequest\x1a .xain_proto.fl.HeartbeatResponse\"\x00\x12k\n\x12StartTrainingRound\x12(.xain_proto.fl.StartTrainingRoundRequest\x1a).xain_proto.fl.StartTrainingRoundResponse\"\x00\x12\x65\n\x10\x45ndTrainingRound\x12&.xain_proto.fl.EndTrainingRoundRequest\x1a\'.xain_proto.fl.EndTrainingRoundResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[xain__proto_dot_np_dot_ndarray__pb2.DESCRIPTOR,])

_RENDEZVOUSREPLY = _descriptor.EnumDescriptor(
  name='RendezvousReply',
  full_name='xain_proto.fl.RendezvousReply',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LATER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=529,
  serialized_end=569,
)
_sym_db.RegisterEnumDescriptor(_RENDEZVOUSREPLY)

RendezvousReply = enum_type_wrapper.EnumTypeWrapper(_RENDEZVOUSREPLY)
_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='xain_proto.fl.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAINING', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=571,
  serialized_end=641,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
ACCEPT = 0
LATER = 1
STANDBY = 0
ROUND = 1
FINISHED = 2
READY = 3
TRAINING = 4



_RENDEZVOUSREQUEST = _descriptor.Descriptor(
  name='RendezvousRequest',
  full_name='xain_proto.fl.RendezvousRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=98,
)


_RENDEZVOUSRESPONSE = _descriptor.Descriptor(
  name='RendezvousResponse',
  full_name='xain_proto.fl.RendezvousResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='xain_proto.fl.RendezvousResponse.reply', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=167,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='xain_proto.fl.HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='xain_proto.fl.HeartbeatRequest.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='xain_proto.fl.HeartbeatRequest.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=239,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='xain_proto.fl.HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='xain_proto.fl.HeartbeatResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='xain_proto.fl.HeartbeatResponse.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=312,
)


_STARTTRAININGROUNDREQUEST = _descriptor.Descriptor(
  name='StartTrainingRoundRequest',
  full_name='xain_proto.fl.StartTrainingRoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=341,
)


_STARTTRAININGROUNDRESPONSE = _descriptor.Descriptor(
  name='StartTrainingRoundResponse',
  full_name='xain_proto.fl.StartTrainingRoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epochs', full_name='xain_proto.fl.StartTrainingRoundResponse.epochs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_base', full_name='xain_proto.fl.StartTrainingRoundResponse.epoch_base', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=407,
)


_ENDTRAININGROUNDREQUEST = _descriptor.Descriptor(
  name='EndTrainingRoundRequest',
  full_name='xain_proto.fl.EndTrainingRoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='participant_id', full_name='xain_proto.fl.EndTrainingRoundRequest.participant_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_samples', full_name='xain_proto.fl.EndTrainingRoundRequest.number_samples', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='xain_proto.fl.EndTrainingRoundRequest.metrics', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=499,
)


_ENDTRAININGROUNDRESPONSE = _descriptor.Descriptor(
  name='EndTrainingRoundResponse',
  full_name='xain_proto.fl.EndTrainingRoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=527,
)

_RENDEZVOUSRESPONSE.fields_by_name['reply'].enum_type = _RENDEZVOUSREPLY
_HEARTBEATREQUEST.fields_by_name['state'].enum_type = _STATE
_HEARTBEATRESPONSE.fields_by_name['state'].enum_type = _STATE
DESCRIPTOR.message_types_by_name['RendezvousRequest'] = _RENDEZVOUSREQUEST
DESCRIPTOR.message_types_by_name['RendezvousResponse'] = _RENDEZVOUSRESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
DESCRIPTOR.message_types_by_name['StartTrainingRoundRequest'] = _STARTTRAININGROUNDREQUEST
DESCRIPTOR.message_types_by_name['StartTrainingRoundResponse'] = _STARTTRAININGROUNDRESPONSE
DESCRIPTOR.message_types_by_name['EndTrainingRoundRequest'] = _ENDTRAININGROUNDREQUEST
DESCRIPTOR.message_types_by_name['EndTrainingRoundResponse'] = _ENDTRAININGROUNDRESPONSE
DESCRIPTOR.enum_types_by_name['RendezvousReply'] = _RENDEZVOUSREPLY
DESCRIPTOR.enum_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RendezvousRequest = _reflection.GeneratedProtocolMessageType('RendezvousRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDEZVOUSREQUEST,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.RendezvousRequest)
  })
_sym_db.RegisterMessage(RendezvousRequest)

RendezvousResponse = _reflection.GeneratedProtocolMessageType('RendezvousResponse', (_message.Message,), {
  'DESCRIPTOR' : _RENDEZVOUSRESPONSE,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.RendezvousResponse)
  })
_sym_db.RegisterMessage(RendezvousResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.HeartbeatResponse)
  })
_sym_db.RegisterMessage(HeartbeatResponse)

StartTrainingRoundRequest = _reflection.GeneratedProtocolMessageType('StartTrainingRoundRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTTRAININGROUNDREQUEST,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.StartTrainingRoundRequest)
  })
_sym_db.RegisterMessage(StartTrainingRoundRequest)

StartTrainingRoundResponse = _reflection.GeneratedProtocolMessageType('StartTrainingRoundResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTTRAININGROUNDRESPONSE,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.StartTrainingRoundResponse)
  })
_sym_db.RegisterMessage(StartTrainingRoundResponse)

EndTrainingRoundRequest = _reflection.GeneratedProtocolMessageType('EndTrainingRoundRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDTRAININGROUNDREQUEST,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.EndTrainingRoundRequest)
  })
_sym_db.RegisterMessage(EndTrainingRoundRequest)

EndTrainingRoundResponse = _reflection.GeneratedProtocolMessageType('EndTrainingRoundResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDTRAININGROUNDRESPONSE,
  '__module__' : 'xain_proto.fl.coordinator_pb2'
  # @@protoc_insertion_point(class_scope:xain_proto.fl.EndTrainingRoundResponse)
  })
_sym_db.RegisterMessage(EndTrainingRoundResponse)



_COORDINATOR = _descriptor.ServiceDescriptor(
  name='Coordinator',
  full_name='xain_proto.fl.Coordinator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=644,
  serialized_end=1036,
  methods=[
  _descriptor.MethodDescriptor(
    name='Rendezvous',
    full_name='xain_proto.fl.Coordinator.Rendezvous',
    index=0,
    containing_service=None,
    input_type=_RENDEZVOUSREQUEST,
    output_type=_RENDEZVOUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='xain_proto.fl.Coordinator.Heartbeat',
    index=1,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_HEARTBEATRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartTrainingRound',
    full_name='xain_proto.fl.Coordinator.StartTrainingRound',
    index=2,
    containing_service=None,
    input_type=_STARTTRAININGROUNDREQUEST,
    output_type=_STARTTRAININGROUNDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EndTrainingRound',
    full_name='xain_proto.fl.Coordinator.EndTrainingRound',
    index=3,
    containing_service=None,
    input_type=_ENDTRAININGROUNDREQUEST,
    output_type=_ENDTRAININGROUNDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATOR)

DESCRIPTOR.services_by_name['Coordinator'] = _COORDINATOR

# @@protoc_insertion_point(module_scope)
