# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_file
from pulpcore.client.pulp_file.models.file_file_file_system_exporter import FileFileFileSystemExporter  # noqa: E501
from pulpcore.client.pulp_file.rest import ApiException


class TestFileFileFileSystemExporter(unittest.TestCase):
    """FileFileFileSystemExporter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileFileFileSystemExporter(self):
        """Test FileFileFileSystemExporter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulp_file.models.file_file_file_system_exporter.FileFileFileSystemExporter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
