
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-29T23:20:07+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ed93b4ebf033332a065eb247b0c44de4431cdf3",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
