# Generated by Django 2.2.4 on 2019-08-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0003_remove_commentassociation_object_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecomment',
            name='comment_markup_type',
            field=models.CharField(choices=[('', '--'), ('plain', 'plain'), ('markdown', 'markdown'), ('draftjs', 'draftjs')], default='plain', max_length=30),
        ),
    ]
