'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._754 import AddendumModificationDistributionRule
    from ._755 import BacklashSpecification
    from ._756 import BaffleLoss
    from ._757 import BasicRackProfiles
    from ._758 import CaseHardeningPropertiesForFEAnalysis
    from ._759 import CreateNewSuitableCutterOption
    from ._760 import CrossedAxisCylindricalGearPair
    from ._761 import CrossedAxisCylindricalGearPairLineContact
    from ._762 import CrossedAxisCylindricalGearPairPointContact
    from ._763 import CylindricalGearAbstractRack
    from ._764 import CylindricalGearBasicRack
    from ._765 import CylindricalGearCuttingOptions
    from ._766 import CylindricalGearDefaults
    from ._767 import CylindricalGearDesign
    from ._768 import CylindricalGearDesignConstraint
    from ._769 import CylindricalGearDesignConstraints
    from ._770 import CylindricalGearDesignConstraintsDatabase
    from ._771 import CylindricalGearDesignConstraintSettings
    from ._772 import CylindricalGearDesignSettings
    from ._773 import CylindricalGearMeshDesign
    from ._774 import CylindricalGearPinionTypeCutter
    from ._775 import CylindricalGearProfileMeasurement
    from ._776 import CylindricalGearProfileMeasurementType
    from ._777 import CylindricalGearProfileModifications
    from ._778 import CylindricalGearSetDesign
    from ._779 import CylindricalGearSetMacroGeometryOptimiser
    from ._780 import CylindricalGearSetManufacturingConfigurationSelection
    from ._781 import CylindricalGearTableMGItemDetail
    from ._782 import CylindricalGearTableWithMGCharts
    from ._783 import CylindricalGearToothThicknessSpecification
    from ._784 import CylindricalMeshAngularBacklash
    from ._785 import CylindricalMeshedGear
    from ._786 import CylindricalMeshLinearBacklashSpecification
    from ._787 import CylindricalPlanetaryGearSetDesign
    from ._788 import CylindricalPlanetGearDesign
    from ._789 import DIN3967AllowanceSeries
    from ._790 import DIN3967ToleranceSeries
    from ._791 import FinishStockSpecification
    from ._792 import FinishToothThicknessDesignSpecification
    from ._793 import GearFitSystems
    from ._794 import GearManufacturingConfigSetupViewModel
    from ._795 import GearSetFCAImportSetup
    from ._796 import GearSetManufacturingConfigurationSetup
    from ._797 import GeometrySpecificationType
    from ._798 import HardenedMaterialProperties
    from ._799 import ISO6336Geometry
    from ._800 import ISO6336GeometryBase
    from ._801 import ISO6336GeometryForShapedGears
    from ._802 import ISO6336GeometryManufactured
    from ._803 import LTCALoadCaseModifiableSettings
    from ._804 import LtcaSettings
    from ._805 import MicroGeometryConvention
    from ._806 import Micropitting
    from ._807 import NamedPlanetAssemblyIndex
    from ._808 import NamedPlanetSideBandAmplitudeFactor
    from ._809 import RelativeMeasurementViewModel
    from ._810 import RelativeValuesSpecification
    from ._811 import Scuffing
    from ._812 import ScuffingCoefficientOfFrictionMethods
    from ._813 import ScuffingTemperatureMethodsAGMA
    from ._814 import ScuffingTemperatureMethodsISO
    from ._815 import ShaperEdgeTypes
    from ._816 import SpurGearLoadSharingCodes
    from ._817 import StandardRack
    from ._818 import SurfaceRoughness
    from ._819 import ThicknessType
    from ._820 import TiffAnalysisSettings
    from ._821 import TipAlterationCoefficientMethod
    from ._822 import TolerancedMetalMeasurements
    from ._823 import TolerancedValueSpecification
    from ._824 import ToothThicknessSpecification
    from ._825 import ToothThicknessSpecificationBase
    from ._826 import TypeOfMechanismHousing
    from ._827 import Usage
