
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-21T12:04:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "495189028f153d61d29daeba01fe1c071cd62cb5",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
