[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "flashgeotext"
author = "Benjamin Ramser"
author-email = "ahoi@iwpnd.pw"
home-page = "https://github.com/iwpnd/flashgeotext"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
requires = [
    "flashtext==2.7",
    "loguru==0.4.1",
    "pydantic==1.4"
]
description-file = "readme.md"
requires-python = ">=3.6"

[tool.flit.metadata.urls]
Documentation = "https://flashgeotext.iwpnd.pw/"

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=4.0.0",
    "pytest-cov"
]
doc = [
    "awscli",
    "mkdocs",
    "mkdocs-material",
    "markdown-include",
    "pydoc-markdown"
]

dev = []
all = []
