openapi: "3.0.2"
info:
    title: "KRCG"
    version: "0.11"
    description: "**V:tES** cards and decks based on VEKN resources, including the [TWDA](http://www.vekn.fr/decks/twd.htm)."
    contact:
        name: "KRCG"
        url: https://github.com/lionel-panhaleux/krcg
    license:
        name: MIT License
        url: https://opensource.org/licenses/MIT
    host: krcg.herokuapp.com
    tags:
        -
            name: Deck
            description: TWDA decks
        -
            name: Card
            description: VTES cards
schemes: [http]
components:
    schemas:
        card_count:
            type: object
            properties:
                id: {type: string, required: true}
                name: {type: string, required: true}
                count: {type: integer, required: true}
                coments: {type: string}
            example: {count: 4, name: Anson}
        deck:
            type: object
            properties:
                twda_id: {type: string, required: true}
                name: {type: string}
                event: {type: string}
                place: {type: string}
                date: {type: string, format: date, required: true}
                player: {type: string, required: true}
                author: {type: string}
                players_count: {type: integer}
                tournament_format: {type: string}
                score: {type: string}
                comments: {type: string}
                crypt:
                    type: object
                    required: true
                    properties:
                        count: {type: integer, required: true}
                        cards:
                            type: array
                            required: true
                            minLength: 1
                            items: {$ref: "#/components/schemas/card_count"}
                library:
                    type: object
                    required: true
                    properties:
                        count: {type: integer, required: true}
                        cards:
                            type: array
                            required: true
                            minLength: 1
                            maxLength: 20
                            items:
                                type: object
                                properties:
                                    type: {type: string, required: true}
                                    count: {type: integer, required: true}
                                    cards:
                                        type: array
                                        required: true
                                        minLength: 1
                                        maxLength: 90
                                        items: {$ref: "#/components/schemas/card_count"}
            example:
                twd_id: "2014incbi"
                name: "AAA - Alert Attention Alarm"
                event: "Italian NC 2014"
                place: "Bologna, Italy"
                date: "2014-06-01"
                player: "Enrico De Stefano (Embraced)"
                author: null
                players_count: 25
                tournament_format: "3R+F"
                score: null
                comments: "-- Once again, our Enrico De Stefano defend his national title. Congratulations.\n"
                crypt:
                    count: 12
                    cards: [
                        {count: 4, name: Anson, id: "200107"},
                        {count: 2, name: Alexandra, id: "200049"},
                        {count: 2, name: Anneke, id: "200106"},
                        {count: 1, name: François Villon, id: "200478"},
                        {count: 1, name: Marcellus, id: "200910"},
                        {count: 1, name: Tatiana Romanov, id: "201347"},
                        {count: 1, name: "Volker, The Puppet Prince", id: "201458"}
                    ]
                library:
                    count: 90
                    cards:
                        -   type: Master
                            count: 30
                            cards: [
                                    {count: 9, name: Ashur Tablets, id: "100106"},
                                    {count: 7, name: Liquidation, id: "101112"},
                                    {count: 5, name: Villein, id: "102121"},
                                    {count: 3, name: Haven Uncovered, id: "100897"},
                                    {count: 1, name: Art Museum, id: "100095"},
                                    {count: 1, name: "Golconda: Inner Peace", id: "100842"},
                                    {count: 1, name: Information Highway, id: "100984"},
                                    {count: 1, name: Papillon, id: "101350"},
                                    {count: 1, name: "Pentex(TM) Subversion", id: "101384"},
                                    {count: 1, name: Wider View, id: "102180"}
                            ]
                        -   type: Action
                            count: 3
                            cards: [
                                {count: 2, name: Entrancement, id: "100652"},
                                {count: 1, name: Heart of the City, id: "100904"}
                            ]
                        -   type: Political Action
                            count: 4
                            cards: [
                                {count: 3, name: Parity Shift, id: "101353"},
                                {count: 1, name: Political Stranglehold, id: "101417"}
                            ]
                        -   type: Action Modifier
                            count: 2
                            cards: [{count: 2, name: Aire of Elation, id: "100031"}]
                        -   type: Action Modifier/Combat
                            count: 4
                            cards: [{count: 4, name: "Resist Earth's Grasp", id: "101610"}]
                        -   type: Combat
                            count: 21
                            cards: [
                                    {count: 4, name: Blur, id: "100227"},
                                    {count: 4, name: Concealed Weapon, id: "100392"},
                                    {count: 4, name: "Psyche!", id: "101507"},
                                    {count: 4, name: Taste of Vitae, id: "101945"},
                                    {count: 3, name: Charismatic Aura, id: "100333"},
                                    {count: 2, name: Side Strike, id: "101778"}
                            ]
                        -   type: Reaction
                            count: 13
                            cards: [
                                {count: 8, name: "Second Tradition: Domain", id: "101706"},
                                {count: 5, name: Telepathic Misdirection, id: "101949"}
                            ]
                        -   type: Equipment
                            count: 11
                            cards: [
                                    {count: 6, name: ".44 Magnum", id: "100001"},
                                    {count: 3, name: Heart of Nizchetus, id: "100903"},
                                    {count: 1, name: Bowl of Convergence, id: "100243"},
                                    {count: 1, name: Codex of the Edenic Groundskeepers, id: "100374"}
                            ]
                        -   type: Event
                            count: 2
                            cards: [
                                {count: 1, name: "Anthelios, The Red Star", id: "100074"},
                                {count: 1, name: Scourge of the Enochians, id: "101697"}
                            ]
paths:
    /deck:
        post:
            tags: [Deck]
            summary: Get TWDA decks matching given filters
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                card_names:
                                    description: "If absent, all decks are returned"
                                    type: array
                                    required: false
                                    minLength: 0
                                    items:
                                        description: "Case-insensitive card name"
                                        type: string
                                date_from:
                                    description: "Only consider decks from this date on"
                                    type: string
                                    format: date
                                    default: "2008-01-01"
                                date_to:
                                    description: "Only consider decks until this date"
                                    type: string
                                    format: date
                                    default: null
                                players:
                                    description: "Only consider tournaments with at least this number of players"
                                    type: integer
                                    minimum: 0
                                    default: 0
                            example:
                                cards: ["François Villon"]
                                date_from: "1994-01-01"
                                players: 25
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                required: true
                                minLength: 1
                                items: {$ref: "#/components/schemas/deck"}
                "404":
                    description: Not found
    /deck/{twda_id}:
        get:
            tags: [Deck]
            summary: Get a deck by its TWDA ID
            description: Returns the deck with the given ID
            parameters:
                - name: twda_id
                  in: path
                  description: "TWDA ID"
                  required: true
                  type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema: {$ref: "#/components/schemas/deck"}
                "404":
                    description: Not Found
    /complete/{partial_name}:
        get:
            tags: [Card]
            summary: Complete a card name
            description: Return all candidates matching the partial name
            parameters:
                - name: partial_name
                  in: path
                  description: "Partial card name"
                  required: true
                  type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    description: Card name
                            example: ["The unnamed", "Unnatural Disaster"]
                "404":
                    description: Not found
