# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-24 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('author', 'target_content_type', 'target_id')]),
        ),
    ]
