# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0602_pd_7974_flame_height.ui',
# licensing of '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0602_pd_7974_flame_height.ui' applies.
#
# Created: Mon Feb 24 00:46:11 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(715, 635, 96, 24))
        self.pushButton_calculate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(600, 635, 96, 24))
        self.pushButton_test.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_test.setObjectName("pushButton_test")
        self.label_image_context = QtWidgets.QLabel(self.centralwidget)
        self.label_image_context.setGeometry(QtCore.QRect(15, 15, 796, 681))
        self.label_image_context.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_image_context.setText("")
        self.label_image_context.setPixmap(QtGui.QPixmap("../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/png/0602_flame_height_794_560.png"))
        self.label_image_context.setObjectName("label_image_context")
        self.groupBox_inputs = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_inputs.setGeometry(QtCore.QRect(415, 210, 396, 216))
        self.groupBox_inputs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_inputs.setObjectName("groupBox_inputs")
        self.label_34 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_34.setGeometry(QtCore.QRect(315, 125, 51, 21))
        self.label_34.setMinimumSize(QtCore.QSize(0, 0))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_34.setObjectName("label_34")
        self.label_33 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_33.setGeometry(QtCore.QRect(315, 50, 51, 21))
        self.label_33.setMinimumSize(QtCore.QSize(0, 0))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_33.setObjectName("label_33")
        self.label_Q_dot_or_Q_dot_l_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_Q_dot_or_Q_dot_l_unit.setGeometry(QtCore.QRect(315, 25, 55, 21))
        self.label_Q_dot_or_Q_dot_l_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Q_dot_or_Q_dot_l_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Q_dot_or_Q_dot_l_unit.setObjectName("label_Q_dot_or_Q_dot_l_unit")
        self.lineEdit_Q_dot_or_Q_dot_l = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_Q_dot_or_Q_dot_l.setGeometry(QtCore.QRect(210, 25, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Q_dot_or_Q_dot_l.sizePolicy().hasHeightForWidth())
        self.lineEdit_Q_dot_or_Q_dot_l.setSizePolicy(sizePolicy)
        self.lineEdit_Q_dot_or_Q_dot_l.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Q_dot_or_Q_dot_l.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Q_dot_or_Q_dot_l.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_Q_dot_or_Q_dot_l.setObjectName("lineEdit_Q_dot_or_Q_dot_l")
        self.lineEdit_L_A_or_D = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_L_A_or_D.setGeometry(QtCore.QRect(210, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_L_A_or_D.sizePolicy().hasHeightForWidth())
        self.lineEdit_L_A_or_D.setSizePolicy(sizePolicy)
        self.lineEdit_L_A_or_D.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_L_A_or_D.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_L_A_or_D.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_L_A_or_D.setObjectName("lineEdit_L_A_or_D")
        self.lineEdit_c_p_0 = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_c_p_0.setGeometry(QtCore.QRect(210, 125, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_c_p_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_c_p_0.setSizePolicy(sizePolicy)
        self.lineEdit_c_p_0.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_c_p_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_c_p_0.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_c_p_0.setObjectName("lineEdit_c_p_0")
        self.label_23 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_23.setGeometry(QtCore.QRect(10, 125, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_23.setObjectName("label_23")
        self.label_L_A_or_D = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_L_A_or_D.setGeometry(QtCore.QRect(10, 50, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_L_A_or_D.sizePolicy().hasHeightForWidth())
        self.label_L_A_or_D.setSizePolicy(sizePolicy)
        self.label_L_A_or_D.setMinimumSize(QtCore.QSize(0, 0))
        self.label_L_A_or_D.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_L_A_or_D.setObjectName("label_L_A_or_D")
        self.label_Q_dot_or_Q_dot_l = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_Q_dot_or_Q_dot_l.setGeometry(QtCore.QRect(10, 25, 181, 21))
        self.label_Q_dot_or_Q_dot_l.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Q_dot_or_Q_dot_l.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Q_dot_or_Q_dot_l.setObjectName("label_Q_dot_or_Q_dot_l")
        self.label_35 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_35.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.label_35.setMinimumSize(QtCore.QSize(0, 0))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_35.setObjectName("label_35")
        self.lineEdit_rho_0 = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_rho_0.setGeometry(QtCore.QRect(210, 100, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rho_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_rho_0.setSizePolicy(sizePolicy)
        self.lineEdit_rho_0.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_rho_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_rho_0.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_rho_0.setObjectName("lineEdit_rho_0")
        self.label_37 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_37.setGeometry(QtCore.QRect(315, 100, 51, 21))
        self.label_37.setMinimumSize(QtCore.QSize(0, 0))
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_37.setObjectName("label_37")
        self.lineEdit_g = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_g.setGeometry(QtCore.QRect(210, 175, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_g.sizePolicy().hasHeightForWidth())
        self.lineEdit_g.setSizePolicy(sizePolicy)
        self.lineEdit_g.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_g.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_g.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_g.setObjectName("lineEdit_g")
        self.label_unit_S_or_UA_2 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_unit_S_or_UA_2.setGeometry(QtCore.QRect(315, 175, 51, 21))
        self.label_unit_S_or_UA_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_unit_S_or_UA_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_unit_S_or_UA_2.setObjectName("label_unit_S_or_UA_2")
        self.label_28 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_28.setGeometry(QtCore.QRect(10, 175, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_28.setObjectName("label_28")
        self.label_L_B = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_L_B.setGeometry(QtCore.QRect(10, 75, 181, 21))
        self.label_L_B.setMinimumSize(QtCore.QSize(0, 0))
        self.label_L_B.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_L_B.setObjectName("label_L_B")
        self.label_L_B_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_L_B_unit.setGeometry(QtCore.QRect(315, 75, 51, 21))
        self.label_L_B_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_L_B_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_L_B_unit.setObjectName("label_L_B_unit")
        self.lineEdit_L_B = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_L_B.setGeometry(QtCore.QRect(210, 75, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_L_B.sizePolicy().hasHeightForWidth())
        self.lineEdit_L_B.setSizePolicy(sizePolicy)
        self.lineEdit_L_B.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_L_B.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_L_B.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_L_B.setObjectName("lineEdit_L_B")
        self.label_unit_S_or_UA = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_unit_S_or_UA.setGeometry(QtCore.QRect(315, 150, 51, 21))
        self.label_unit_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.label_unit_S_or_UA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_unit_S_or_UA.setObjectName("label_unit_S_or_UA")
        self.lineEdit_T_0 = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_T_0.setGeometry(QtCore.QRect(210, 150, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_T_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_T_0.setSizePolicy(sizePolicy)
        self.lineEdit_T_0.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_T_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_T_0.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_T_0.setObjectName("lineEdit_T_0")
        self.label_27 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_27.setGeometry(QtCore.QRect(10, 150, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setObjectName("label_27")
        self.groupBox_outputs = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_outputs.setGeometry(QtCore.QRect(415, 525, 396, 81))
        self.groupBox_outputs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_outputs.setObjectName("groupBox_outputs")
        self.lineEdit_out_Q_dot_star = QtWidgets.QLineEdit(self.groupBox_outputs)
        self.lineEdit_out_Q_dot_star.setGeometry(QtCore.QRect(215, 25, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_Q_dot_star.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Q_dot_star.setSizePolicy(sizePolicy)
        self.lineEdit_out_Q_dot_star.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_Q_dot_star.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_out_Q_dot_star.setObjectName("lineEdit_out_Q_dot_star")
        self.lineEdit_out_Z_f = QtWidgets.QLineEdit(self.groupBox_outputs)
        self.lineEdit_out_Z_f.setGeometry(QtCore.QRect(215, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_Z_f.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Z_f.setSizePolicy(sizePolicy)
        self.lineEdit_out_Z_f.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_Z_f.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_out_Z_f.setObjectName("lineEdit_out_Z_f")
        self.label_out_Q_dot_star = QtWidgets.QLabel(self.groupBox_outputs)
        self.label_out_Q_dot_star.setGeometry(QtCore.QRect(10, 25, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_Q_dot_star.sizePolicy().hasHeightForWidth())
        self.label_out_Q_dot_star.setSizePolicy(sizePolicy)
        self.label_out_Q_dot_star.setMinimumSize(QtCore.QSize(40, 0))
        self.label_out_Q_dot_star.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_out_Q_dot_star.setObjectName("label_out_Q_dot_star")
        self.label_out_Z_f = QtWidgets.QLabel(self.groupBox_outputs)
        self.label_out_Z_f.setGeometry(QtCore.QRect(10, 50, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_Z_f.sizePolicy().hasHeightForWidth())
        self.label_out_Z_f.setSizePolicy(sizePolicy)
        self.label_out_Z_f.setMinimumSize(QtCore.QSize(20, 0))
        self.label_out_Z_f.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_out_Z_f.setObjectName("label_out_Z_f")
        self.label_out_Z_f_unit = QtWidgets.QLabel(self.groupBox_outputs)
        self.label_out_Z_f_unit.setGeometry(QtCore.QRect(320, 50, 51, 21))
        self.label_out_Z_f_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_out_Z_f_unit.setObjectName("label_out_Z_f_unit")
        self.groupBox_options = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_options.setGeometry(QtCore.QRect(415, 435, 396, 80))
        self.groupBox_options.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_options.setObjectName("groupBox_options")
        self.comboBox_fire_shape = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_fire_shape.setGeometry(QtCore.QRect(115, 25, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fire_shape.sizePolicy().hasHeightForWidth())
        self.comboBox_fire_shape.setSizePolicy(sizePolicy)
        self.comboBox_fire_shape.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_fire_shape.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_fire_shape.setObjectName("comboBox_fire_shape")
        self.comboBox_fire_shape.addItem("")
        self.comboBox_fire_shape.addItem("")
        self.comboBox_fire_shape.addItem("")
        self.label_29 = QtWidgets.QLabel(self.groupBox_options)
        self.label_29.setGeometry(QtCore.QRect(10, 25, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 0))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setObjectName("label_29")
        self.comboBox_fuel_type = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_fuel_type.setGeometry(QtCore.QRect(115, 50, 191, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fuel_type.sizePolicy().hasHeightForWidth())
        self.comboBox_fuel_type.setSizePolicy(sizePolicy)
        self.comboBox_fuel_type.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_fuel_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_fuel_type.setObjectName("comboBox_fuel_type")
        self.comboBox_fuel_type.addItem("")
        self.comboBox_fuel_type.addItem("")
        self.comboBox_fuel_type.addItem("")
        self.label_24 = QtWidgets.QLabel(self.groupBox_options)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setObjectName("label_24")
        self.label_image_figure = QtWidgets.QLabel(self.centralwidget)
        self.label_image_figure.setGeometry(QtCore.QRect(40, 15, 342, 284))
        self.label_image_figure.setText("")
        self.label_image_figure.setPixmap(QtGui.QPixmap("../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/png/0602_figure_342_284.png"))
        self.label_image_figure.setObjectName("label_image_figure")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_calculate, self.pushButton_test)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.pushButton_test.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Generate example input parameters.", None, -1))
        self.pushButton_test.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Generate example input parameters.", None, -1))
        self.pushButton_test.setText(QtWidgets.QApplication.translate("MainWindow", "Example", None, -1))
        self.groupBox_inputs.setTitle(QtWidgets.QApplication.translate("MainWindow", "Inputs", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "kJ/kg/K", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.label_Q_dot_or_Q_dot_l_unit.setText(QtWidgets.QApplication.translate("MainWindow", "kW", None, -1))
        self.lineEdit_Q_dot_or_Q_dot_l.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_Q_dot_or_Q_dot_l.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_L_A_or_D.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_L_A_or_D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_c_p_0.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_c_p_0.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_c_p_0.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.label_23.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Ambient are thermal capacity.", None, -1))
        self.label_23.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Ambient are thermal capacity.", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>c<span style=\" vertical-align:sub;\">p,0</span>, ambient air heat capacity</p></body></html>", None, -1))
        self.label_L_A_or_D.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Fire dimension 1.", None, -1))
        self.label_L_A_or_D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Fire dimension 1.", None, -1))
        self.label_L_A_or_D.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">A</span>, fire longer dimension</p></body></html>", None, -1))
        self.label_Q_dot_or_Q_dot_l.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Fire total heat release rate.", None, -1))
        self.label_Q_dot_or_Q_dot_l.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Fire total heat release rate.", None, -1))
        self.label_Q_dot_or_Q_dot_l.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Q<span style=\" vertical-align:super;\">`</span>, total heat release rate</p></body></html>", None, -1))
        self.label_35.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Ambient air density.", None, -1))
        self.label_35.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Ambient air density.", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>ρ<span style=\" vertical-align:sub;\">0</span>, ambient air density</p></body></html>", None, -1))
        self.lineEdit_rho_0.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_rho_0.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_rho_0.setText(QtWidgets.QApplication.translate("MainWindow", "1.2", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "kg/m<sup>3<sup>", None, -1))
        self.lineEdit_g.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_g.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_g.setText(QtWidgets.QApplication.translate("MainWindow", "9.81", None, -1))
        self.label_unit_S_or_UA_2.setText(QtWidgets.QApplication.translate("MainWindow", "m/s<sup>2<sup>", None, -1))
        self.label_28.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Gravity.", None, -1))
        self.label_28.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Gravity.", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "g, gravity", None, -1))
        self.label_L_B.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Fire dimension 2.", None, -1))
        self.label_L_B.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Fire dimension 2.", None, -1))
        self.label_L_B.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">B</span>, fire shorter dimension</p></body></html>", None, -1))
        self.label_L_B_unit.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.lineEdit_L_B.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_L_B.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.label_unit_S_or_UA.setText(QtWidgets.QApplication.translate("MainWindow", "K", None, -1))
        self.lineEdit_T_0.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_T_0.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_T_0.setText(QtWidgets.QApplication.translate("MainWindow", "293.15", None, -1))
        self.label_27.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Ambient air temperature.", None, -1))
        self.label_27.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Ambient air temperature.", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">0</span>, ambient air temperature</p></body></html>", None, -1))
        self.groupBox_outputs.setTitle(QtWidgets.QApplication.translate("MainWindow", "Outputs", None, -1))
        self.label_out_Q_dot_star.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved dimensionless heat release rate.", None, -1))
        self.label_out_Q_dot_star.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Solved dimensionless heat release rate.", None, -1))
        self.label_out_Q_dot_star.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Q`<span style=\" vertical-align:super;\">*</span>, dimensionless HRR</p></body></html>", None, -1))
        self.label_out_Z_f.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved flame height.", None, -1))
        self.label_out_Z_f.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Solved flame height.", None, -1))
        self.label_out_Z_f.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">f</span>, flame height</p></body></html>", None, -1))
        self.label_out_Z_f_unit.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.groupBox_options.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.comboBox_fire_shape.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Circular", None, -1))
        self.comboBox_fire_shape.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Rectangular", None, -1))
        self.comboBox_fire_shape.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Line", None, -1))
        self.label_29.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Fire shape.", None, -1))
        self.label_29.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Fire shape.", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Fire Shape", None, -1))
        self.comboBox_fuel_type.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Natural gas (Zukoski)", None, -1))
        self.comboBox_fuel_type.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Wood cribs (Thomas)", None, -1))
        self.comboBox_fuel_type.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Gas, liquids and solids (Heskestad)", None, -1))
        self.label_24.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Fuel type, this dictates the correlation that will be used for the calculation.", None, -1))
        self.label_24.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Fuel type, this dictates the correlation that will be used for the calculation.", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Fuel Type", None, -1))

