[tool.poetry]
name = "ekrhizoc"
version = "0.1.0"
description = "A simple python web crawler"
license = "MIT"
authors = ["Nicholas Elia <me@nichelia.com>"]
maintainers = ["Nicholas Elia <me@nichelia.com>"]
readme = "README.md"
homepage = "https://github.com/nichelia/ekrhizoc"
repository = "https://github.com/nichelia/ekrhizoc"
keywords = ["python", "web", "crawl"]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.7"              # PSF
poetry = "^1.0.3"            # MIT
tomlkit = "^0.5.8"           # MIT
beautifulsoup4 = "4.8.1"     # MIT
urlcanon = "^0.3.1"          # Apache2
asyncio = "^3.4.3"           # Apache2
aiohttp = "^3.6.2"           # Apache2
aiodns = "^2.0.0"            # MIT
brotlipy = "^0.7.0"          # MIT
networkx = "^2.4"            # BSD
pyyaml = "^5.3"              # MIT
matplotlib = "^3.1.3"        # MDT
reppy = "^0.4.14"            # MIT

[tool.poetry.dev-dependencies]
black = "19.10b0"            # MIT
isort = "4.3.4"              # MIT
mock = "4.0.1"               # BSD
pylint = "^2.4.4"            # GPLv2, but only used as a tool
pytest = "^5.3"              # MIT
pytest-cov = "^2.8"          # MIT
pytest-env = "^0.6.2"        # MIT

[tool.poetry.scripts]
ekrhizoc = "ekrhizoc.cli.__main__:main"

[build-system]
requires = ["wheel", "tomlkit", "poetry>=0.12.16"] # PEP 518
build-backend = "poetry.masonry.api"
