
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T23:13:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c8073d7ac9b225cfea9c2037b9544ce33fa1c73",
 "version": "0.0.4a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
