language: python
python:
- 3.7
script:
- pip install yapf
- diffs=$(yapf -dr --style=yapf.ini ./thunderbolt)
- if [ -n "$diffs" ]; then exit 1; fi
- python setup.py install
- python -m unittest discover -s ./test/
deploy:
  on:
    branch: master
    tags: true
  provider: pypi
  user: vaaaaanquish
  skip_existing: true
  password:
    secure: RhxtLbK/reRuCdRCUgtGrmTm5JjQh/hisNODBHWwlL3C84xADhRrHlXlal+IUNoXGLYe7m8DwR2bO8DUldGaVV9reWpJ2W9mKd9borgt4ZSKShqNRqsf0dnkHIY5HkIdfrac6ECkLXy1FOmfxXpRCXjp9G2Xy2/QtfytgBptp7jLHTzOIcQjckc4LnEk2qe6ZHVXDetN3+fuCRywU0truQrTrcBdqUhIJi0gvDMv7WrC3CIMPiRjlojhHVol3RyPL2EeRBAqfz/ww0U9jPXC4Evh2cJvJ1Mwpu4ER7aBkREhBscYpbCahNIvOECBJ7U3lEoS845G6vHyEwME+jWnmzAeWUAbWIrH4uvm/AlED3zrqij2m9rEpmpVI6f1GJUI9Ea6Bq/mZ6kY5I7zccDRCz7APVsgWopMvtvdVQPPch6HdATvbW8fedKN2Mu+HlCRUaWpoH0ogI9MwynxTTF4I+/IUEe1Lv5xXLogArHnB9RB2NTCdvdaSpA7SUvwQCtuRU/7CALHxguax3fj+bSXIMymxT6C72VyEyH0a+ZIlyJubJ2fSWdAsdrNoQn9TC5o2eNgUhqAQK+keP2X/1F6P6ZH9ehxEYnlpUnrfWyZgEIfKmCFuoXapBttGEw6vnqDuPQv3zv5gnnkRZyb+ikGzFUbiX7iVanHa6xqOYjDjl8=
