# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 05:30
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_dse', '0022_auto_20190501_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetspecification',
            name='implementation_end_date',
        ),
        migrations.RemoveField(
            model_name='datasetspecification',
            name='implementation_start_date',
        ),
        migrations.AlterField(
            model_name='datasetspecification',
            name='statistical_unit',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, help_text='A Statistical Unit is the Object Class that is recorded against each entry described by this specification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistical_unit_of', to='aristotle_mdr._concept', verbose_name='Statistical Unit'),
        ),
    ]
