# Generated by Django 2.2.8 on 2020-01-17 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aristotle_dse', '0030_auto_20190809_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Data Set'},
        ),
    ]
