# Generated by Django 2.2.6 on 2019-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='_target',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='likestats',
            name='_target',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
