# Generated by Django 2.2.6 on 2020-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_like_author_anonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_reviewd',
            field=models.BooleanField(default=True),
        ),
    ]
