env:
  matrix:
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
  - TRAVIS_PYTHON_VERSION="3.7"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"

os:
  - linux
  - osx

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    fi
  - |
    if [[ "$TRAVIS_TAG" == v* ]]; then
      CIBUILD=1
    fi
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      CIBUILD=1
    fi

install:
  - echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
  - bash $HOME/minconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
  - conda config --append channels conda-forge
  - conda update -q conda
  - conda info -a

  # Create new env and install deps
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pillow pytest=3.8.1 pyqt pytest-mpl
  - source activate test-environment
  # - conda install -q numpy scipy matplotlib pillow pytest pyqt
  # - conda install -q -c conda-forge pytest-mpl
  - hash -r

before_script:
  # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 5 # give xvfb some time to start

script:
  - pytest --mpl --mpl-results-path=tests/results

after_success:
  - |
    if [[ "$CIBUILD" == "1" ]]; then
      conda install -q conda-build anaconda-client
      pip install twine wheel
    fi
  - python .ci/travis/anaconda_build_upload.py
  - python .ci/travis/pypi_build_upload.py

after_failure:
  deploy:
  - provider: script
    script: bash .ci/travis/ftp_artifacts.sh
