# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('aristotle_mdr_publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionPermissions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reversion.Version')),
                ('visibility_permission', models.CharField(choices=[(0, 'Public'), (1, 'Authenticated'), (2, 'Workgroup')], default=2, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
