# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_publishing', '0003_auto_20190416_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionpermissions',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Authenticated'), (2, 'Workgroup')], default=2, max_length=20),
        ),
    ]
