# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_0111_heat_detector_activation.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(826, 744)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_image_context = QLabel(self.centralwidget)
        self.label_image_context.setObjectName(u"label_image_context")
        self.label_image_context.setGeometry(QRect(15, 15, 794, 681))
        self.label_image_context.setPixmap(QPixmap(u"../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/png/0111_context_2_794_560.png"))
        self.groupBox_in = QGroupBox(self.centralwidget)
        self.groupBox_in.setObjectName(u"groupBox_in")
        self.groupBox_in.setGeometry(QRect(415, 220, 396, 256))
        self.label_51 = QLabel(self.groupBox_in)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(315, 225, 66, 21))
        self.label_51.setMinimumSize(QSize(0, 0))
        self.label_51.setMaximumSize(QSize(16777215, 16777215))
        self.label_48 = QLabel(self.groupBox_in)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(315, 150, 66, 21))
        self.label_48.setMinimumSize(QSize(0, 0))
        self.label_48.setMaximumSize(QSize(16777215, 16777215))
        self.label_in_R_label = QLabel(self.groupBox_in)
        self.label_in_R_label.setObjectName(u"label_in_R_label")
        self.label_in_R_label.setGeometry(QRect(10, 100, 181, 21))
        self.label_in_R_label.setMinimumSize(QSize(60, 21))
        self.label_in_R_label.setMaximumSize(QSize(16777215, 16777215))
        self.label_40 = QLabel(self.groupBox_in)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 175, 181, 21))
        self.label_40.setMinimumSize(QSize(60, 21))
        self.label_40.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_C_conv = QLineEdit(self.groupBox_in)
        self.lineEdit_in_C_conv.setObjectName(u"lineEdit_in_C_conv")
        self.lineEdit_in_C_conv.setGeometry(QRect(210, 200, 91, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_C_conv.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_C_conv.setSizePolicy(sizePolicy)
        self.lineEdit_in_C_conv.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_C_conv.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_C_conv.setBaseSize(QSize(0, 0))
        self.label_31 = QLabel(self.groupBox_in)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 25, 181, 21))
        self.label_31.setMinimumSize(QSize(0, 0))
        self.label_31.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_T_act = QLineEdit(self.groupBox_in)
        self.lineEdit_in_T_act.setObjectName(u"lineEdit_in_T_act")
        self.lineEdit_in_T_act.setGeometry(QRect(210, 225, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_T_act.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_T_act.setSizePolicy(sizePolicy)
        self.lineEdit_in_T_act.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_T_act.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_T_act.setBaseSize(QSize(0, 0))
        self.label_49 = QLabel(self.groupBox_in)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(315, 175, 66, 21))
        self.label_49.setMinimumSize(QSize(0, 0))
        self.label_49.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_R = QLineEdit(self.groupBox_in)
        self.lineEdit_in_R.setObjectName(u"lineEdit_in_R")
        self.lineEdit_in_R.setGeometry(QRect(210, 100, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_R.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_R.setSizePolicy(sizePolicy)
        self.lineEdit_in_R.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_R.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_R.setBaseSize(QSize(0, 0))
        self.label_39 = QLabel(self.groupBox_in)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 150, 181, 21))
        self.label_39.setMinimumSize(QSize(60, 21))
        self.label_39.setMaximumSize(QSize(16777215, 16777215))
        self.label_in_R_unit = QLabel(self.groupBox_in)
        self.label_in_R_unit.setObjectName(u"label_in_R_unit")
        self.label_in_R_unit.setGeometry(QRect(315, 100, 66, 21))
        self.label_in_R_unit.setMinimumSize(QSize(0, 0))
        self.label_in_R_unit.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_C = QLineEdit(self.groupBox_in)
        self.lineEdit_in_C.setObjectName(u"lineEdit_in_C")
        self.lineEdit_in_C.setGeometry(QRect(210, 150, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_C.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_C.setSizePolicy(sizePolicy)
        self.lineEdit_in_C.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_C.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_C.setBaseSize(QSize(0, 0))
        self.label_47 = QLabel(self.groupBox_in)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(315, 125, 66, 21))
        self.label_47.setMinimumSize(QSize(0, 0))
        self.label_47.setMaximumSize(QSize(16777215, 16777215))
        self.label_35 = QLabel(self.groupBox_in)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 50, 181, 21))
        self.label_35.setMinimumSize(QSize(60, 21))
        self.label_35.setMaximumSize(QSize(16777215, 16777215))
        self.label_36 = QLabel(self.groupBox_in)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 75, 181, 21))
        self.label_36.setMinimumSize(QSize(60, 21))
        self.label_36.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_RTI = QLineEdit(self.groupBox_in)
        self.lineEdit_in_RTI.setObjectName(u"lineEdit_in_RTI")
        self.lineEdit_in_RTI.setGeometry(QRect(210, 125, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_RTI.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_RTI.setSizePolicy(sizePolicy)
        self.lineEdit_in_RTI.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_RTI.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_RTI.setBaseSize(QSize(0, 0))
        self.label_45 = QLabel(self.groupBox_in)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(315, 75, 66, 21))
        self.label_45.setMinimumSize(QSize(0, 0))
        self.label_45.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_H = QLineEdit(self.groupBox_in)
        self.lineEdit_in_H.setObjectName(u"lineEdit_in_H")
        self.lineEdit_in_H.setGeometry(QRect(210, 75, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_H.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_H.setSizePolicy(sizePolicy)
        self.lineEdit_in_H.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_H.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_H.setBaseSize(QSize(0, 0))
        self.lineEdit_in_t = QLineEdit(self.groupBox_in)
        self.lineEdit_in_t.setObjectName(u"lineEdit_in_t")
        self.lineEdit_in_t.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_t.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_t.setSizePolicy(sizePolicy)
        self.lineEdit_in_t.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_t.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_t.setBaseSize(QSize(0, 0))
        self.label_43 = QLabel(self.groupBox_in)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(315, 25, 66, 21))
        self.label_43.setMinimumSize(QSize(0, 0))
        self.label_43.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_alpha = QLineEdit(self.groupBox_in)
        self.lineEdit_in_alpha.setObjectName(u"lineEdit_in_alpha")
        self.lineEdit_in_alpha.setGeometry(QRect(210, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_alpha.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_alpha.setSizePolicy(sizePolicy)
        self.lineEdit_in_alpha.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_alpha.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_alpha.setBaseSize(QSize(0, 0))
        self.label_41 = QLabel(self.groupBox_in)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 200, 181, 21))
        self.label_41.setMinimumSize(QSize(60, 21))
        self.label_41.setMaximumSize(QSize(16777215, 16777215))
        self.label_44 = QLabel(self.groupBox_in)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(315, 50, 66, 21))
        self.label_44.setMinimumSize(QSize(0, 0))
        self.label_44.setMaximumSize(QSize(16777215, 16777215))
        self.label_42 = QLabel(self.groupBox_in)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 225, 181, 21))
        self.label_42.setMinimumSize(QSize(60, 21))
        self.label_42.setMaximumSize(QSize(16777215, 16777215))
        self.label_38 = QLabel(self.groupBox_in)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 125, 181, 21))
        self.label_38.setMinimumSize(QSize(60, 21))
        self.label_38.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_HRRPUA = QLineEdit(self.groupBox_in)
        self.lineEdit_in_HRRPUA.setObjectName(u"lineEdit_in_HRRPUA")
        self.lineEdit_in_HRRPUA.setGeometry(QRect(210, 175, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_HRRPUA.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_HRRPUA.setSizePolicy(sizePolicy)
        self.lineEdit_in_HRRPUA.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_HRRPUA.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_HRRPUA.setBaseSize(QSize(0, 0))
        self.label_50 = QLabel(self.groupBox_in)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(315, 200, 66, 21))
        self.label_50.setMinimumSize(QSize(0, 0))
        self.label_50.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox_gas_correlation = QGroupBox(self.centralwidget)
        self.groupBox_gas_correlation.setObjectName(u"groupBox_gas_correlation")
        self.groupBox_gas_correlation.setGeometry(QRect(415, 485, 396, 80))
        self.radioButton_ceiling_jet = QRadioButton(self.groupBox_gas_correlation)
        self.radioButton_ceiling_jet.setObjectName(u"radioButton_ceiling_jet")
        self.radioButton_ceiling_jet.setGeometry(QRect(10, 25, 176, 20))
        self.radioButton_fire_plume = QRadioButton(self.groupBox_gas_correlation)
        self.radioButton_fire_plume.setObjectName(u"radioButton_fire_plume")
        self.radioButton_fire_plume.setGeometry(QRect(10, 50, 171, 20))
        self.groupBox_out = QGroupBox(self.centralwidget)
        self.groupBox_out.setObjectName(u"groupBox_out")
        self.groupBox_out.setGeometry(QRect(415, 575, 396, 56))
        self.lineEdit_out_t_act = QLineEdit(self.groupBox_out)
        self.lineEdit_out_t_act.setObjectName(u"lineEdit_out_t_act")
        self.lineEdit_out_t_act.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_t_act.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_t_act.setSizePolicy(sizePolicy)
        self.lineEdit_out_t_act.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_t_act.setMaximumSize(QSize(16777215, 16777215))
        self.label_11 = QLabel(self.groupBox_out)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(15, 25, 181, 21))
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QSize(61, 0))
        self.label_11.setMaximumSize(QSize(16777215, 16777215))
        self.label_25 = QLabel(self.groupBox_out)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(315, 25, 50, 21))
        self.label_image_figure = QLabel(self.centralwidget)
        self.label_image_figure.setObjectName(u"label_image_figure")
        self.label_image_figure.setGeometry(QRect(15, 15, 342, 284))
        self.label_image_figure.setPixmap(QPixmap(u"../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/png/0111_figure_1_342_284.png"))
        self.pushButton_show_results_in_table = QPushButton(self.centralwidget)
        self.pushButton_show_results_in_table.setObjectName(u"pushButton_show_results_in_table")
        self.pushButton_show_results_in_table.setEnabled(False)
        self.pushButton_show_results_in_table.setGeometry(QRect(605, 645, 96, 26))
        self.pushButton_calculate = QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName(u"pushButton_calculate")
        self.pushButton_calculate.setGeometry(QRect(715, 645, 96, 26))
        self.pushButton_test = QPushButton(self.centralwidget)
        self.pushButton_test.setObjectName(u"pushButton_test")
        self.pushButton_test.setGeometry(QRect(415, 645, 96, 26))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 826, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lineEdit_in_t, self.lineEdit_in_alpha)
        QWidget.setTabOrder(self.lineEdit_in_alpha, self.lineEdit_in_H)
        QWidget.setTabOrder(self.lineEdit_in_H, self.lineEdit_in_R)
        QWidget.setTabOrder(self.lineEdit_in_R, self.lineEdit_in_RTI)
        QWidget.setTabOrder(self.lineEdit_in_RTI, self.lineEdit_in_C)
        QWidget.setTabOrder(self.lineEdit_in_C, self.lineEdit_in_HRRPUA)
        QWidget.setTabOrder(self.lineEdit_in_HRRPUA, self.lineEdit_in_C_conv)
        QWidget.setTabOrder(self.lineEdit_in_C_conv, self.lineEdit_in_T_act)
        QWidget.setTabOrder(self.lineEdit_in_T_act, self.radioButton_ceiling_jet)
        QWidget.setTabOrder(self.radioButton_ceiling_jet, self.radioButton_fire_plume)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_image_context.setText("")
        self.groupBox_in.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"m<sup>0.5</sup>/s<sup>0.5</sup>", None))
#if QT_CONFIG(tooltip)
        self.label_in_R_label.setToolTip(QCoreApplication.translate("MainWindow", u"Lateral distance between HD and fire central axis", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_in_R_label.setStatusTip(QCoreApplication.translate("MainWindow", u"Lateral distance between HD and fire central axis", None))
#endif // QT_CONFIG(statustip)
        self.label_in_R_label.setText(QCoreApplication.translate("MainWindow", u"R, radial distance", None))
#if QT_CONFIG(tooltip)
        self.label_40.setToolTip(QCoreApplication.translate("MainWindow", u"Heat release rate per unit area", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_40.setStatusTip(QCoreApplication.translate("MainWindow", u"Heat release rate per unit area", None))
#endif // QT_CONFIG(statustip)
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"HRR per unit area", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_C_conv.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_C_conv.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.label_31.setToolTip(QCoreApplication.translate("MainWindow", u"Fire duration", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_31.setStatusTip(QCoreApplication.translate("MainWindow", u"Fire duration", None))
#endif // QT_CONFIG(statustip)
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"t, fire duration", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_T_act.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_T_act.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_R.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_R.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.label_39.setToolTip(QCoreApplication.translate("MainWindow", u"Conduction factor", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_39.setStatusTip(QCoreApplication.translate("MainWindow", u"Conduction factor", None))
#endif // QT_CONFIG(statustip)
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"C, conduction factor", None))
        self.label_in_R_unit.setText(QCoreApplication.translate("MainWindow", u"m", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_C.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_C.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"m<sup>0.5</sup>\u22c5s<sup>0.5</sup>", None))
#if QT_CONFIG(tooltip)
        self.label_35.setToolTip(QCoreApplication.translate("MainWindow", u"Fire growth factor for t-square fire", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_35.setStatusTip(QCoreApplication.translate("MainWindow", u"Fire growth factor for t-square fire", None))
#endif // QT_CONFIG(statustip)
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"\u03b1, fire growth factor", None))
#if QT_CONFIG(tooltip)
        self.label_36.setToolTip(QCoreApplication.translate("MainWindow", u"Vertical distance between the fire bed and the detecting element", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_36.setStatusTip(QCoreApplication.translate("MainWindow", u"Vertical distance between the fire bed and the detecting element", None))
#endif // QT_CONFIG(statustip)
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"H, height", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_RTI.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_RTI.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"m", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_H.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_H.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_in_t.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_t.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"s", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_alpha.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float, {'slow': 0.0029, 'medium': 0.0117, 'fast': 0.0469, 'ultra-fast': 0.1876}", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_alpha.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float, {'slow': 0.0029, 'medium': 0.0117, 'fast': 0.0469, 'ultra-fast': 0.1876}", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.label_41.setToolTip(QCoreApplication.translate("MainWindow", u"Percentage of convective heat release rate to total heat release rate", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_41.setStatusTip(QCoreApplication.translate("MainWindow", u"Percentage of convective heat release rate to total heat release rate", None))
#endif // QT_CONFIG(statustip)
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>C<span style=\" vertical-align:sub;\">conv</span>, convection HRR</p></body></html>", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"kW/s\u00b2", None))
#if QT_CONFIG(tooltip)
        self.label_42.setToolTip(QCoreApplication.translate("MainWindow", u"Heat detecting element activation temperature", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_42.setStatusTip(QCoreApplication.translate("MainWindow", u"Heat detecting element activation temperature", None))
#endif // QT_CONFIG(statustip)
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>T<span style=\" vertical-align:sub;\">act</span>, detector activation temp.</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_38.setToolTip(QCoreApplication.translate("MainWindow", u"Response time index", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_38.setStatusTip(QCoreApplication.translate("MainWindow", u"Response time index", None))
#endif // QT_CONFIG(statustip)
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"RTI, response time index", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_in_HRRPUA.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_in_HRRPUA.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float", None))
#endif // QT_CONFIG(statustip)
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBox_gas_correlation.setTitle(QCoreApplication.translate("MainWindow", u"Gas Temperature and Velocity Correlation", None))
#if QT_CONFIG(tooltip)
        self.radioButton_ceiling_jet.setToolTip(QCoreApplication.translate("MainWindow", u"To use ceiling jet equations for calculating temperature and velocity", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.radioButton_ceiling_jet.setStatusTip(QCoreApplication.translate("MainWindow", u"To use ceiling jet equations for calculating temperature and velocity", None))
#endif // QT_CONFIG(statustip)
        self.radioButton_ceiling_jet.setText(QCoreApplication.translate("MainWindow", u"Use Ceiling Jet Equations", None))
#if QT_CONFIG(tooltip)
        self.radioButton_fire_plume.setToolTip(QCoreApplication.translate("MainWindow", u"To use plume equations for calculating temperature and velocity", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.radioButton_fire_plume.setStatusTip(QCoreApplication.translate("MainWindow", u"To use plume equations for calculating temperature and velocity", None))
#endif // QT_CONFIG(statustip)
        self.radioButton_fire_plume.setText(QCoreApplication.translate("MainWindow", u"Use Plume Equations", None))
        self.groupBox_out.setTitle(QCoreApplication.translate("MainWindow", u"Outputs", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_out_t_act.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("MainWindow", u"Solved heat detecting element activation time", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_11.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved heat detecting element activation time", None))
#endif // QT_CONFIG(statustip)
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>t<span style=\" vertical-align:sub;\">act</span>, detector activation time</p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"s", None))
        self.label_image_figure.setText("")
        self.pushButton_show_results_in_table.setText(QCoreApplication.translate("MainWindow", u"Full Results", None))
        self.pushButton_calculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.pushButton_test.setText(QCoreApplication.translate("MainWindow", u"Example", None))
    # retranslateUi

