# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_0602_pd_7974_flame_height.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(826, 751)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_calculate = QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName(u"pushButton_calculate")
        self.pushButton_calculate.setGeometry(QRect(715, 635, 96, 24))
        self.pushButton_calculate.setMaximumSize(QSize(16777215, 16777215))
        self.pushButton_test = QPushButton(self.centralwidget)
        self.pushButton_test.setObjectName(u"pushButton_test")
        self.pushButton_test.setGeometry(QRect(600, 635, 96, 24))
        self.pushButton_test.setMaximumSize(QSize(16777215, 16777215))
        self.label_image_context = QLabel(self.centralwidget)
        self.label_image_context.setObjectName(u"label_image_context")
        self.label_image_context.setGeometry(QRect(15, 15, 796, 681))
        self.label_image_context.setMaximumSize(QSize(16777215, 16777215))
        self.label_image_context.setPixmap(QPixmap(u"../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/png/0602_context_794_681.png"))
        self.groupBox_inputs = QGroupBox(self.centralwidget)
        self.groupBox_inputs.setObjectName(u"groupBox_inputs")
        self.groupBox_inputs.setGeometry(QRect(415, 225, 396, 216))
        self.groupBox_inputs.setMaximumSize(QSize(16777215, 16777215))
        self.label_34 = QLabel(self.groupBox_inputs)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(315, 125, 51, 21))
        self.label_34.setMinimumSize(QSize(0, 0))
        self.label_34.setMaximumSize(QSize(16777215, 16777215))
        self.label_33 = QLabel(self.groupBox_inputs)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(315, 50, 51, 21))
        self.label_33.setMinimumSize(QSize(0, 0))
        self.label_33.setMaximumSize(QSize(16777215, 16777215))
        self.label_Q_dot_or_Q_dot_l_unit = QLabel(self.groupBox_inputs)
        self.label_Q_dot_or_Q_dot_l_unit.setObjectName(u"label_Q_dot_or_Q_dot_l_unit")
        self.label_Q_dot_or_Q_dot_l_unit.setGeometry(QRect(315, 25, 55, 21))
        self.label_Q_dot_or_Q_dot_l_unit.setMinimumSize(QSize(0, 0))
        self.label_Q_dot_or_Q_dot_l_unit.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_Q_dot_or_Q_dot_l = QLineEdit(self.groupBox_inputs)
        self.lineEdit_Q_dot_or_Q_dot_l.setObjectName(u"lineEdit_Q_dot_or_Q_dot_l")
        self.lineEdit_Q_dot_or_Q_dot_l.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Q_dot_or_Q_dot_l.sizePolicy().hasHeightForWidth())
        self.lineEdit_Q_dot_or_Q_dot_l.setSizePolicy(sizePolicy)
        self.lineEdit_Q_dot_or_Q_dot_l.setMinimumSize(QSize(0, 0))
        self.lineEdit_Q_dot_or_Q_dot_l.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_Q_dot_or_Q_dot_l.setBaseSize(QSize(0, 0))
        self.lineEdit_L_A_or_D = QLineEdit(self.groupBox_inputs)
        self.lineEdit_L_A_or_D.setObjectName(u"lineEdit_L_A_or_D")
        self.lineEdit_L_A_or_D.setGeometry(QRect(210, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_L_A_or_D.sizePolicy().hasHeightForWidth())
        self.lineEdit_L_A_or_D.setSizePolicy(sizePolicy)
        self.lineEdit_L_A_or_D.setMinimumSize(QSize(0, 0))
        self.lineEdit_L_A_or_D.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_L_A_or_D.setBaseSize(QSize(0, 0))
        self.lineEdit_c_p_0 = QLineEdit(self.groupBox_inputs)
        self.lineEdit_c_p_0.setObjectName(u"lineEdit_c_p_0")
        self.lineEdit_c_p_0.setGeometry(QRect(210, 125, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_c_p_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_c_p_0.setSizePolicy(sizePolicy)
        self.lineEdit_c_p_0.setMinimumSize(QSize(0, 0))
        self.lineEdit_c_p_0.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_c_p_0.setBaseSize(QSize(0, 0))
        self.label_23 = QLabel(self.groupBox_inputs)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 125, 181, 21))
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QSize(0, 0))
        self.label_23.setMaximumSize(QSize(16777215, 16777215))
        self.label_L_A_or_D = QLabel(self.groupBox_inputs)
        self.label_L_A_or_D.setObjectName(u"label_L_A_or_D")
        self.label_L_A_or_D.setGeometry(QRect(10, 50, 181, 21))
        sizePolicy.setHeightForWidth(self.label_L_A_or_D.sizePolicy().hasHeightForWidth())
        self.label_L_A_or_D.setSizePolicy(sizePolicy)
        self.label_L_A_or_D.setMinimumSize(QSize(0, 0))
        self.label_L_A_or_D.setMaximumSize(QSize(16777215, 16777215))
        self.label_Q_dot_or_Q_dot_l = QLabel(self.groupBox_inputs)
        self.label_Q_dot_or_Q_dot_l.setObjectName(u"label_Q_dot_or_Q_dot_l")
        self.label_Q_dot_or_Q_dot_l.setGeometry(QRect(10, 25, 181, 21))
        self.label_Q_dot_or_Q_dot_l.setMinimumSize(QSize(0, 0))
        self.label_Q_dot_or_Q_dot_l.setMaximumSize(QSize(16777215, 16777215))
        self.label_35 = QLabel(self.groupBox_inputs)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 100, 181, 21))
        self.label_35.setMinimumSize(QSize(0, 0))
        self.label_35.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_rho_0 = QLineEdit(self.groupBox_inputs)
        self.lineEdit_rho_0.setObjectName(u"lineEdit_rho_0")
        self.lineEdit_rho_0.setGeometry(QRect(210, 100, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_rho_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_rho_0.setSizePolicy(sizePolicy)
        self.lineEdit_rho_0.setMinimumSize(QSize(0, 0))
        self.lineEdit_rho_0.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_rho_0.setBaseSize(QSize(0, 0))
        self.label_37 = QLabel(self.groupBox_inputs)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(315, 100, 51, 21))
        self.label_37.setMinimumSize(QSize(0, 0))
        self.label_37.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_g = QLineEdit(self.groupBox_inputs)
        self.lineEdit_g.setObjectName(u"lineEdit_g")
        self.lineEdit_g.setGeometry(QRect(210, 175, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_g.sizePolicy().hasHeightForWidth())
        self.lineEdit_g.setSizePolicy(sizePolicy)
        self.lineEdit_g.setMinimumSize(QSize(0, 0))
        self.lineEdit_g.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_g.setBaseSize(QSize(0, 0))
        self.label_unit_S_or_UA_2 = QLabel(self.groupBox_inputs)
        self.label_unit_S_or_UA_2.setObjectName(u"label_unit_S_or_UA_2")
        self.label_unit_S_or_UA_2.setGeometry(QRect(315, 175, 51, 21))
        self.label_unit_S_or_UA_2.setMinimumSize(QSize(0, 0))
        self.label_unit_S_or_UA_2.setMaximumSize(QSize(16777215, 16777215))
        self.label_28 = QLabel(self.groupBox_inputs)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 175, 181, 21))
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QSize(0, 0))
        self.label_28.setMaximumSize(QSize(16777215, 16777215))
        self.label_L_B = QLabel(self.groupBox_inputs)
        self.label_L_B.setObjectName(u"label_L_B")
        self.label_L_B.setGeometry(QRect(10, 75, 181, 21))
        self.label_L_B.setMinimumSize(QSize(0, 0))
        self.label_L_B.setMaximumSize(QSize(16777215, 16777215))
        self.label_L_B_unit = QLabel(self.groupBox_inputs)
        self.label_L_B_unit.setObjectName(u"label_L_B_unit")
        self.label_L_B_unit.setGeometry(QRect(315, 75, 51, 21))
        self.label_L_B_unit.setMinimumSize(QSize(0, 0))
        self.label_L_B_unit.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_L_B = QLineEdit(self.groupBox_inputs)
        self.lineEdit_L_B.setObjectName(u"lineEdit_L_B")
        self.lineEdit_L_B.setGeometry(QRect(210, 75, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_L_B.sizePolicy().hasHeightForWidth())
        self.lineEdit_L_B.setSizePolicy(sizePolicy)
        self.lineEdit_L_B.setMinimumSize(QSize(0, 0))
        self.lineEdit_L_B.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_L_B.setBaseSize(QSize(0, 0))
        self.label_unit_S_or_UA = QLabel(self.groupBox_inputs)
        self.label_unit_S_or_UA.setObjectName(u"label_unit_S_or_UA")
        self.label_unit_S_or_UA.setGeometry(QRect(315, 150, 51, 21))
        self.label_unit_S_or_UA.setMinimumSize(QSize(0, 0))
        self.label_unit_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_T_0 = QLineEdit(self.groupBox_inputs)
        self.lineEdit_T_0.setObjectName(u"lineEdit_T_0")
        self.lineEdit_T_0.setGeometry(QRect(210, 150, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_T_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_T_0.setSizePolicy(sizePolicy)
        self.lineEdit_T_0.setMinimumSize(QSize(0, 0))
        self.lineEdit_T_0.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_T_0.setBaseSize(QSize(0, 0))
        self.label_27 = QLabel(self.groupBox_inputs)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 150, 181, 21))
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QSize(0, 0))
        self.label_27.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox_outputs = QGroupBox(self.centralwidget)
        self.groupBox_outputs.setObjectName(u"groupBox_outputs")
        self.groupBox_outputs.setGeometry(QRect(415, 540, 396, 81))
        self.groupBox_outputs.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_out_Q_dot_star = QLineEdit(self.groupBox_outputs)
        self.lineEdit_out_Q_dot_star.setObjectName(u"lineEdit_out_Q_dot_star")
        self.lineEdit_out_Q_dot_star.setGeometry(QRect(215, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_Q_dot_star.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Q_dot_star.setSizePolicy(sizePolicy)
        self.lineEdit_out_Q_dot_star.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_Q_dot_star.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_out_Z_f = QLineEdit(self.groupBox_outputs)
        self.lineEdit_out_Z_f.setObjectName(u"lineEdit_out_Z_f")
        self.lineEdit_out_Z_f.setGeometry(QRect(215, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_Z_f.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Z_f.setSizePolicy(sizePolicy)
        self.lineEdit_out_Z_f.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_Z_f.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_Q_dot_star = QLabel(self.groupBox_outputs)
        self.label_out_Q_dot_star.setObjectName(u"label_out_Q_dot_star")
        self.label_out_Q_dot_star.setGeometry(QRect(10, 25, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_Q_dot_star.sizePolicy().hasHeightForWidth())
        self.label_out_Q_dot_star.setSizePolicy(sizePolicy)
        self.label_out_Q_dot_star.setMinimumSize(QSize(40, 0))
        self.label_out_Q_dot_star.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_Z_f = QLabel(self.groupBox_outputs)
        self.label_out_Z_f.setObjectName(u"label_out_Z_f")
        self.label_out_Z_f.setGeometry(QRect(10, 50, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_Z_f.sizePolicy().hasHeightForWidth())
        self.label_out_Z_f.setSizePolicy(sizePolicy)
        self.label_out_Z_f.setMinimumSize(QSize(20, 0))
        self.label_out_Z_f.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_Z_f_unit = QLabel(self.groupBox_outputs)
        self.label_out_Z_f_unit.setObjectName(u"label_out_Z_f_unit")
        self.label_out_Z_f_unit.setGeometry(QRect(320, 50, 51, 21))
        self.label_out_Z_f_unit.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox_options = QGroupBox(self.centralwidget)
        self.groupBox_options.setObjectName(u"groupBox_options")
        self.groupBox_options.setGeometry(QRect(415, 450, 396, 80))
        self.groupBox_options.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_fire_shape = QComboBox(self.groupBox_options)
        self.comboBox_fire_shape.addItem("")
        self.comboBox_fire_shape.addItem("")
        self.comboBox_fire_shape.addItem("")
        self.comboBox_fire_shape.setObjectName(u"comboBox_fire_shape")
        self.comboBox_fire_shape.setGeometry(QRect(115, 25, 191, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.comboBox_fire_shape.sizePolicy().hasHeightForWidth())
        self.comboBox_fire_shape.setSizePolicy(sizePolicy1)
        self.comboBox_fire_shape.setMinimumSize(QSize(0, 0))
        self.comboBox_fire_shape.setMaximumSize(QSize(16777215, 16777215))
        self.label_29 = QLabel(self.groupBox_options)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QSize(0, 0))
        self.label_29.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_fuel_type = QComboBox(self.groupBox_options)
        self.comboBox_fuel_type.addItem("")
        self.comboBox_fuel_type.addItem("")
        self.comboBox_fuel_type.addItem("")
        self.comboBox_fuel_type.setObjectName(u"comboBox_fuel_type")
        self.comboBox_fuel_type.setGeometry(QRect(115, 50, 191, 21))
        sizePolicy1.setHeightForWidth(self.comboBox_fuel_type.sizePolicy().hasHeightForWidth())
        self.comboBox_fuel_type.setSizePolicy(sizePolicy1)
        self.comboBox_fuel_type.setMinimumSize(QSize(0, 0))
        self.comboBox_fuel_type.setMaximumSize(QSize(16777215, 16777215))
        self.label_24 = QLabel(self.groupBox_options)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QSize(0, 0))
        self.label_24.setMaximumSize(QSize(16777215, 16777215))
        self.label_image_figure = QLabel(self.centralwidget)
        self.label_image_figure.setObjectName(u"label_image_figure")
        self.label_image_figure.setGeometry(QRect(40, 15, 342, 284))
        self.label_image_figure.setPixmap(QPixmap(u"../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/png/0602_figure_342_284.png"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_image_context.raise_()
        self.pushButton_calculate.raise_()
        self.pushButton_test.raise_()
        self.groupBox_inputs.raise_()
        self.groupBox_outputs.raise_()
        self.groupBox_options.raise_()
        self.label_image_figure.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 826, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.pushButton_calculate, self.pushButton_test)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_calculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(tooltip)
        self.pushButton_test.setToolTip(QCoreApplication.translate("MainWindow", u"Generate example input parameters.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_test.setStatusTip(QCoreApplication.translate("MainWindow", u"Generate example input parameters.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_test.setText(QCoreApplication.translate("MainWindow", u"Example", None))
        self.label_image_context.setText("")
        self.groupBox_inputs.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"kJ/kg/K", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_Q_dot_or_Q_dot_l_unit.setText(QCoreApplication.translate("MainWindow", u"kW", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_Q_dot_or_Q_dot_l.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_Q_dot_or_Q_dot_l.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_L_A_or_D.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_L_A_or_D.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_c_p_0.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_c_p_0.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_c_p_0.setText(QCoreApplication.translate("MainWindow", u"1.0", None))
#if QT_CONFIG(tooltip)
        self.label_23.setToolTip(QCoreApplication.translate("MainWindow", u"Ambient are thermal capacity.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_23.setStatusTip(QCoreApplication.translate("MainWindow", u"Ambient are thermal capacity.", None))
#endif // QT_CONFIG(statustip)
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>c<span style=\" vertical-align:sub;\">p,0</span>, ambient air heat capacity</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_L_A_or_D.setToolTip(QCoreApplication.translate("MainWindow", u"Fire dimension 1.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_L_A_or_D.setStatusTip(QCoreApplication.translate("MainWindow", u"Fire dimension 1.", None))
#endif // QT_CONFIG(statustip)
        self.label_L_A_or_D.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L<span style=\" vertical-align:sub;\">A</span>, fire longer dimension</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_Q_dot_or_Q_dot_l.setToolTip(QCoreApplication.translate("MainWindow", u"Fire total heat release rate.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_Q_dot_or_Q_dot_l.setStatusTip(QCoreApplication.translate("MainWindow", u"Fire total heat release rate.", None))
#endif // QT_CONFIG(statustip)
        self.label_Q_dot_or_Q_dot_l.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Q<span style=\" vertical-align:super;\">`</span>, total heat release rate</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_35.setToolTip(QCoreApplication.translate("MainWindow", u"Ambient air density.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_35.setStatusTip(QCoreApplication.translate("MainWindow", u"Ambient air density.", None))
#endif // QT_CONFIG(statustip)
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u03c1<span style=\" vertical-align:sub;\">0</span>, ambient air density</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_rho_0.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_rho_0.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_rho_0.setText(QCoreApplication.translate("MainWindow", u"1.2", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"kg/m<sup>3<sup>", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_g.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_g.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_g.setText(QCoreApplication.translate("MainWindow", u"9.81", None))
        self.label_unit_S_or_UA_2.setText(QCoreApplication.translate("MainWindow", u"m/s<sup>2<sup>", None))
#if QT_CONFIG(tooltip)
        self.label_28.setToolTip(QCoreApplication.translate("MainWindow", u"Gravity.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_28.setStatusTip(QCoreApplication.translate("MainWindow", u"Gravity.", None))
#endif // QT_CONFIG(statustip)
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"g, gravity", None))
#if QT_CONFIG(tooltip)
        self.label_L_B.setToolTip(QCoreApplication.translate("MainWindow", u"Fire dimension 2.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_L_B.setStatusTip(QCoreApplication.translate("MainWindow", u"Fire dimension 2.", None))
#endif // QT_CONFIG(statustip)
        self.label_L_B.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L<span style=\" vertical-align:sub;\">B</span>, fire shorter dimension</p></body></html>", None))
        self.label_L_B_unit.setText(QCoreApplication.translate("MainWindow", u"m", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_L_B.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_L_B.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
        self.label_unit_S_or_UA.setText(QCoreApplication.translate("MainWindow", u"K", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_T_0.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_T_0.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_T_0.setText(QCoreApplication.translate("MainWindow", u"293.15", None))
#if QT_CONFIG(tooltip)
        self.label_27.setToolTip(QCoreApplication.translate("MainWindow", u"Ambient air temperature.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_27.setStatusTip(QCoreApplication.translate("MainWindow", u"Ambient air temperature.", None))
#endif // QT_CONFIG(statustip)
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>T<span style=\" vertical-align:sub;\">0</span>, ambient air temperature</p></body></html>", None))
        self.groupBox_outputs.setTitle(QCoreApplication.translate("MainWindow", u"Outputs", None))
#if QT_CONFIG(tooltip)
        self.label_out_Q_dot_star.setToolTip(QCoreApplication.translate("MainWindow", u"Solved dimensionless heat release rate.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_Q_dot_star.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved dimensionless heat release rate.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_Q_dot_star.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Q`<span style=\" vertical-align:super;\">*</span>, dimensionless HRR</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_out_Z_f.setToolTip(QCoreApplication.translate("MainWindow", u"Solved flame height.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_Z_f.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved flame height.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_Z_f.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Z<span style=\" vertical-align:sub;\">f</span>, flame height</p></body></html>", None))
        self.label_out_Z_f_unit.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.groupBox_options.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.comboBox_fire_shape.setItemText(0, QCoreApplication.translate("MainWindow", u"Circular", None))
        self.comboBox_fire_shape.setItemText(1, QCoreApplication.translate("MainWindow", u"Rectangular", None))
        self.comboBox_fire_shape.setItemText(2, QCoreApplication.translate("MainWindow", u"Line", None))

#if QT_CONFIG(tooltip)
        self.label_29.setToolTip(QCoreApplication.translate("MainWindow", u"Fire shape.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_29.setStatusTip(QCoreApplication.translate("MainWindow", u"Fire shape.", None))
#endif // QT_CONFIG(statustip)
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Fire Shape", None))
        self.comboBox_fuel_type.setItemText(0, QCoreApplication.translate("MainWindow", u"Natural gas (Zukoski)", None))
        self.comboBox_fuel_type.setItemText(1, QCoreApplication.translate("MainWindow", u"Wood cribs (Thomas)", None))
        self.comboBox_fuel_type.setItemText(2, QCoreApplication.translate("MainWindow", u"Gas, liquids and solids (Heskestad)", None))

#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("MainWindow", u"Fuel type, this dictates the correlation that will be used for the calculation.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_24.setStatusTip(QCoreApplication.translate("MainWindow", u"Fuel type, this dictates the correlation that will be used for the calculation.", None))
#endif // QT_CONFIG(statustip)
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Fuel Type", None))
        self.label_image_figure.setText("")
    # retranslateUi

