[tool.poetry]
name = "tractordriver"
version = "0.1.1"
description = "TractorDriver is a python base end-to-end test framework for Angular and AngularJS applications."
authors = ["Pargev Ghazaryan <pargev.ghazarian@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
APPLICATION-NAME = 'entry:main'
