[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython>=0.29.14",
    "numpy==1.14.5; python_version=='3.5'",
    "numpy==1.14.5; python_version=='3.6'",
    "numpy==1.16.1; python_version=='3.7'",
    "numpy==1.17.5; python_version>='3.8'",
    "scipy>=1.0",
]
