[tool.poetry]
name = "datatosk"
version = "0.1.3"
description = ""
authors = ["Miłosz Bednarzak <milosz.bednarzak@bethink.pl>", "Kuba Karmiński <kuba.karminski@bethink.pl>"]

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "^1.3.13"
pandas = "^1.0.1"
pandas-gbq = "^0.13.1"
bottleneck = "^1.3.2"
numexpr = "^2.7.1"
google-cloud-bigquery = "^1.24.0"
mysqlclient = "^1.4.6"
python-dotenv = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
