
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-05T08:42:45-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddd50905407a484b87ec33b207f59f345592b1a6",
 "version": "1.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
