# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_activitypub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.URLField()),
                ('public_key', models.TextField(blank=True, max_length=5000, null=True)),
                ('private_key', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'control'),
            },
        ),
    ]
