
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-02T15:20:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e0d2455c9f62a534f48df95946ddb94ee766d75",
 "version": "2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
