# Generated by Django 2.1.7 on 2019-03-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_category', '0006_auto_20190120_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort', 'pk'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
