
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T14:51:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "edaf29f88ec45147b628c1e7f905921dd885920a",
 "version": "0.2.12rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
