name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pyproj
  - matplotlib
  - intake
  - pip:
    - codecov
    - pytest-cov
    - black
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/numpy/numpy.git
    - git+https://github.com/pandas-dev/pandas.git
    - git+https://github.com/NCAR/intake-esm.git
    - git+https://github.com/xgcm/xgcm.git
