
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-21T11:26:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ddb014cd28f43c4207f04b41ed7f2599b8edf09",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
