[tool.poetry]
name = "foocatse"
version = "0.1.0"
description = "Python package that eases the pain concatenating Pandas categoricals!"
authors = ["SamEdwardes <edwardes.s@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.1"

[tool.poetry.dev-dependencies]
sphinx = "^2.4.3"
sphinxcontrib-napoleon = "^0.7"
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/legacy/"
default = true
