# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_issues', '0004_issuecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='proposal_field',
            field=models.TextField(blank=True, choices=[('name', 'Name'), ('definition', 'Definition'), ('references', 'References'), ('origin', 'Origin'), ('comments', 'Comments')]),
        ),
        migrations.AddField(
            model_name='issue',
            name='proposal_value',
            field=models.TextField(blank=True),
        ),
    ]
