
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-24T15:26:53+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d5f8144949d681c95165dafa531b83c528a87e7",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
