[tool.poetry]
name = "dicto"
version = "0.1.0"
description = ""
authors = ["Cristian Garcia <cgarcia.e88@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cgarciae/dicto"
homepage = "https://cgarciae.github.io/dicto"

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
