# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_review_requests', '0004_auto_20181205_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewendorsementtimeline',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='requester',
            field=models.ForeignKey(help_text='The user requesting a review', on_delete=django.db.models.deletion.PROTECT, related_name='rr_requested_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='workgroup',
            field=models.ForeignKey(help_text='A workgroup associated with this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rr_workgroup_reviews', to='aristotle_mdr.Workgroup'),
        ),
        migrations.AlterField(
            model_name='reviewstatuschangetimeline',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
