# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- job:
    name: keystone-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/keystone-dsvm-functional/run.yaml
    post-run: playbooks/legacy/keystone-dsvm-functional/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/keystone
      - openstack/keystone-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^keystone/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: keystone-dsvm-functional-v3-only
    parent: legacy-dsvm-base
    run: playbooks/legacy/keystone-dsvm-functional-v3-only/run.yaml
    post-run: playbooks/legacy/keystone-dsvm-functional-v3-only/post.yaml
    timeout: 4200
    voting: false
    required-projects:
      - openstack/devstack-gate
      - openstack/keystone
      - openstack/keystone-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^keystone/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: keystone-dsvm-py35-functional-v3-only
    parent: legacy-dsvm-base
    run: playbooks/legacy/keystone-dsvm-py35-functional-v3-only/run.yaml
    post-run: playbooks/legacy/keystone-dsvm-py35-functional-v3-only/post.yaml
    timeout: 4200
    voting: false
    required-projects:
      - openstack/devstack-gate
      - openstack/keystone
      - openstack/keystone-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^keystone/tests/unit/.*$
      - ^releasenotes/.*$

- job:
    name: openstack-tox-cover-keystone-xenial
    parent: openstack-tox-cover
    nodeset: openstack-single-node-xenial

# This job will execute 'tox -e upgrade' from the OSA
# repo specified in 'osa_test_repo'.
- job:
    name: openstack-ansible-keystone-rolling-upgrade
    parent: openstack-ansible-cross-repo-functional
    voting: false
    required-projects:
      - name: openstack/openstack-ansible-os_keystone
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^keystone/tests/unit/.*$
      - ^releasenotes/.*$
    vars:
      tox_env: upgrade
      osa_test_repo: openstack/openstack-ansible-os_keystone

- job:
    name: keystone-dsvm-ldap-domain-specific-driver
    parent: devstack-tempest
    vars:
      devstack_localrc:
        KEYSTONE_CLEAR_LDAP: 'yes'
        LDAP_PASSWORD: 'nomoresecret'
        USE_PYTHON3: True
      devstack_services:
        ldap: true

# Experimental
- job:
    name: keystone-tox-patch_cover
    parent: openstack-tox
    description: |
      Run test for keystone project.

      Uses tox with the ``patch_cover`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^keystone/tests/unit/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: patch_cover

# Experimental
- job:
    name: keystone-dsvm-grenade-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/keystone-dsvm-grenade-multinode/run.yaml
    post-run: playbooks/legacy/keystone-dsvm-grenade-multinode/post.yaml
    timeout: 10800
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^keystone/tests/unit/.*$
      - ^releasenotes/.*$
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/keystone
    nodeset: legacy-ubuntu-xenial-2-node

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - integrated-gate
      - integrated-gate-py35
      - release-notes-jobs
    check:
      jobs:
        - keystone-dsvm-functional
        - keystone-dsvm-functional-v3-only
        - keystone-dsvm-py35-functional-v3-only
        - openstack-tox-lower-constraints
        - legacy-keystoneclient-dsvm-functional:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
        - openstack-tox-cover-keystone-xenial
        - keystone-dsvm-ldap-domain-specific-driver:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - tempest-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
    gate:
      jobs:
        - keystone-dsvm-functional
        - openstack-tox-lower-constraints
        - tempest-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
    experimental:
      jobs:
        - keystone-tox-patch_cover
        - keystone-dsvm-grenade-multinode
        - openstack-ansible-keystone-rolling-upgrade
        - legacy-tempest-dsvm-neutron-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^etc/.*$
              - ^keystone/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
