[tool.poetry]
name = "ehealthkd"
version = "0.2.2"
description = "Evaluation scripts and tools for eHealth-KD"
authors = ["eHealth-KD"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
