__title__ = 'apiautotest'
__description__ = 'One-stop solution for HTTP(S) testing.'
__url__ = 'https://github.com/idibmzjm/apiautotest'
__version__ = '1.3.7'
__author__ = 'jimmy.zhangjm'
__author_email__ = '547980561@qq.com'
__license__ = 'Apache-2.0'
__copyright__ = 'Copyright 2017'
