# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:06
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aristotle_mdr', '0039_auto_20180828_1926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the item was viewed')),
                ('concept', aristotle_mdr.fields.ConceptForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_view_history', to='aristotle_mdr._concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_metadata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
