# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_favourites', '0004_auto_20180913_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='aristotle_mdr.PossumProfile'),
        ),
    ]
