[tool.poetry]
name = "mlbase"
version = "0.1.0"
description = ""
authors = ["Zhen Zhang <git@zhen-zhang.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.18.1"
pandas = "^1.0.1"
matplotlib = "^3.1.3"
seaborn = "^0.10.0"
ipython = "^7.13.0"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
