# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_user_management', '0003_auto_20180820_0248'),
        ('aristotle_mdr', '0061_auto_20190503_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm_view_all_metadata',
            field=models.BooleanField(default=False, help_text='Enable this to allow a user to see all metadata stored in the registry', verbose_name='Allow user to view all metadata'),
        ),
    ]
