[tool.poetry]
name = "pdf-preview"
version = "0.1.0"
description = ""
authors = ["kkzk <shohachi.kakizaki@gmail.com>"]
include = ["pdf_preview/pdfjs-dist"]
classifiers = [
    "Operating System :: Microsoft :: Windows"
    ]

[tool.poetry.dependencies]
python = "3.8"
PySide2 = "^5.14.1"
openpyxl = "^3.0.3"
PyPDF2 = "^1.26.0"
pywin32 = {version = "^227", platform = "windows"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
