dist: xenial
language: python
matrix:
  include: 
  - python: 3.7
    env: NOX_SESSION="mypy flake8 black"
  - python: 3.7
    env: NOX_SESSION="tests-3.7"
  - python: 3.6
    env: NOX_SESSION="tests-3.6"
  - python: 3.7
    env: NOX_SESSION="cov"
install:
  - pip install nox
script:
  - nox -s $NOX_SESSION
