from enum import Enum

from ..lib.auto_repl import auto

class TokenTypes(Enum):
    ALL = auto()
    AND = auto()
    AT = auto()
    BEGIN = auto()
    DEFINE = auto()
    END = auto()
    EOF = auto()
    GET = auto()
    GROUP = auto()
    LITERAL_STRING = auto()
    LOCATION = auto()
    LOGICAL = auto()
    NAME = auto()
    NUMBER = auto()
    OFF = auto()
    ON = auto()
    OR = auto()
    POWER = auto()
    PAUSE = auto()
    RANGE = auto()
    RAW = auto()
    REGISTER = auto()
    SERIES = auto()
    SET = auto()
    SYNTAX_ERROR = auto()
    TIME_PATTERN = auto()
    UNITS = auto()
    UNKNOWN = auto()
    WITH = auto()
    WAIT = auto()
    ZONE = auto()
