dist: bionic
sudo: false
language: python
virtualenv:
  system_site_packages: false
addons:
  apt:
    update: true
matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  - os: windows
  include:
  - python: 3.5
    env: DISTRIB="ubuntu"
    before_install:
    - sudo apt-get install -y ninja-build build-essential nvidia-cuda-toolkit
  - python: 3.6
    before_install:
    - sudo apt-get install -y ninja-build build-essential nvidia-cuda-toolkit
  - python: 3.7
    before_install:
    - sudo apt-get install -y ninja-build build-essential nvidia-cuda-toolkit
  - python: 3.8
    before_install:
    - sudo apt-get install -y ninja-build build-essential nvidia-cuda-toolkit
  - name: Python 3.7.2 on macOS
    os: osx
    osx_image: xcode11
    language: shell
    before_install:
    - brew update && brew upgrade python
    - brew install ninja
    - alias python=python3
    - alias pip="python3 -m pip"
    - shopt -s expand_aliases
    before_cache:
    - brew cleanup
  - name: Python 3.7.3 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python
    - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
- source tests/travis_install.sh
- pip3 install torch
- pip3 install -e .
- pip3 install torch || echo "failed to install machine learning stuff"
before_script:
- git config --global user.email "stephan.seitz@fau.de"
- git config --global user.name "Stephan Seitz"
script:
- python setup.py bdist_wheel
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; codecov; fi
after_script:
- travis-cleanup
cache:
  pip: true
  directories:
  - "$HOME/miniconda"
  - "/c/Python37"
  - "$HOME/Library/Caches/Homebrew"
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: InaJRipNoDcgiYlaQpkNangz4GX0j56z3jP9WYV+mphq6GOZnPDh4d9UikWiFnBpr9i6Q5+Rn6YJTLfohcqLfJEkoCVLSQ3Elie0gsZ0HQYnw1PIHa7mvgTgAcMigFghL1pMY/ELopR9+/AVg7l5PxCxWBnsgZn6LkUPFClly8nlKm/I1Mmb764EzJWx7o+SesmSxt5av0jGbfVPs6MQ/yB8mb1LuX/FHJ1D1FmnCgU6/CdpiwPE1gcfawMjQClBR11eTyN1d0GoLKOuV6l6rEI2b18eNW85t7aNl8Daqhwk+X4iMce/E1oUjVI8e8C3bztm4nuY/RpxccFnpP/hzdIng67GFyOQNDC//JmZkeO0BeA6gqJ8PG+HH/wboviE13ROVmwkxl1mNrovor6ucLo6OqWkh9nqnGhCisRigbO5UVVU9UKmQLLeB3Mrn819TbWXj2cOpHsxrDxqYRoBPNKtKa58PqCXzGtJZn/LrL/Ki4ioHcKAuc7jVSV55Giro1HdH0glLI7A9tg1QUhVHpMs6cq/l9xf+6Ifa6nCwCamrpwQCZhyRaqsyn9KaxTnmaNtM9Sj/HugMB/F91b729IVxrZ4H7Dg5sdVS1+ZY7gC+mBJLs0M+ILa7y/3erKKs21GA7yTPKfTszflB5q8jcBDcjP1sjjdokSigyZ689o=
  on:
    tags: true
  distributions: "bdist_wheel"
