---
image: python:latest

variables:
  PIP_CACHE: ${CI_PROJECT_DIR}/pip_cache
cache:
  paths:
    - ${CI_PROJECT_DIR}/pip_cache
  key: ${CI_PROJECT_ID}

services:
  - docker:dind

stages:
  - test

# before_script:
#   - apt-get update && apt-get install make
#   - python3 --version

pylint:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install --upgrade pylint pylint-exit anybadge
    - mkdir ./pylint
    - cd ./module && pylint *  -f parseable --ignore-imports=yes --output-format=text . | tee ../pylint/pylint.log || pylint-exit $? && cd -
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/

code_quality:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install --upgrade mypy
    - mypy --strict module/main/piphyperd.py
    - mypy --strict module/cli/cmdproxy.py
    - mypy --strict module/cli/parser.py

coverage:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install codecov
    - pip3 install yarl==1.1.0
    - coverage run -m module.tests.unit
    - coverage report -m

.pipelinesetup:
  before_script:
    - mkdir -p $PIP_CACHE
    - pip3 install --upgrade pip virtualenv