[tool.poetry]
name = "notate"
version = "0.1.0"
description = "Note generation scripts for note-taking with Notable."
authors = ["David Cabinian <dhcabinian@gmail.com>"]
license = "MIT"
readme = "README.rst"
keywords = ["notable"]
packages = [
    { include = "notate"},
]

[tool.poetry.dependencies]
python = "^3.7"
PyInquirer = "^1.0.3"
pendulum = "^2.0.5"
icalendar = "^4.0.4"
youtube_dl = "^2020.2.16"
pdfkit = "^0.6.1"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[tool.poetry.scripts]
notate = 'notate.take_note:take_note'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
