# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 02:48
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_user_management', '0002_lowercase_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=aristotle_mdr.fields.LowerEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
