[tool.poetry]
name = "colins"
version = "0.0.1b1"
description = ""
authors = ["joyongjin <wnrhd114@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/joyongjin/colins"
repository = "https://github.com/joyongjin/colins"

[tool.poetry.dependencies]
python = "^3.5"
yarl = "^1.4.2"
beautifulsoup4 = "^4.8.2"
pendulum = "^2.0.5"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
