# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"find_model": "00_core.ipynb",
         "get_row": "00_core.ipynb",
         "supported_models": "00_core.ipynb",
         "get_inp_sz": "00_core.ipynb",
         "infos_to_gen": "00_core.ipynb",
         "CNDF": "00_core.ipynb",
         "get_layer": "00_core.ipynb",
         "convnav_supported_models": "01_navigator.ipynb",
         "cndf_view": "01_navigator.ipynb",
         "add_container_row_info": "01_navigator.ipynb",
         "cndf_search": "01_navigator.ipynb",
         "ConvNav": "01_navigator.ipynb",
         "cndf_save": "01_navigator.ipynb",
         "cndf_load": "01_navigator.ipynb",
         "vgg": "02_models.ipynb",
         "alexnet": "02_models.ipynb",
         "squeezenet": "02_models.ipynb",
         "resnet": "02_models.ipynb",
         "densenet": "02_models.ipynb",
         "xresnet": "02_models.ipynb",
         "models": "02_models.ipynb"}

modules = ["core.py",
           "navigator.py",
           "models.py"]

doc_url = "https://hallmx.github.io/fa_convnav/"

git_url = "https://github.com/hallmx/fa_convnav/tree/master/"

def custom_doc_links(name): return None
