# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_answer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_answer',
            field=models.BooleanField(default=False),
        ),
    ]
