
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T13:37:55-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d8fd9412e7a0f83dcf1504cf60ca9aff957bd7e",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
