- project:
    templates:
      - check-requirements
      - publish-openstack-sphinx-docs
      - openstack-python-jobs
      - openstack-python35-jobs
      - lib-forward-testing
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-tempest-dsvm-full-ceph-plugin-src-os-brick:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-full-lio-src-os-brick:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-tempest-dsvm-full-lio-src-os-brick:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    experimental:
      jobs:
        - openstack-tox-pylint
