
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-03T22:21:05-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d818998a7cc2a2ffd12d404077bf9bdfaa98c4b4",
 "version": "0.5.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
