from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 320)
        Dialog.setMinimumSize(QtCore.QSize(470, 320))
        Dialog.setMaximumSize(QtCore.QSize(470, 320))
        Dialog.setSizeIncrement(QtCore.QSize(470, 320))
        Dialog.setBaseSize(QtCore.QSize(470, 320))
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 450, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(450, 300))
        self.tabWidget.setMaximumSize(QtCore.QSize(450, 300))
        self.tabWidget.setBaseSize(QtCore.QSize(450, 300))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.button_xUp = QtWidgets.QPushButton(self.widget)
        self.button_xUp.setGeometry(QtCore.QRect(20, 10, 51, 31))
        self.button_xUp.setObjectName("button_xUp")
        self.label_move_step = QtWidgets.QLabel(self.widget)
        self.label_move_step.setGeometry(QtCore.QRect(20, 160, 81, 16))
        self.label_move_step.setObjectName("label_move_step")
        self.label_rotation_step = QtWidgets.QLabel(self.widget)
        self.label_rotation_step.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.label_rotation_step.setObjectName("label_rotation_step")
        self.button_xDown = QtWidgets.QPushButton(self.widget)
        self.button_xDown.setGeometry(QtCore.QRect(20, 50, 51, 31))
        self.button_xDown.setObjectName("button_xDown")
        self.button_yDown = QtWidgets.QPushButton(self.widget)
        self.button_yDown.setGeometry(QtCore.QRect(90, 50, 51, 31))
        self.button_yDown.setObjectName("button_yDown")
        self.button_yUp = QtWidgets.QPushButton(self.widget)
        self.button_yUp.setGeometry(QtCore.QRect(90, 10, 51, 31))
        self.button_yUp.setObjectName("button_yUp")
        self.button_zDown = QtWidgets.QPushButton(self.widget)
        self.button_zDown.setGeometry(QtCore.QRect(160, 50, 51, 31))
        self.button_zDown.setObjectName("button_zDown")
        self.button_zUp = QtWidgets.QPushButton(self.widget)
        self.button_zUp.setGeometry(QtCore.QRect(160, 10, 51, 31))
        self.button_zUp.setObjectName("button_zUp")
        self.button_rollUp = QtWidgets.QPushButton(self.widget)
        self.button_rollUp.setGeometry(QtCore.QRect(230, 10, 51, 31))
        self.button_rollUp.setObjectName("button_rollUp")
        self.button_rollDown = QtWidgets.QPushButton(self.widget)
        self.button_rollDown.setGeometry(QtCore.QRect(230, 50, 51, 31))
        self.button_rollDown.setObjectName("button_rollDown")
        self.button_pitchDown = QtWidgets.QPushButton(self.widget)
        self.button_pitchDown.setGeometry(QtCore.QRect(300, 50, 51, 31))
        self.button_pitchDown.setObjectName("button_pitchDown")
        self.button_pitchUp = QtWidgets.QPushButton(self.widget)
        self.button_pitchUp.setGeometry(QtCore.QRect(300, 10, 51, 31))
        self.button_pitchUp.setObjectName("button_pitchUp")
        self.button_yawDown = QtWidgets.QPushButton(self.widget)
        self.button_yawDown.setGeometry(QtCore.QRect(370, 50, 51, 31))
        self.button_yawDown.setObjectName("button_yawDown")
        self.button_yawUp = QtWidgets.QPushButton(self.widget)
        self.button_yawUp.setGeometry(QtCore.QRect(370, 10, 51, 31))
        self.button_yawUp.setObjectName("button_yawUp")
        self.spinBox_move_step = QtWidgets.QSpinBox(self.widget)
        self.spinBox_move_step.setEnabled(False)
        self.spinBox_move_step.setGeometry(QtCore.QRect(140, 160, 61, 22))
        self.spinBox_move_step.setToolTipDuration(-1)
        self.spinBox_move_step.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_move_step.setMinimum(1)
        self.spinBox_move_step.setMaximum(1000)
        self.spinBox_move_step.setSingleStep(1)
        self.spinBox_move_step.setDisplayIntegerBase(10)
        self.spinBox_move_step.setObjectName("spinBox_move_step")
        self.spinBox_rotation_step = QtWidgets.QSpinBox(self.widget)
        self.spinBox_rotation_step.setEnabled(False)
        self.spinBox_rotation_step.setGeometry(QtCore.QRect(140, 190, 61, 22))
        self.spinBox_rotation_step.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_rotation_step.setMinimum(1)
        self.spinBox_rotation_step.setMaximum(90)
        self.spinBox_rotation_step.setObjectName("spinBox_rotation_step")
        self.label_x = QtWidgets.QLabel(self.widget)
        self.label_x.setGeometry(QtCore.QRect(30, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.lineEdit_x = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_x.setGeometry(QtCore.QRect(90, 90, 51, 20))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.lineEdit_roll = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_roll.setGeometry(QtCore.QRect(90, 120, 51, 20))
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.lineEdit_y = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_y.setGeometry(QtCore.QRect(230, 90, 51, 20))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_pitch.setGeometry(QtCore.QRect(230, 120, 51, 20))
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.lineEdit_z = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_z.setGeometry(QtCore.QRect(370, 90, 51, 20))
        self.lineEdit_z.setObjectName("lineEdit_z")
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_yaw.setGeometry(QtCore.QRect(370, 120, 51, 20))
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.label_roll = QtWidgets.QLabel(self.widget)
        self.label_roll.setGeometry(QtCore.QRect(30, 120, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_roll.setFont(font)
        self.label_roll.setObjectName("label_roll")
        self.label_y = QtWidgets.QLabel(self.widget)
        self.label_y.setGeometry(QtCore.QRect(180, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")
        self.label_pitch = QtWidgets.QLabel(self.widget)
        self.label_pitch.setGeometry(QtCore.QRect(170, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_pitch.setFont(font)
        self.label_pitch.setObjectName("label_pitch")
        self.label_z = QtWidgets.QLabel(self.widget)
        self.label_z.setGeometry(QtCore.QRect(320, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_z.setFont(font)
        self.label_z.setObjectName("label_z")
        self.label_yaw = QtWidgets.QLabel(self.widget)
        self.label_yaw.setGeometry(QtCore.QRect(310, 120, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_yaw.setFont(font)
        self.label_yaw.setObjectName("label_yaw")
        self.button_get_position = QtWidgets.QPushButton(self.widget)
        self.button_get_position.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.button_get_position.setObjectName("button_get_position")
        self.button_get_pose = QtWidgets.QPushButton(self.widget)
        self.button_get_pose.setGeometry(QtCore.QRect(350, 200, 75, 23))
        self.button_get_pose.setObjectName("button_get_pose")
        self.horizontalSlider_speed = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_speed.setGeometry(QtCore.QRect(20, 240, 401, 22))
        self.horizontalSlider_speed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_speed.setMinimum(1)
        self.horizontalSlider_speed.setMaximum(100)
        self.horizontalSlider_speed.setSliderPosition(5)
        self.horizontalSlider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_speed.setInvertedAppearance(False)
        self.horizontalSlider_speed.setInvertedControls(False)
        self.horizontalSlider_speed.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_speed.setTickInterval(5)
        self.horizontalSlider_speed.setObjectName("horizontalSlider_speed")
        self.checkBox_moving = QtWidgets.QCheckBox(self.widget)
        self.checkBox_moving.setGeometry(QtCore.QRect(230, 160, 91, 17))
        self.checkBox_moving.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_moving.setObjectName("checkBox_moving")
        self.pushButton_rememberPoint = QtWidgets.QPushButton(self.widget)
        self.pushButton_rememberPoint.setGeometry(QtCore.QRect(350, 160, 75, 23))
        self.pushButton_rememberPoint.setObjectName("pushButton_rememberPoint")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_xUp.setText(_translate("Dialog", "X+"))
        self.label_move_step.setText(_translate("Dialog", "Move Step, mm"))
        self.label_rotation_step.setText(_translate("Dialog", "Rotation Step, deg"))
        self.button_xDown.setText(_translate("Dialog", "X-"))
        self.button_yDown.setText(_translate("Dialog", "Y-"))
        self.button_yUp.setText(_translate("Dialog", "Y+"))
        self.button_zDown.setText(_translate("Dialog", "Z-"))
        self.button_zUp.setText(_translate("Dialog", "Z+"))
        self.button_rollUp.setText(_translate("Dialog", "roll+"))
        self.button_rollDown.setText(_translate("Dialog", "roll-"))
        self.button_pitchDown.setText(_translate("Dialog", "pitch-"))
        self.button_pitchUp.setText(_translate("Dialog", "pitch+"))
        self.button_yawDown.setText(_translate("Dialog", "yaw-"))
        self.button_yawUp.setText(_translate("Dialog", "yaw+"))
        self.label_x.setText(_translate("Dialog", "X:"))
        self.label_roll.setText(_translate("Dialog", "roll:"))
        self.label_y.setText(_translate("Dialog", "Y:"))
        self.label_pitch.setText(_translate("Dialog", "pitch:"))
        self.label_z.setText(_translate("Dialog", "Z:"))
        self.label_yaw.setText(_translate("Dialog", "yaw:"))
        self.button_get_position.setText(_translate("Dialog", "Get Position"))
        self.button_get_pose.setText(_translate("Dialog", "Get Pose"))
        self.checkBox_moving.setText(_translate("Dialog", "Move by steps"))
        self.pushButton_rememberPoint.setText(_translate("Dialog", "Remember"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Dialog", "Cortesian"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Joints"))
