sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 || $TRAVIS_PYTHON_VERSION == 3.6 || $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install aiohttp==3.6.2 asynctest==0.13.0; fi
  - pip install -q pycodestyle==2.3.1
script:
  - pycodestyle .
  - python setup.py test
