# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 03:32
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0022_switch_to_concept_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiblevalue',
            name='meaning',
            field=aristotle_mdr.fields.ShortTextField(help_text="A textual designation of a value, where a relation to a Value meaning doesn't exist"),
        ),
        migrations.AlterField(
            model_name='permissiblevalue',
            name='value',
            field=aristotle_mdr.fields.ShortTextField(help_text='the actual value of the Value'),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='meaning',
            field=aristotle_mdr.fields.ShortTextField(help_text="A textual designation of a value, where a relation to a Value meaning doesn't exist"),
        ),
        migrations.AlterField(
            model_name='supplementaryvalue',
            name='value',
            field=aristotle_mdr.fields.ShortTextField(help_text='the actual value of the Value'),
        ),
    ]
