# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 02:32
from __future__ import unicode_literals

from django.db import migrations
from aristotle_mdr.utils.migrations import (move_field_to_slot,
                                            move_slot_to_field)


def add_slots(apps, schema_editor):
    move_field_to_slot(apps, schema_editor, 'short_name')


def reverse_add_slots(apps, schema_editor):
    move_slot_to_field(apps, schema_editor, 'short_name')


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0028_replace_old_ded_through'),
        ('aristotle_mdr_slots', '0006_auto_20180531_0337')
    ]

    operations = [
        migrations.RunPython(add_slots, reverse_add_slots),
        migrations.RemoveField(
            model_name='_concept',
            name='short_name',
        ),
    ]
