# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 17:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion

from aristotle_mdr.utils.migrations import (
    classproperty,
    StewardMigration
)


class Migration(StewardMigration):

    dependencies = [
        ('aristotle_mdr', '0048_auto_20181223_1134'),
    ]

    @classproperty
    def operations(cls):
        return [
            migrations.AlterField(
                model_name='registrationauthority',
                name='stewardship_organisation',
                field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
            migrations.AlterField(
                model_name='workgroup',
                name='stewardship_organisation',
                field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
            migrations.AlterField(
                model_name='measure',
                name='stewardship_organisation',
                field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='managed_items', to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
                preserve_default=False,
            ),
        ]
