# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 04:55
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_backwards', '0002_representationclass'),
        ('aristotle_mdr', '0050_auto_20190204_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuedomain',
            name='representation_class',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_domains', to='aristotle_mdr_backwards.RepresentationClass', verbose_name='Representation Class'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='stewardship_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.StewardOrganisation', to_field='uuid'),
        ),
    ]
