# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 10:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0055_auto_20190313_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='stewards',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='submitters',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='viewers',
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='workgroupmembership',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('steward', 'Steward'), ('submitter', 'Submitter'), ('viewer', 'Viewer')], help_text='Role within this group', max_length=128),
        ),
    ]
