# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 22:53
from __future__ import unicode_literals

from django.db import migrations
from aristotle_mdr.utils.migrations import CustomFieldMover


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0057_auto_20190329_1609'),
        ('aristotle_mdr_custom_fields', '0002_auto_20190212_1805'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        CustomFieldMover(
            app_label="aristotle_mdr",
            model_name="_concept",
            field_name="submitting_organisation",
            custom_field_name="Submitting Organisation",
            custom_field_type="html",
            custom_field_kwargs={"order": 0},
        ),
        CustomFieldMover(
            app_label="aristotle_mdr",
            model_name="_concept",
            field_name="responsible_organisation",
            custom_field_name="Responsible Organisation",
            custom_field_type="html",
            custom_field_kwargs={"order": 1},
        ),
    ]
