# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0064_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='_concept',
            name='_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='supersederelationship',
            name='proposed',
            field=models.BooleanField(default=False, help_text='Whether this is a proposal or an active supersedes relation'),
        ),
    ]
