# Generated by Django 2.2.4 on 2019-09-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0074_auto_20190908_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='changeDetails',
            field=models.TextField(blank=True, null=True, verbose_name='Change details'),
        ),
        migrations.AlterField(
            model_name='status',
            name='registrationDate',
            field=models.DateField(help_text='Date and time an Administered_Item became/becomes available to registry users.', verbose_name='Date registration effective'),
        ),
        migrations.AlterField(
            model_name='status',
            name='state',
            field=models.IntegerField(choices=[(0, 'Not Progressed'), (1, 'Incomplete'), (2, 'Candidate'), (3, 'Recorded'), (4, 'Qualified'), (5, 'Standard'), (6, 'Preferred Standard'), (7, 'Superseded'), (8, 'Retired')], default=1, help_text='Designation (3.2.51) of the status in the registration life-cycle of an Administered_Item', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='status',
            name='until_date',
            field=models.DateField(blank=True, help_text='Date and time the Registration of an Administered_Item by a Registration_Authority in a registry is no longer effective.', null=True, verbose_name='Date registration expires'),
        ),
    ]
