# Generated by Django 2.2.6 on 2019-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0075_auto_20190916_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organisation'},
        ),
        migrations.AlterModelOptions(
            name='organizationrecord',
            options={'verbose_name': 'Organisation Record'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='uri',
            field=models.URLField(blank=True, help_text='uri for Organisation', null=True),
        ),
        migrations.AlterField(
            model_name='recordrelation',
            name='type',
            field=models.CharField(choices=[('s', 'Submitting Organisation'), ('r', 'Responsible Organisation')], max_length=1),
        ),
    ]
