# coding: utf-8

"""
    Nomad Pilot

    This is the API descriptor for the Nomad Pilot API, responsible for shipping and logistics processing.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import nomad_pilot_cli
from nomad_pilot_cli.models.goldjet import Goldjet  # noqa: E501
from nomad_pilot_cli.rest import ApiException


class TestGoldjet(unittest.TestCase):
    """Goldjet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoldjet(self):
        """Test Goldjet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nomad_pilot_cli.models.goldjet.Goldjet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
