
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4fc0cfd4c20292e481a30e233cc70d27a3e5b5e0",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
