
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-06T02:20:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1fa7f911919c48cf4c67284e66bb90df6b2bffeb",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
