variables:
  build_num: $(Build.BuildNumber)
  
jobs:
- job: PyPi_Linux
  pool:
   vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      python -m pip install wheel twine
    displayName: 'Install wheel+twine'

  - script: |
      docker pull quay.io/pypa/manylinux1_x86_64
      docker build -t pybfms .
    displayName: 'Setup Docker Image'
    
  - script: |
      docker run -e BUILD_NUM=$(Build.BuildNumber) -v $(Build.Repository.LocalPath):/pybfms pybfms
    displayName: 'Build Wheel'
  - task: TwineAuthenticate@1
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      pythonUploadServiceConnection: pypi-pybfms
  - script: |
      # Only deploy from master
      if test "$(Build.SourceBranchName)" = "master"; then
          python -m twine --version
          echo "Calling twine"
          python -m twine upload -r pybfms --config-file $(PYPIRC_PATH) result/wheelhouse/* result/dist/*.tar.gz
          echo "Calling twine complete"
      fi
    displayName: 'Upload to PyPi'


