# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 05:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_links', '0003_auto_20170328_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='arity',
            field=models.PositiveIntegerField(help_text='number of elements in the relation', null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
