from polyproto.generators import GeometricGenerator, GeometricNGenerator
from polyproto.drawFunctions import drawRandomCircle, drawRandomEllipse,drawRandomLine, drawRandomPolygon, drawRandomRectangle