
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13.2'
version_full = '7f3c22f5d599fd19e89c290a5f1a4d88937d276b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

