[tool.poetry]
name = "odoo_backup"
version = "0.1.0"
description = ""
authors = ["Martin Lehoux <martin@lehoux.net>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
click = "^7.0"
humanize = "^1.0.0"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
