# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 03:27
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0003_auto_20171030_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='indicators',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='frameworks', to='comet.Indicator'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='parentFramework',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childFrameworks', to='comet.Framework'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='dataElementConcept',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.DataElementConcept', verbose_name='Data Element Concept'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='denominators',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='as_denominator', to='aristotle_mdr.DataElement'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='disaggregators',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='as_disaggregator', to='aristotle_mdr.DataElement'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicatorType',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comet.IndicatorType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='numerators',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='as_numerator', to='aristotle_mdr.DataElement'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='outcome_areas',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, related_name='indicators', to='comet.OutcomeArea'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='valueDomain',
            field=aristotle_mdr.fields.ConceptForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.ValueDomain', verbose_name='Value Domain'),
        ),
        migrations.AlterField(
            model_name='indicatorset',
            name='indicators',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, null=True, related_name='indicatorSets', to='comet.Indicator'),
        ),
    ]
