# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet', '0007_auto_20190218_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='denominators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='disaggregators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='numerators',
        ),
        migrations.RemoveField(
            model_name='indicatorset',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='indicatorType',
        ),
        migrations.RemoveField(
            model_name='indicatorset',
            name='indicatorSetType',
        ),
        migrations.DeleteModel(
            name='IndicatorTypeOld',
        ),
        migrations.DeleteModel(
            name='IndicatorSetTypeOld',
        ),
    ]
