version: "3.7"

services:
    app:
        build:
            context: .
            target: prod
        volumes:
            - ./data:/app/data
            - ./dist:/app/dist
            - ./src:/app
        environment:
            - VERSION=${VERSION}
