version: "2"
checks:
  argument-count:
    config:
      threshold: 14
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 65
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 180
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled : false
  identical-code:
    enabled: true
    config:
      threshold: 40
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/logic.py"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/ui/*.py"