[tool.poetry]
name = "poetry-demo-1"
version = "0.1.0"
description = ""
authors = ["cmejia <cmejia@kiusys.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pendulum = "^2.0.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
