
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T22:47:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b5594f54a22cc3779de39e0fd04a675b134453c",
 "version": "0.0.4a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
