[tool.poetry]
name = "phases"
version = "0.1.1"
description = "A Framework for creating a boilerplate template for ai projects that are ready for MLOps"
authors = ["fehrlich <fehrlichd@gmail.com>"]
license = "MIT"

readme = 'README.md'

repository = "https://gitlab.com/tud.ibmt/phases"
homepage = "https://gitlab.com/tud.ibmt/phases"

include = ["phases/generate-template"]
exclude = ["tests", "example"]

[tool.poetry.dependencies]
python = "^3.7"
docopt = "^0.6"
pyPhases = "^0.0"
PyYAML = "^5.3"
pystache = "^0.5"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
phases = "phases.cli:main"