
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T23:21:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0e3d959b84d108cf0c106db1131a03f6b2fbd8e",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
