
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-21T17:09:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc95a28d9c3e8fd0893c53e551a7ab4a9083a61c",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
