language: python
dist: xenial
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy2.7-6.0
    - pypy3.5-6.0
install:
    - pip install -U pip setuptools
    - pip install -U zope.testrunner coverage coveralls
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - coveralls
notifications:
    email: false
cache: pip
