
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T15:12:25-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1911d73bce2987306ae8bbcf3a682abe85fc0d87",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
