# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_favourites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='aristotle_mdr.PossumProfile'),
        ),
    ]
