# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_favourites', '0002_auto_20180904_0422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('tag', 'item')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('profile', 'name')]),
        ),
    ]
