# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-14 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_favourites', '0003_auto_20180907_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
