#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This script was generated by the clinterfacer framework.
It script defines the subparser used by the {command} commnad, 
which is available in the {package} command-line interface.
For more details, visit https://gitlab.com/adrianohrl/clinterfacer!
"""

# standard library(ies)
from argparse import _SubParsersAction, ArgumentParser, Namespace

# 3rd party package(s)
from clinterfacer import cli


def add_parser(subparsers: _SubParsersAction) -> None:
    parser = subparsers.add_parser(
        '{command}',
        help='This is the {command} command of the {package} command-line',
        prog='{package} {command}',
        description='This command is the {command} one.')
    add_arguments(parser)


def add_arguments(parser: ArgumentParser) -> None:
    pass


def parse_args() -> Namespace:
    parser = ArgumentParser()
    add_arguments(parser)
    args = parser.parse_args()
    cli.setup()
    return args
