connectors:
- configuration: opcua.json
  name: OPCUA
  type: opcua
storage:
  max_records_count: 10000
  read_records_count: 100
  type: memory
thingsboard:
  host: 192.168.1.100
  port: 1883
  remoteConfiguration: true
  security:
    accessToken: jkDf8kE9CH5qlYcSrLY1
