# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_deb
from pulpcore.client.pulp_deb.models.deb_package_index import DebPackageIndex  # noqa: E501
from pulpcore.client.pulp_deb.rest import ApiException


class TestDebPackageIndex(unittest.TestCase):
    """DebPackageIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDebPackageIndex(self):
        """Test DebPackageIndex"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulp_deb.models.deb_package_index.DebPackageIndex()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
