# Generated by Django 2.2.1 on 2019-06-18 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecomment',
            name='updated_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date/time updated'),
        ),
    ]
