# Generated by Django 2.2.1 on 2019-07-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0002_treecomment_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentassociation',
            name='object_pk',
        ),
    ]
