# Generated by Django 2.2.6 on 2019-10-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0004_auto_20190803_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecomment',
            name='assoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_comments_tree.CommentAssociation'),
        ),
    ]
