# Generated by Django 2.2.6 on 2019-10-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_tree', '0006_auto_20191023_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecomment',
            name='assoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_comments_tree.CommentAssociation'),
        ),
    ]
