# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(673, 479)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(673, 462))
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        MainWindow.setBaseSize(QtCore.QSize(640, 390))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 157, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 157, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 157, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_ack = QtWidgets.QPushButton(self.centralwidget)
        self.button_ack.setObjectName("button_ack")
        self.gridLayout_3.addWidget(self.button_ack, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.button_documentation = QtWidgets.QPushButton(self.centralwidget)
        self.button_documentation.setObjectName("button_documentation")
        self.gridLayout_3.addWidget(self.button_documentation, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.tabWidget.setMaximumSize(QtCore.QSize(9999, 236))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 157, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 157, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 157, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 118, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setToolTip("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_CL = QtWidgets.QWidget()
        self.tab_CL.setObjectName("tab_CL")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_CL)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_encoding_CL = QtWidgets.QLabel(self.tab_CL)
        self.label_encoding_CL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_encoding_CL.setObjectName("label_encoding_CL")
        self.gridLayout.addWidget(self.label_encoding_CL, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.button_generate_CL = QtWidgets.QPushButton(self.tab_CL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_generate_CL.sizePolicy().hasHeightForWidth())
        self.button_generate_CL.setSizePolicy(sizePolicy)
        self.button_generate_CL.setMaximumSize(QtCore.QSize(283, 23))
        self.button_generate_CL.setObjectName("button_generate_CL")
        self.gridLayout.addWidget(self.button_generate_CL, 8, 3, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 3, 1, 1)
        self.line_treatment_CL = QtWidgets.QLineEdit(self.tab_CL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_treatment_CL.sizePolicy().hasHeightForWidth())
        self.line_treatment_CL.setSizePolicy(sizePolicy)
        self.line_treatment_CL.setMinimumSize(QtCore.QSize(286, 25))
        self.line_treatment_CL.setMaximumSize(QtCore.QSize(286, 25))
        self.line_treatment_CL.setText("")
        self.line_treatment_CL.setObjectName("line_treatment_CL")
        self.gridLayout.addWidget(self.line_treatment_CL, 4, 3, 1, 2)
        self.label_load_treatment_CL = QtWidgets.QLabel(self.tab_CL)
        self.label_load_treatment_CL.setMaximumSize(QtCore.QSize(99999, 33))
        self.label_load_treatment_CL.setObjectName("label_load_treatment_CL")
        self.gridLayout.addWidget(self.label_load_treatment_CL, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 8, 1, 1)
        self.button_treatment_CL = QtWidgets.QPushButton(self.tab_CL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_treatment_CL.sizePolicy().hasHeightForWidth())
        self.button_treatment_CL.setSizePolicy(sizePolicy)
        self.button_treatment_CL.setMinimumSize(QtCore.QSize(80, 25))
        self.button_treatment_CL.setMaximumSize(QtCore.QSize(80, 25))
        self.button_treatment_CL.setObjectName("button_treatment_CL")
        self.gridLayout.addWidget(self.button_treatment_CL, 4, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 7, 3, 1, 1)
        self.combo_encoding_CL = QtWidgets.QComboBox(self.tab_CL)
        self.combo_encoding_CL.setObjectName("combo_encoding_CL")
        self.gridLayout.addWidget(self.combo_encoding_CL, 6, 3, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 3, 1, 1, 1)
        self.label_description_CL = QtWidgets.QLabel(self.tab_CL)
        self.label_description_CL.setWordWrap(True)
        self.label_description_CL.setObjectName("label_description_CL")
        self.gridLayout.addWidget(self.label_description_CL, 1, 1, 1, 5)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_CL, "")
        self.tab_IL = QtWidgets.QWidget()
        self.tab_IL.setObjectName("tab_IL")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_IL)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_encoding_output_IL = QtWidgets.QLabel(self.tab_IL)
        self.label_encoding_output_IL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_encoding_output_IL.setObjectName("label_encoding_output_IL")
        self.gridLayout_2.addWidget(self.label_encoding_output_IL, 15, 1, 1, 1)
        self.label_encoding_input_IL = QtWidgets.QLabel(self.tab_IL)
        self.label_encoding_input_IL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_encoding_input_IL.setObjectName("label_encoding_input_IL")
        self.gridLayout_2.addWidget(self.label_encoding_input_IL, 6, 1, 1, 1)
        self.combo_encoding_input_IL = QtWidgets.QComboBox(self.tab_IL)
        self.combo_encoding_input_IL.setObjectName("combo_encoding_input_IL")
        self.gridLayout_2.addWidget(self.combo_encoding_input_IL, 6, 3, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem9, 4, 3, 1, 1)
        self.combo_encoding_output_IL = QtWidgets.QComboBox(self.tab_IL)
        self.combo_encoding_output_IL.setObjectName("combo_encoding_output_IL")
        self.gridLayout_2.addWidget(self.combo_encoding_output_IL, 15, 3, 1, 2)
        self.line_language_IL = QtWidgets.QLineEdit(self.tab_IL)
        self.line_language_IL.setObjectName("line_language_IL")
        self.gridLayout_2.addWidget(self.line_language_IL, 8, 3, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem10, 9, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem11, 13, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 3, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem13, 0, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem14, 16, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem15, 18, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 3, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 5, 3, 1, 1)
        self.line_treatment_IL = QtWidgets.QLineEdit(self.tab_IL)
        self.line_treatment_IL.setObjectName("line_treatment_IL")
        self.gridLayout_2.addWidget(self.line_treatment_IL, 3, 3, 1, 2)
        self.label_load_language_IL = QtWidgets.QLabel(self.tab_IL)
        self.label_load_language_IL.setObjectName("label_load_language_IL")
        self.gridLayout_2.addWidget(self.label_load_language_IL, 8, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem18, 7, 3, 1, 1)
        self.button_generate_IL = QtWidgets.QPushButton(self.tab_IL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_generate_IL.sizePolicy().hasHeightForWidth())
        self.button_generate_IL.setSizePolicy(sizePolicy)
        self.button_generate_IL.setMinimumSize(QtCore.QSize(283, 23))
        self.button_generate_IL.setObjectName("button_generate_IL")
        self.gridLayout_2.addWidget(self.button_generate_IL, 17, 3, 1, 2)
        self.button_language_IL = QtWidgets.QPushButton(self.tab_IL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_language_IL.sizePolicy().hasHeightForWidth())
        self.button_language_IL.setSizePolicy(sizePolicy)
        self.button_language_IL.setObjectName("button_language_IL")
        self.gridLayout_2.addWidget(self.button_language_IL, 8, 5, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 3, 6, 1, 1)
        self.label_load_treatment_IL = QtWidgets.QLabel(self.tab_IL)
        self.label_load_treatment_IL.setObjectName("label_load_treatment_IL")
        self.gridLayout_2.addWidget(self.label_load_treatment_IL, 3, 1, 1, 1)
        self.check_strip_unmatched = QtWidgets.QCheckBox(self.tab_IL)
        self.check_strip_unmatched.setObjectName("check_strip_unmatched")
        self.gridLayout_2.addWidget(self.check_strip_unmatched, 12, 3, 1, 2)
        self.button_treatment_IL = QtWidgets.QPushButton(self.tab_IL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_treatment_IL.sizePolicy().hasHeightForWidth())
        self.button_treatment_IL.setSizePolicy(sizePolicy)
        self.button_treatment_IL.setObjectName("button_treatment_IL")
        self.gridLayout_2.addWidget(self.button_treatment_IL, 3, 5, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem20, 2, 3, 1, 1)
        self.label_description_IL = QtWidgets.QLabel(self.tab_IL)
        self.label_description_IL.setWordWrap(True)
        self.label_description_IL.setObjectName("label_description_IL")
        self.gridLayout_2.addWidget(self.label_description_IL, 1, 1, 1, 5)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_IL, "")
        self.tab_SB = QtWidgets.QWidget()
        self.tab_SB.setToolTip("")
        self.tab_SB.setObjectName("tab_SB")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_SB)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout2 = QtWidgets.QGridLayout()
        self.gridLayout2.setSpacing(0)
        self.gridLayout2.setObjectName("gridLayout2")
        self.button_generate_SB = QtWidgets.QPushButton(self.tab_SB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_generate_SB.sizePolicy().hasHeightForWidth())
        self.button_generate_SB.setSizePolicy(sizePolicy)
        self.button_generate_SB.setMaximumSize(QtCore.QSize(283, 23))
        self.button_generate_SB.setObjectName("button_generate_SB")
        self.gridLayout2.addWidget(self.button_generate_SB, 7, 3, 1, 3)
        spacerItem21 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout2.addItem(spacerItem21, 4, 3, 1, 1)
        self.line_treatment_SB = QtWidgets.QLineEdit(self.tab_SB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_treatment_SB.sizePolicy().hasHeightForWidth())
        self.line_treatment_SB.setSizePolicy(sizePolicy)
        self.line_treatment_SB.setMinimumSize(QtCore.QSize(286, 25))
        self.line_treatment_SB.setMaximumSize(QtCore.QSize(286, 25))
        self.line_treatment_SB.setText("")
        self.line_treatment_SB.setObjectName("line_treatment_SB")
        self.gridLayout2.addWidget(self.line_treatment_SB, 3, 3, 1, 2)
        self.label_load_treatment_SB = QtWidgets.QLabel(self.tab_SB)
        self.label_load_treatment_SB.setMaximumSize(QtCore.QSize(99999, 33))
        self.label_load_treatment_SB.setObjectName("label_load_treatment_SB")
        self.gridLayout2.addWidget(self.label_load_treatment_SB, 3, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout2.addItem(spacerItem22, 8, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout2.addItem(spacerItem23, 0, 3, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem24, 3, 8, 1, 1)
        self.button_treatment_SB = QtWidgets.QPushButton(self.tab_SB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_treatment_SB.sizePolicy().hasHeightForWidth())
        self.button_treatment_SB.setSizePolicy(sizePolicy)
        self.button_treatment_SB.setMinimumSize(QtCore.QSize(80, 25))
        self.button_treatment_SB.setMaximumSize(QtCore.QSize(80, 25))
        self.button_treatment_SB.setObjectName("button_treatment_SB")
        self.gridLayout2.addWidget(self.button_treatment_SB, 3, 5, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem25, 3, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem26, 3, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout2.addItem(spacerItem27, 6, 3, 1, 1)
        self.label_encoding_SB = QtWidgets.QLabel(self.tab_SB)
        self.label_encoding_SB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_encoding_SB.setObjectName("label_encoding_SB")
        self.gridLayout2.addWidget(self.label_encoding_SB, 5, 1, 1, 1)
        self.combo_encoding_SB = QtWidgets.QComboBox(self.tab_SB)
        self.combo_encoding_SB.setObjectName("combo_encoding_SB")
        self.gridLayout2.addWidget(self.combo_encoding_SB, 5, 3, 1, 2)
        self.label_description_SB = QtWidgets.QLabel(self.tab_SB)
        self.label_description_SB.setEnabled(True)
        self.label_description_SB.setWordWrap(True)
        self.label_description_SB.setObjectName("label_description_SB")
        self.gridLayout2.addWidget(self.label_description_SB, 1, 1, 2, 5)
        self.verticalLayout_22.addLayout(self.gridLayout2)
        self.tabWidget.addTab(self.tab_SB, "")
        self.gridLayout_3.addWidget(self.tabWidget, 6, 0, 1, 4)
        self.check_description = QtWidgets.QCheckBox(self.centralwidget)
        self.check_description.setObjectName("check_description")
        self.gridLayout_3.addWidget(self.check_description, 3, 1, 1, 1)
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMaximumSize(QtCore.QSize(125, 125))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/res/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.gridLayout_3.addWidget(self.Logo, 0, 1, 1, 1)
        self.text_console = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_console.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_console.sizePolicy().hasHeightForWidth())
        self.text_console.setSizePolicy(sizePolicy)
        self.text_console.setMaximumSize(QtCore.QSize(99999, 99999))
        self.text_console.setReadOnly(True)
        self.text_console.setObjectName("text_console")
        self.gridLayout_3.addWidget(self.text_console, 0, 3, 5, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.button_documentationold = QtWidgets.QAction(MainWindow)
        self.button_documentationold.setObjectName("button_documentationold")
        self.button_citation = QtWidgets.QAction(MainWindow)
        self.button_citation.setObjectName("button_citation")
        self.button_acko = QtWidgets.QAction(MainWindow)
        self.button_acko.setObjectName("button_acko")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "title"))
        self.button_ack.setToolTip(_translate("MainWindow", "<html><head/><body><p>Acknowledgements: Printed in the console</p></body></html>"))
        self.button_ack.setText(_translate("MainWindow", "Acknowledgments"))
        self.button_documentation.setToolTip(_translate("MainWindow", "<html><head/><body><p>Opens the project page on browser</p></body></html>"))
        self.button_documentation.setText(_translate("MainWindow", "Documentation"))
        self.label_encoding_CL.setToolTip(_translate("MainWindow", "<html><head/><body><p>Text File encoding. in zTree, different regional settings may lead to different encodings. Standard English zTree works with ISO-8859 family.</p></body></html>"))
        self.label_encoding_CL.setText(_translate("MainWindow", "Encoding:"))
        self.button_generate_CL.setText(_translate("MainWindow", "Save language file as..."))
        self.label_load_treatment_CL.setToolTip(_translate("MainWindow", "<html><head/><body><p>The treatment file in txt format exported by zTree. zBrac only recognizes the text in between [[ ]].</p></body></html>"))
        self.label_load_treatment_CL.setText(_translate("MainWindow", "Load treatment File:"))
        self.button_treatment_CL.setText(_translate("MainWindow", "Browse"))
        self.label_description_CL.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600;\">Creates a language file from an exported treatment file (txt). zBrac grabs the text that are wrapped in double brackets. Generated files can later be used for translation/text replacement.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_CL), _translate("MainWindow", "Create Language File Template"))
        self.label_encoding_output_IL.setToolTip(_translate("MainWindow", "<html><head/><body><p>Text File encoding.This should be set to an encoding that is compatible with the translation language.</p></body></html>"))
        self.label_encoding_output_IL.setText(_translate("MainWindow", "Output Encoding:"))
        self.label_encoding_input_IL.setToolTip(_translate("MainWindow", "<html><head/><body><p>Text File encoding. Different languages can output different encodings. Standard English zTree works with ISO-8859 family.</p></body></html>"))
        self.label_encoding_input_IL.setText(_translate("MainWindow", "Encoding:"))
        self.label_load_language_IL.setText(_translate("MainWindow", "Load language File:"))
        self.button_generate_IL.setText(_translate("MainWindow", "Save treatment file as..."))
        self.button_language_IL.setText(_translate("MainWindow", "Browse"))
        self.label_load_treatment_IL.setToolTip(_translate("MainWindow", "<html><head/><body><p>The treatment file in txt format exported by zTree. zBrac only recognizes the text in between [[ ]].</p></body></html>"))
        self.label_load_treatment_IL.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_load_treatment_IL.setText(_translate("MainWindow", "Load treatment File:"))
        self.check_strip_unmatched.setText(_translate("MainWindow", "Strip brackets of unmatched keywords"))
        self.button_treatment_IL.setText(_translate("MainWindow", "Browse"))
        self.label_description_IL.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600;\">Generates zTree treatment file from an exported zTree file(txt) and a language file (xlsx) in the target language.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_IL), _translate("MainWindow", "Implement Language File"))
        self.button_generate_SB.setText(_translate("MainWindow", "Save treatment file as..."))
        self.label_load_treatment_SB.setToolTip(_translate("MainWindow", "<html><head/><body><p>The treatment file in txt format exported by zTree. zBrac only recognizes the text in between [[ ]].</p></body></html>"))
        self.label_load_treatment_SB.setText(_translate("MainWindow", "Load treatment File:"))
        self.button_treatment_SB.setText(_translate("MainWindow", "Browse"))
        self.label_encoding_SB.setText(_translate("MainWindow", "Encoding:"))
        self.label_description_SB.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600;\">Removes double brackets from the file. You can use this option if your zTree file is already in the language you need. This option is useful if you are coding your zTree files with brackets by default and you would like to see how it looks without them.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SB), _translate("MainWindow", "Strip Brackets"))
        self.check_description.setText(_translate("MainWindow", "Show descriptions"))
        self.text_console.setPlainText(_translate("MainWindow", "console_text"))
        self.button_documentationold.setText(_translate("MainWindow", "Documentation"))
        self.button_citation.setText(_translate("MainWindow", "Citation Information"))
        self.button_acko.setText(_translate("MainWindow", "Acknowledgments"))

from . import resources_rc
