
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "branch": "rc/maintenance",
 "dirty": false,
 "error": null,
 "full-revisionid": "d99af420acb9d5b18a4f60f9cae8abb458e131d4",
 "version": "1.4.0rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
