# Generated by Django 2.2.4 on 2019-09-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_validators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravalidationrules',
            name='registration_authority',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.RegistrationAuthority'),
        ),
    ]
