# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_deb
from pulpcore.client.pulp_deb.models.inline_response20012 import InlineResponse20012  # noqa: E501
from pulpcore.client.pulp_deb.rest import ApiException


class TestInlineResponse20012(unittest.TestCase):
    """InlineResponse20012 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20012(self):
        """Test InlineResponse20012"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulp_deb.models.inline_response20012.InlineResponse20012()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
