[tool.poetry]
name = "fsorg"
version = "1.0.1"
description = "Create a directory structure by describing it"
authors = ["ewen-lbh <ewen.lebihan7@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
fsorg = 'fsorg.entry:main'

[tool.poetry.dependencies]
python = "^3.7"
rm = "^2019.4.13"
pyfiglet = "^0.8.post1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
