# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_bg_workers', '0001_squashed_0002_extrataskinfo_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrataskinfo',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
