[tool.poetry]
name = "ptera"
version = "0.1.0"
description = "Call graph addressing library."
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
isort = "^4.3.21"

[tool.black]
line-length = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
