
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-26T21:10:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ceae0bf5436b636c44e4042e4ab21ee27e52071f",
 "version": "v0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
