# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flowcell/frontend/flowcell.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 360)
        MainWindow.setMinimumSize(QtCore.QSize(640, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.autoconnectBox = QtWidgets.QCheckBox(self.frame)
        self.autoconnectBox.setObjectName("autoconnectBox")
        self.horizontalLayout.addWidget(self.autoconnectBox)
        spacerItem = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.macLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macLabel.sizePolicy().hasHeightForWidth())
        self.macLabel.setSizePolicy(sizePolicy)
        self.macLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.macLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.macLabel.setObjectName("macLabel")
        self.horizontalLayout.addWidget(self.macLabel)
        self.macBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macBox.sizePolicy().hasHeightForWidth())
        self.macBox.setSizePolicy(sizePolicy)
        self.macBox.setMinimumSize(QtCore.QSize(275, 0))
        self.macBox.setObjectName("macBox")
        self.horizontalLayout.addWidget(self.macBox)
        self.connectButton = QtWidgets.QPushButton(self.frame)
        self.connectButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.connectButton.setAutoDefault(True)
        self.connectButton.setDefault(False)
        self.connectButton.setFlat(False)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.consoleText = QtWidgets.QPlainTextEdit(self.tab)
        self.consoleText.setEnabled(False)
        self.consoleText.setReadOnly(True)
        self.consoleText.setObjectName("consoleText")
        self.verticalLayout_2.addWidget(self.consoleText)
        self.frame2 = QtWidgets.QFrame(self.tab)
        self.frame2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.sendLayout = QtWidgets.QHBoxLayout(self.frame2)
        self.sendLayout.setContentsMargins(0, 0, 0, 0)
        self.sendLayout.setObjectName("sendLayout")
        self.sendButton = QtWidgets.QPushButton(self.frame2)
        self.sendButton.setEnabled(False)
        self.sendButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sendButton.setAutoDefault(True)
        self.sendButton.setDefault(False)
        self.sendButton.setFlat(False)
        self.sendButton.setObjectName("sendButton")
        self.sendLayout.addWidget(self.sendButton)
        self.verticalLayout_2.addWidget(self.frame2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.headerLine = QtWidgets.QLineEdit(self.groupBox)
        self.headerLine.setObjectName("headerLine")
        self.gridLayout.addWidget(self.headerLine, 1, 1, 1, 1)
        self.outputLine = QtWidgets.QLineEdit(self.groupBox)
        self.outputLine.setReadOnly(True)
        self.outputLine.setObjectName("outputLine")
        self.gridLayout.addWidget(self.outputLine, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.browseButton = QtWidgets.QToolButton(self.groupBox)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 3, 1, 1)
        self.daysBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.daysBox.setMinimumSize(QtCore.QSize(70, 0))
        self.daysBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.daysBox.setMaximum(365)
        self.daysBox.setObjectName("daysBox")
        self.gridLayout_3.addWidget(self.daysBox, 0, 1, 1, 1)
        self.hoursBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.hoursBox.setMaximum(9999)
        self.hoursBox.setObjectName("hoursBox")
        self.gridLayout_3.addWidget(self.hoursBox, 1, 1, 1, 1)
        self.secondsBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.secondsBox.setMaximum(60)
        self.secondsBox.setObjectName("secondsBox")
        self.gridLayout_3.addWidget(self.secondsBox, 1, 4, 1, 1)
        self.minutesBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.minutesBox.setMinimumSize(QtCore.QSize(70, 0))
        self.minutesBox.setMaximum(60)
        self.minutesBox.setObjectName("minutesBox")
        self.gridLayout_3.addWidget(self.minutesBox, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(568, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.resetButton = QtWidgets.QPushButton(self.frame_3)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial monitor"))
        self.autoconnectBox.setText(_translate("MainWindow", "Autoconnect"))
        self.macLabel.setText(_translate("MainWindow", "MAC Address :"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Console"))
        self.groupBox.setTitle(_translate("MainWindow", "Output"))
        self.label_2.setText(_translate("MainWindow", "Header (CSV)"))
        self.label.setText(_translate("MainWindow", "Logs directory"))
        self.browseButton.setText(_translate("MainWindow", "..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Acquisition interval"))
        self.label_6.setText(_translate("MainWindow", "Minute(s)"))
        self.label_7.setText(_translate("MainWindow", "Second(s)     "))
        self.label_4.setText(_translate("MainWindow", "Day(s)"))
        self.label_5.setText(_translate("MainWindow", "Hour(s)"))
        self.resetButton.setText(_translate("MainWindow", "Reset to default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
