[tool.poetry]
name = "webframework"
version = "0.2.2"
description = "Framework para desarrollar tests automatizados"
authors = ["cmejia <cmejia@kiusys.com>", "iblanco <iblanco@kiusys.com>"]
readme = "README.md"
repository = "http://source.olleros/qa-automation/python-web-framework-automation"
keywords = [
    "framework",
    "python",
    "qa",
    "automation",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: Software Development :: Testing :: BDD",
]
packages = [
    { include = "webframework" },
]
exclude = ["samples"]

[tool.poetry.dependencies]
python = "^3.8"
behave = "^1.2.6"
selenium = "^3.141.0"
allure-behave = "^2.8.11"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.12.0"
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
