
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-02T15:08:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c325b65b6eb91fce55a2ab46438d326426b6efcb",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
