
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-02T17:13:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "816c3042886a35b6ac094e6fc491abaa2df9b460",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
