language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '2.6'
  - '3.2'
  - 'pypy'
  - 'nightly'

install:
  - python -c "import setuptools; print(setuptools.__version__)"
  - case ${TRAVIS_PYTHON_VERSION} in 2.6|2.7|pypy) pip install cryptography pyasn1 pyasn1-modules unittest2 ;; esac

  - pip install bzr+lp:~jayvdb/testscenarios/0.4-with_scenarios

script:
  - python setup.py test
