
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-25T09:59:21+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1f0e0ecd1f4704c97de1490ca99acf5558e6f2b",
 "version": "0.1.1-alpha.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
