environment:
  matrix:
    - TOXENV: py38
    - TOXENV: py37
    - TOXENV: py36
    - TOXENV: py35
    - TOXENV: py34
    - TOXENV: py27
install:
  - pip install tox
build: false
test_script:
  - git clone --depth 1 https://github.com/EFForg/https-everywhere
  - mv https-everywhere ..
  - tox
skip_branch_with_pr: true
