env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

Linux_task:
  container:
    matrix:
      - image: python:2.7
      - image: python:3.4
      - image: python:3.5
      - image: python:3.6
      - image: python:3.7
      - image: python:3.8
  install_script:
    - pip install -U tox
    - git clone --depth 1 https://github.com/EFForg/https-everywhere
    - mv https-everywhere ..
  script:
    - python --version
    - PY=$(python3 -c 'import sys; print("%d%d" % (sys.version_info[0], sys.version_info[1]))')
    - python -m tox -e py$PY

macOS_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install python3
    - pip3 install -U tox
    - git clone --depth 1 https://github.com/EFForg/https-everywhere
    - mv https-everywhere ..
  script:
    - python3 --version
    - python3 -m tox -e py
