
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-06T13:22:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "42d5cee73f8b380346cd40b17021c204d845965f",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
