
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-02T06:25:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "693703d7e6d6894fa1523812e2ed103ec1a08133",
 "version": "v2.0.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
