# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx_bsl/proto/model_spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfx_bsl/proto/model_spec.proto',
  package='tfx_bsl.model_spec',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1etfx_bsl/proto/model_spec.proto\x12\x12tfx_bsl.model_spec\"[\n\x11InferenceEndpoint\x12>\n\x10saved_model_spec\x18\x01 \x01(\x0b\x32\".tfx_bsl.model_spec.SavedModelSpecH\x00\x42\x06\n\x04type\"I\n\x0eSavedModelSpec\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x16\n\x0esignature_name\x18\x02 \x03(\t\x12\x0b\n\x03tag\x18\x03 \x03(\tb\x06proto3')
)




_INFERENCEENDPOINT = _descriptor.Descriptor(
  name='InferenceEndpoint',
  full_name='tfx_bsl.model_spec.InferenceEndpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='saved_model_spec', full_name='tfx_bsl.model_spec.InferenceEndpoint.saved_model_spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='tfx_bsl.model_spec.InferenceEndpoint.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=54,
  serialized_end=145,
)


_SAVEDMODELSPEC = _descriptor.Descriptor(
  name='SavedModelSpec',
  full_name='tfx_bsl.model_spec.SavedModelSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_path', full_name='tfx_bsl.model_spec.SavedModelSpec.model_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature_name', full_name='tfx_bsl.model_spec.SavedModelSpec.signature_name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='tfx_bsl.model_spec.SavedModelSpec.tag', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=220,
)

_INFERENCEENDPOINT.fields_by_name['saved_model_spec'].message_type = _SAVEDMODELSPEC
_INFERENCEENDPOINT.oneofs_by_name['type'].fields.append(
  _INFERENCEENDPOINT.fields_by_name['saved_model_spec'])
_INFERENCEENDPOINT.fields_by_name['saved_model_spec'].containing_oneof = _INFERENCEENDPOINT.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['InferenceEndpoint'] = _INFERENCEENDPOINT
DESCRIPTOR.message_types_by_name['SavedModelSpec'] = _SAVEDMODELSPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferenceEndpoint = _reflection.GeneratedProtocolMessageType('InferenceEndpoint', (_message.Message,), dict(
  DESCRIPTOR = _INFERENCEENDPOINT,
  __module__ = 'tfx_bsl.proto.model_spec_pb2'
  # @@protoc_insertion_point(class_scope:tfx_bsl.model_spec.InferenceEndpoint)
  ))
_sym_db.RegisterMessage(InferenceEndpoint)

SavedModelSpec = _reflection.GeneratedProtocolMessageType('SavedModelSpec', (_message.Message,), dict(
  DESCRIPTOR = _SAVEDMODELSPEC,
  __module__ = 'tfx_bsl.proto.model_spec_pb2'
  # @@protoc_insertion_point(class_scope:tfx_bsl.model_spec.SavedModelSpec)
  ))
_sym_db.RegisterMessage(SavedModelSpec)


# @@protoc_insertion_point(module_scope)
