[tool.poetry]
name = "businessowner-retriever"
version = "2.0.1"
description = "Tool to retrieve list of Vietnamese registered business owners."
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
readme = "README.md"
homepage = "https://bitbucket.org/hongquan/businessowner_retriever"
repository = "https://bitbucket.org/hongquan/businessowner_retriever.git"
license = "GPL-3.0-or-later"
keywords = ["Vietnamese", "business"]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Legal Industry",
    "Intended Audience :: Manufacturing",
    "Programming Language :: Python :: 3 :: Only"
]

[tool.poetry.dependencies]
python = "^3.7"
parsel = "^1.5.2"
click = "^7.0"
Logbook = "^1.5.2"
colorama = "^0.4.1"
terminaltables = "^3.1.0"
requests = {version = "^2.22.0", extras = ["socks"]}
named-enum = "^1.0.0"

[tool.poetry.dev-dependencies]
cx_Freeze = "^6.0"

[tool.poetry.scripts]
businessowner-retriever = 'businessowner_retriever:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

