# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_identifiers', '0003_switch_to_concept_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedidentifier',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
    ]
