
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <frc/commands/InstantCommand.h>



#include <rpygen/frc__Command.hpp>

namespace rpygen {

using namespace frc;


template <typename CxxBase>
using PyBasefrc__InstantCommand = 
    Pyfrc__Command<
        CxxBase
    
    >
;

template <typename CxxBase>
struct Pyfrc__InstantCommand : PyBasefrc__InstantCommand<CxxBase> {
    using PyBasefrc__InstantCommand<CxxBase>::PyBasefrc__InstantCommand;

#ifdef RPYGEN_ENABLE_frc__InstantCommand_PROTECTED_CONSTRUCTORS
    Pyfrc__InstantCommand() :
PyBasefrc__InstantCommand<CxxBase>()
    {}
#endif


#ifndef RPYGEN_DISABLE__Initialize_v
    void _Initialize() override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "_initialize", _Initialize,);    }
#endif

#ifndef RPYGEN_DISABLE_IsFinished_v
    bool IsFinished() override {
PYBIND11_OVERLOAD_NAME(bool, CxxBase, "isFinished", IsFinished,);    }
#endif



};

}; // namespace rpygen
