
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <frc/commands/PrintCommand.h>



#include <rpygen/frc__InstantCommand.hpp>

namespace rpygen {

using namespace frc;


template <typename CxxBase>
using PyBasefrc__PrintCommand = 
    Pyfrc__InstantCommand<
        CxxBase
    
    >
;

template <typename CxxBase>
struct Pyfrc__PrintCommand : PyBasefrc__PrintCommand<CxxBase> {
    using PyBasefrc__PrintCommand<CxxBase>::PyBasefrc__PrintCommand;



#ifndef RPYGEN_DISABLE_Initialize_v
    void Initialize() override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "initialize", Initialize,);    }
#endif



};

}; // namespace rpygen
