# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
