[package]
name = "tmsn-py"
version = "0.2.1"
authors = ["Julaiti Alafate <jalafate@gmail.com>"]

[lib]
name = "tmsn"
crate-type = ["cdylib"]

[dependencies.tmsn]
path = "../"
version = "0.2.0"

[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]
