name: Test Master Branch

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: Audit Python packages for known vulnerabilities
        run: ossaudit --installed --config setup.cfg --username ${{ secrets.OSS_USERNAME }} --token ${{ secrets.OSS_TOKEN }}
      - name: Run unit tests with coverage
        run: coverage run --source=marshmallow_objects setup.py test
      - name: Trigger codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
