# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0002_auto_20190212_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='choices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'Text'), ('html', 'Rich Text'), ('date', 'Date'), ('enum', 'Choice')], max_length=10),
        ),
    ]
