# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 07:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0006_auto_20190606_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='help_text_long',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Longer contextual help and business rules describing a field.'),
        ),
    ]
