# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_custom_fields', '0008_auto_20190711_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='allowed_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
