name: jupyterlab_documentation
channels:
  - conda-forge
dependencies:
- python=3.5
- sphinx>=1.8
- sphinx-copybutton
- sphinx_rtd_theme
- recommonmark
- pytest
- pip
- pip:
  - pytest-check-links
  - jsx-lexer
