apiVersion: v1
baseDomain: {{ domain }}
compute:
- name: worker
  replicas: {{ workers }}
controlPlane:
  name: master
  replicas: {{ masters }}
metadata:
  name: {{ cluster }}
networking:
  clusterNetworks:
{%- if ipv6 %}
  - cidr: fd35::/48
    hostPrefix: 64
{%- else %}
  - cidr: 10.132.0.0/14
    hostPrefix: 23
{%- endif %}
  networkType: {{ network_type | default('OpenShiftSDN') }}
  serviceNetwork:
  - 172.30.0.0/16
platform:
{%- if config_type == 'vsphere' %}
  vsphere:
    vcenter: {{ config_host }}
    username: {{ config_user }}
    password: {{ config_password }}
    datacenter: {{ config_datacenter }}
    defaultDatastore: {{ config_pool }}
{%- else %}
  none: {}
{%- endif %}
{%- if ca is defined %}
additionalTrustBundle: |
 {{ ca | replace('\n', '\n ') }}
{%- endif %}
pullSecret: '{{ pull_secret }}'
sshKey: |
  {{ pub_key }}
{% if disconnected_url is defined -%}
imageContentSources:
- mirrors:
  - {{ disconnected_url }}/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - {{ disconnected_url }}/ocp4/openshift4
  source: registry.svc.ci.openshift.org/ocp/release
{%- endif %}
