[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "jeepney"
author = "Thomas Kluyver"
author-email = "thomas@kluyver.me.uk"
home-page = "https://gitlab.com/takluyver/jeepney"
description-file = "README.rst"
requires-python = ">=3.5"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Desktop Environment"
]

[tool.flit.metadata.requires-extra]
dev = ["testpath"]

[tool.flit.metadata.urls]
Documentation = "https://jeepney.readthedocs.io/en/latest/"

