[tool.poetry]
name = "cambak"
version = "0.1.0"
description = "Camera Backup script"
authors = ["Michael Vieira <contact@mvieira.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"
pyyaml = "^5.3"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}
pycodestyle = "^2.5.0"

[tool.black]
line-length = 79
skip-string-normalization = false
include = '\.py$'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
