- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-tempest-dsvm-monasca-transform-python-functional:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-monasca-transform-python35-functional:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-tempest-dsvm-monasca-transform-python-functional:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

