---
- hosts: primary
  environment:
    KAYOBE_CONFIG_SOURCE_PATH: "{{ kayobe_config_src_dir }}"
  tasks:
    # NOTE(mgoddard): Use the name zz-overrides.yml to ensure this takes
    # precedence over the standard config files.
    - name: Ensure kayobe-config override config file exists
      template:
        src: overrides.yml.j2
        dest: "{{ kayobe_config_src_dir }}/etc/kayobe/zz-overrides.yml"

    # NOTE(mgoddard): The kayobe dev config by default expects a bridge -
    # breth1 - to exist with an IP address of 192.168.33.3.
    - name: Ensure all-in-one network bridge interface exists
      command: "{{ item }}"
      become: true
      with_items:
        - "ip l add breth1 type bridge"
        - "ip l set breth1 up"
        - "ip a add 192.168.33.3/24 dev breth1"

    - name: Ensure kayobe is installed
      shell:
        cmd: dev/install.sh > {{ logs_dir }}/ansible/install
        chdir: "{{ kayobe_src_dir }}"

    - name: Configure the firewall
      shell:
        cmd: dev/configure-firewall.sh
        chdir: "{{ kayobe_src_dir }}"
