[tool.poetry]
name = "pymail-aliyun"
version = "0.1.14"
description = "mail-aliyun wrapper"
authors = ["zbjdonald <service@yingchengtz.com>"]

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"


[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
imapclient = "^2.1.0"
simplejson = "^3.17.0"
beautifulsoup4 = "^4.8.1"
selenium = "^3.141.0"
optionaldict = "^0.1.1"
tqdm = "^4.41.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
